# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

from baml_core import define_function as _define_function


get       = _define_function("baml.env.get", "sync",  ["key"])
get.__doc__ = """Returns the value of the environment variable `key`, or `null` if not set.

Throws `ParseError` if the variable is set but its value is not valid
UTF-8 (the native bridge surfaces `std::env::VarError::NotUnicode` as a
catchable parse error).

Raises:
    Io, ParseError"""
get_async = _define_function("baml.env.get", "async", ["key"])
get_async.__doc__ = """Returns the value of the environment variable `key`, or `null` if not set.

Throws `ParseError` if the variable is set but its value is not valid
UTF-8 (the native bridge surfaces `std::env::VarError::NotUnicode` as a
catchable parse error).

Raises:
    Io, ParseError"""


get_or_panic       = _define_function("baml.env.get_or_panic", "sync",  ["key"])
get_or_panic.__doc__ = """Returns the value of the environment variable `key`. Panics if not set.

Raises:
    Io, ParseError"""
get_or_panic_async = _define_function("baml.env.get_or_panic", "async", ["key"])
get_or_panic_async.__doc__ = """Returns the value of the environment variable `key`. Panics if not set.

Raises:
    Io, ParseError"""


__all__ = [
    "get",
    "get_async",
    "get_or_panic",
    "get_or_panic_async",
]
