[package]
name = "agent-host"

[toolchain]
version = "local-dev"

# [scripts]
# dev = "-f main"

[generator.target]
output_type = "python/pydantic"
output_dir = "src"
naming_convention = "preserve-case"
