# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

from . import baml
from . import stream_types
from . import vendor

import enum
import typing
import pydantic

if typing.TYPE_CHECKING:
    from . import baml
    from . import stream_types
    from .baml import UNSET as UNSET


class ConversationMode(str, enum.Enum):
    WAKE_COMMAND = "WAKE_COMMAND"
    CONTINUOUS_CONVERSATION = "CONTINUOUS_CONVERSATION"


class AvailableTask(pydantic.BaseModel):
    id: str
    name: str
    description: str
    input: str
    output: str
    prompt: str
    provider_id: str
    created_at: str
    updated_at: str
    read_at: str


class ConversationHistoryMessage(pydantic.BaseModel):
    created_at: str
    updated_at: str
    read_at: str
    role: str
    content: str


class ConversationHistory(pydantic.BaseModel):
    id: str
    name: str
    created_at: str
    updated_at: str
    read_at: str
    messages: typing.List[ConversationHistoryMessage]


class SessionMemoryContext(pydantic.BaseModel):
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class TaskChoiceMemoryContext(pydantic.BaseModel):
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class ConversationEvaluationMemoryContext(pydantic.BaseModel):
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class SearchDepthMemoryContext(pydantic.BaseModel):
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class RelevanceMemoryContext(pydantic.BaseModel):
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class TaskPromptMemoryContext(pydantic.BaseModel):
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class SelectedTaskContext(pydantic.BaseModel):
    id: str
    name: str
    description: str
    input: str
    output: str
    prompt: str
    provider_id: str
    created_at: str
    updated_at: str
    read_at: str


class MemoryTagSearch(pydantic.BaseModel):
    any_of: typing.List[str]
    all_of: typing.List[str]
    none_of: typing.List[str]


class MemoryStringSearch(pydantic.BaseModel):
    contains: typing.List[str]
    equals: typing.List[str]


class CandidateMemory(pydantic.BaseModel):
    title: str
    description: str


class SearchDepthDomain(pydantic.BaseModel):
    id: str
    description: str
    searches: str
    hydrates: str


class SearchDepthTimestamps(pydantic.BaseModel):
    created_after: str
    read_after: str
    updated_after: str


class ConversationMemorySearchHints(pydantic.BaseModel):
    tags: MemoryTagSearch
    strings: MemoryStringSearch
    candidate_memory: typing.Optional[CandidateMemory]


class SearchDepthDecision(pydantic.BaseModel):
    depths: typing.Dict[str, SearchDepthTimestamps]
    candidate_memory: typing.Optional[CandidateMemory]


class RetrievedMemoryCandidate(pydantic.BaseModel):
    id: str
    kind: str
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str
    retrieval_matched: bool
    parent_session_id: typing.Optional[str]
    parent_conversation_id: typing.Optional[str]


class TaskPromptSelectedMemoryContext(pydantic.BaseModel):
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class RelevantMemoryDecision(pydantic.BaseModel):
    kept_memory_ids: typing.List[str]
    candidate_memory: typing.Optional[CandidateMemory]


class TaskChoiceDecision(pydantic.BaseModel):
    selected_task_id: str
    confidence: float
    reason: str
    agent_thought: typing.Optional[str]
    candidate_memory: typing.Optional[CandidateMemory]


class TaskPromptDecision(pydantic.BaseModel):
    full_task_prompt: str
    candidate_memory: typing.Optional[CandidateMemory]


class TaskReturnItem(pydantic.BaseModel):
    name: str
    payload: typing.Optional[typing.Dict[str, str]]


class TaskExecutionResult(pydantic.BaseModel):
    returns: typing.List[TaskReturnItem]


def ChooseInitialTask(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], available_tasks: typing.List[AvailableTask], task_choice_memories: typing.List[TaskChoiceMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> TaskChoiceDecision:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
async def ChooseInitialTask_async(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], available_tasks: typing.List[AvailableTask], task_choice_memories: typing.List[TaskChoiceMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> TaskChoiceDecision:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
def ChooseInitialTask__build_request(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], available_tasks: typing.List[AvailableTask], task_choice_memories: typing.List[TaskChoiceMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def ChooseInitialTask__build_request_async(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], available_tasks: typing.List[AvailableTask], task_choice_memories: typing.List[TaskChoiceMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def ChooseInitialTask__build_request_stream(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], available_tasks: typing.List[AvailableTask], task_choice_memories: typing.List[TaskChoiceMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def ChooseInitialTask__build_request_stream_async(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], available_tasks: typing.List[AvailableTask], task_choice_memories: typing.List[TaskChoiceMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def ChooseInitialTask__parse(json: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> TaskChoiceDecision:
    """Raises:
        LlmClient"""
async def ChooseInitialTask__parse_async(json: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> TaskChoiceDecision:
    """Raises:
        LlmClient"""
def ChooseInitialTask__parse_stream(sse: baml.http.SseStream, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.TaskChoiceDecision], TaskChoiceDecision]:
    """Raises:
        InvalidArgument, LlmClient"""
async def ChooseInitialTask__parse_stream_async(sse: baml.http.SseStream, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.TaskChoiceDecision], TaskChoiceDecision]:
    """Raises:
        InvalidArgument, LlmClient"""
def ChooseInitialTask__render_prompt(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], available_tasks: typing.List[AvailableTask], task_choice_memories: typing.List[TaskChoiceMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.PromptAst:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def ChooseInitialTask__render_prompt_async(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], available_tasks: typing.List[AvailableTask], task_choice_memories: typing.List[TaskChoiceMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.PromptAst:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def ChooseInitialTask_stream(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], available_tasks: typing.List[AvailableTask], task_choice_memories: typing.List[TaskChoiceMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.TaskChoiceDecision], TaskChoiceDecision]:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
async def ChooseInitialTask_stream_async(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], available_tasks: typing.List[AvailableTask], task_choice_memories: typing.List[TaskChoiceMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.TaskChoiceDecision], TaskChoiceDecision]:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


def GenerateTaskPrompt(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, selected_memories: typing.List[TaskPromptSelectedMemoryContext], task_prompt_memories: typing.List[TaskPromptMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> TaskPromptDecision:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
async def GenerateTaskPrompt_async(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, selected_memories: typing.List[TaskPromptSelectedMemoryContext], task_prompt_memories: typing.List[TaskPromptMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> TaskPromptDecision:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
def GenerateTaskPrompt__build_request(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, selected_memories: typing.List[TaskPromptSelectedMemoryContext], task_prompt_memories: typing.List[TaskPromptMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def GenerateTaskPrompt__build_request_async(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, selected_memories: typing.List[TaskPromptSelectedMemoryContext], task_prompt_memories: typing.List[TaskPromptMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def GenerateTaskPrompt__build_request_stream(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, selected_memories: typing.List[TaskPromptSelectedMemoryContext], task_prompt_memories: typing.List[TaskPromptMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def GenerateTaskPrompt__build_request_stream_async(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, selected_memories: typing.List[TaskPromptSelectedMemoryContext], task_prompt_memories: typing.List[TaskPromptMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def GenerateTaskPrompt__parse(json: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> TaskPromptDecision:
    """Raises:
        LlmClient"""
async def GenerateTaskPrompt__parse_async(json: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> TaskPromptDecision:
    """Raises:
        LlmClient"""
def GenerateTaskPrompt__parse_stream(sse: baml.http.SseStream, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.TaskPromptDecision], TaskPromptDecision]:
    """Raises:
        InvalidArgument, LlmClient"""
async def GenerateTaskPrompt__parse_stream_async(sse: baml.http.SseStream, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.TaskPromptDecision], TaskPromptDecision]:
    """Raises:
        InvalidArgument, LlmClient"""
def GenerateTaskPrompt__render_prompt(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, selected_memories: typing.List[TaskPromptSelectedMemoryContext], task_prompt_memories: typing.List[TaskPromptMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.PromptAst:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def GenerateTaskPrompt__render_prompt_async(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, selected_memories: typing.List[TaskPromptSelectedMemoryContext], task_prompt_memories: typing.List[TaskPromptMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.PromptAst:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def GenerateTaskPrompt_stream(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, selected_memories: typing.List[TaskPromptSelectedMemoryContext], task_prompt_memories: typing.List[TaskPromptMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.TaskPromptDecision], TaskPromptDecision]:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
async def GenerateTaskPrompt_stream_async(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, selected_memories: typing.List[TaskPromptSelectedMemoryContext], task_prompt_memories: typing.List[TaskPromptMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.TaskPromptDecision], TaskPromptDecision]:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


def ExecuteTask(full_task_prompt: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> TaskExecutionResult:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
async def ExecuteTask_async(full_task_prompt: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> TaskExecutionResult:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
def ExecuteTask__build_request(full_task_prompt: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def ExecuteTask__build_request_async(full_task_prompt: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def ExecuteTask__build_request_stream(full_task_prompt: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def ExecuteTask__build_request_stream_async(full_task_prompt: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def ExecuteTask__parse(json: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> TaskExecutionResult:
    """Raises:
        LlmClient"""
async def ExecuteTask__parse_async(json: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> TaskExecutionResult:
    """Raises:
        LlmClient"""
def ExecuteTask__parse_stream(sse: baml.http.SseStream, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.TaskExecutionResult], TaskExecutionResult]:
    """Raises:
        InvalidArgument, LlmClient"""
async def ExecuteTask__parse_stream_async(sse: baml.http.SseStream, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.TaskExecutionResult], TaskExecutionResult]:
    """Raises:
        InvalidArgument, LlmClient"""
def ExecuteTask__render_prompt(full_task_prompt: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.PromptAst:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def ExecuteTask__render_prompt_async(full_task_prompt: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.PromptAst:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def ExecuteTask_stream(full_task_prompt: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.TaskExecutionResult], TaskExecutionResult]:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
async def ExecuteTask_stream_async(full_task_prompt: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.TaskExecutionResult], TaskExecutionResult]:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


def EvaluateRelevantMemories(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, candidate_memories: typing.List[RetrievedMemoryCandidate], relevance_memories: typing.List[RelevanceMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> RelevantMemoryDecision:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
async def EvaluateRelevantMemories_async(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, candidate_memories: typing.List[RetrievedMemoryCandidate], relevance_memories: typing.List[RelevanceMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> RelevantMemoryDecision:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
def EvaluateRelevantMemories__build_request(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, candidate_memories: typing.List[RetrievedMemoryCandidate], relevance_memories: typing.List[RelevanceMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def EvaluateRelevantMemories__build_request_async(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, candidate_memories: typing.List[RetrievedMemoryCandidate], relevance_memories: typing.List[RelevanceMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def EvaluateRelevantMemories__build_request_stream(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, candidate_memories: typing.List[RetrievedMemoryCandidate], relevance_memories: typing.List[RelevanceMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def EvaluateRelevantMemories__build_request_stream_async(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, candidate_memories: typing.List[RetrievedMemoryCandidate], relevance_memories: typing.List[RelevanceMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def EvaluateRelevantMemories__parse(json: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> RelevantMemoryDecision:
    """Raises:
        LlmClient"""
async def EvaluateRelevantMemories__parse_async(json: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> RelevantMemoryDecision:
    """Raises:
        LlmClient"""
def EvaluateRelevantMemories__parse_stream(sse: baml.http.SseStream, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.RelevantMemoryDecision], RelevantMemoryDecision]:
    """Raises:
        InvalidArgument, LlmClient"""
async def EvaluateRelevantMemories__parse_stream_async(sse: baml.http.SseStream, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.RelevantMemoryDecision], RelevantMemoryDecision]:
    """Raises:
        InvalidArgument, LlmClient"""
def EvaluateRelevantMemories__render_prompt(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, candidate_memories: typing.List[RetrievedMemoryCandidate], relevance_memories: typing.List[RelevanceMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.PromptAst:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def EvaluateRelevantMemories__render_prompt_async(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, candidate_memories: typing.List[RetrievedMemoryCandidate], relevance_memories: typing.List[RelevanceMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.PromptAst:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def EvaluateRelevantMemories_stream(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, candidate_memories: typing.List[RetrievedMemoryCandidate], relevance_memories: typing.List[RelevanceMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.RelevantMemoryDecision], RelevantMemoryDecision]:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
async def EvaluateRelevantMemories_stream_async(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, candidate_memories: typing.List[RetrievedMemoryCandidate], relevance_memories: typing.List[RelevanceMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.RelevantMemoryDecision], RelevantMemoryDecision]:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


def EvaluateConversationForMemorySearch(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, conversation_evaluation_memories: typing.List[ConversationEvaluationMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> ConversationMemorySearchHints:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
async def EvaluateConversationForMemorySearch_async(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, conversation_evaluation_memories: typing.List[ConversationEvaluationMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> ConversationMemorySearchHints:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
def EvaluateConversationForMemorySearch__build_request(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, conversation_evaluation_memories: typing.List[ConversationEvaluationMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def EvaluateConversationForMemorySearch__build_request_async(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, conversation_evaluation_memories: typing.List[ConversationEvaluationMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def EvaluateConversationForMemorySearch__build_request_stream(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, conversation_evaluation_memories: typing.List[ConversationEvaluationMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def EvaluateConversationForMemorySearch__build_request_stream_async(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, conversation_evaluation_memories: typing.List[ConversationEvaluationMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def EvaluateConversationForMemorySearch__parse(json: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> ConversationMemorySearchHints:
    """Raises:
        LlmClient"""
async def EvaluateConversationForMemorySearch__parse_async(json: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> ConversationMemorySearchHints:
    """Raises:
        LlmClient"""
def EvaluateConversationForMemorySearch__parse_stream(sse: baml.http.SseStream, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.ConversationMemorySearchHints], ConversationMemorySearchHints]:
    """Raises:
        InvalidArgument, LlmClient"""
async def EvaluateConversationForMemorySearch__parse_stream_async(sse: baml.http.SseStream, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.ConversationMemorySearchHints], ConversationMemorySearchHints]:
    """Raises:
        InvalidArgument, LlmClient"""
def EvaluateConversationForMemorySearch__render_prompt(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, conversation_evaluation_memories: typing.List[ConversationEvaluationMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.PromptAst:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def EvaluateConversationForMemorySearch__render_prompt_async(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, conversation_evaluation_memories: typing.List[ConversationEvaluationMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.PromptAst:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def EvaluateConversationForMemorySearch_stream(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, conversation_evaluation_memories: typing.List[ConversationEvaluationMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.ConversationMemorySearchHints], ConversationMemorySearchHints]:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
async def EvaluateConversationForMemorySearch_stream_async(current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, conversation_evaluation_memories: typing.List[ConversationEvaluationMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.ConversationMemorySearchHints], ConversationMemorySearchHints]:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


def EvaluateSearchDepths(current_timestamp: str, current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, memory_search_hints: ConversationMemorySearchHints, search_domains: typing.List[SearchDepthDomain], search_depth_memories: typing.List[SearchDepthMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> SearchDepthDecision:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
async def EvaluateSearchDepths_async(current_timestamp: str, current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, memory_search_hints: ConversationMemorySearchHints, search_domains: typing.List[SearchDepthDomain], search_depth_memories: typing.List[SearchDepthMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> SearchDepthDecision:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
def EvaluateSearchDepths__build_request(current_timestamp: str, current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, memory_search_hints: ConversationMemorySearchHints, search_domains: typing.List[SearchDepthDomain], search_depth_memories: typing.List[SearchDepthMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def EvaluateSearchDepths__build_request_async(current_timestamp: str, current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, memory_search_hints: ConversationMemorySearchHints, search_domains: typing.List[SearchDepthDomain], search_depth_memories: typing.List[SearchDepthMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def EvaluateSearchDepths__build_request_stream(current_timestamp: str, current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, memory_search_hints: ConversationMemorySearchHints, search_domains: typing.List[SearchDepthDomain], search_depth_memories: typing.List[SearchDepthMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def EvaluateSearchDepths__build_request_stream_async(current_timestamp: str, current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, memory_search_hints: ConversationMemorySearchHints, search_domains: typing.List[SearchDepthDomain], search_depth_memories: typing.List[SearchDepthMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def EvaluateSearchDepths__parse(json: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> SearchDepthDecision:
    """Raises:
        LlmClient"""
async def EvaluateSearchDepths__parse_async(json: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> SearchDepthDecision:
    """Raises:
        LlmClient"""
def EvaluateSearchDepths__parse_stream(sse: baml.http.SseStream, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.SearchDepthDecision], SearchDepthDecision]:
    """Raises:
        InvalidArgument, LlmClient"""
async def EvaluateSearchDepths__parse_stream_async(sse: baml.http.SseStream, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.SearchDepthDecision], SearchDepthDecision]:
    """Raises:
        InvalidArgument, LlmClient"""
def EvaluateSearchDepths__render_prompt(current_timestamp: str, current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, memory_search_hints: ConversationMemorySearchHints, search_domains: typing.List[SearchDepthDomain], search_depth_memories: typing.List[SearchDepthMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.PromptAst:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def EvaluateSearchDepths__render_prompt_async(current_timestamp: str, current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, memory_search_hints: ConversationMemorySearchHints, search_domains: typing.List[SearchDepthDomain], search_depth_memories: typing.List[SearchDepthMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.PromptAst:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def EvaluateSearchDepths_stream(current_timestamp: str, current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, memory_search_hints: ConversationMemorySearchHints, search_domains: typing.List[SearchDepthDomain], search_depth_memories: typing.List[SearchDepthMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.SearchDepthDecision], SearchDepthDecision]:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
async def EvaluateSearchDepths_stream_async(current_timestamp: str, current_user_request: str, session_conversations: typing.List[ConversationHistory], session_memories: typing.List[SessionMemoryContext], selected_task: SelectedTaskContext, memory_search_hints: ConversationMemorySearchHints, search_domains: typing.List[SearchDepthDomain], search_depth_memories: typing.List[SearchDepthMemoryContext], *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.SearchDepthDecision], SearchDepthDecision]:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


__all__ = [
    "ConversationMode",
    "AvailableTask",
    "ConversationHistoryMessage",
    "ConversationHistory",
    "SessionMemoryContext",
    "TaskChoiceMemoryContext",
    "ConversationEvaluationMemoryContext",
    "SearchDepthMemoryContext",
    "RelevanceMemoryContext",
    "TaskPromptMemoryContext",
    "SelectedTaskContext",
    "MemoryTagSearch",
    "MemoryStringSearch",
    "CandidateMemory",
    "SearchDepthDomain",
    "SearchDepthTimestamps",
    "ConversationMemorySearchHints",
    "SearchDepthDecision",
    "RetrievedMemoryCandidate",
    "TaskPromptSelectedMemoryContext",
    "RelevantMemoryDecision",
    "TaskChoiceDecision",
    "TaskPromptDecision",
    "TaskReturnItem",
    "TaskExecutionResult",
    "ChooseInitialTask",
    "ChooseInitialTask_async",
    "ChooseInitialTask__build_request",
    "ChooseInitialTask__build_request_async",
    "ChooseInitialTask__build_request_stream",
    "ChooseInitialTask__build_request_stream_async",
    "ChooseInitialTask__parse",
    "ChooseInitialTask__parse_async",
    "ChooseInitialTask__parse_stream",
    "ChooseInitialTask__parse_stream_async",
    "ChooseInitialTask__render_prompt",
    "ChooseInitialTask__render_prompt_async",
    "ChooseInitialTask_stream",
    "ChooseInitialTask_stream_async",
    "GenerateTaskPrompt",
    "GenerateTaskPrompt_async",
    "GenerateTaskPrompt__build_request",
    "GenerateTaskPrompt__build_request_async",
    "GenerateTaskPrompt__build_request_stream",
    "GenerateTaskPrompt__build_request_stream_async",
    "GenerateTaskPrompt__parse",
    "GenerateTaskPrompt__parse_async",
    "GenerateTaskPrompt__parse_stream",
    "GenerateTaskPrompt__parse_stream_async",
    "GenerateTaskPrompt__render_prompt",
    "GenerateTaskPrompt__render_prompt_async",
    "GenerateTaskPrompt_stream",
    "GenerateTaskPrompt_stream_async",
    "ExecuteTask",
    "ExecuteTask_async",
    "ExecuteTask__build_request",
    "ExecuteTask__build_request_async",
    "ExecuteTask__build_request_stream",
    "ExecuteTask__build_request_stream_async",
    "ExecuteTask__parse",
    "ExecuteTask__parse_async",
    "ExecuteTask__parse_stream",
    "ExecuteTask__parse_stream_async",
    "ExecuteTask__render_prompt",
    "ExecuteTask__render_prompt_async",
    "ExecuteTask_stream",
    "ExecuteTask_stream_async",
    "EvaluateRelevantMemories",
    "EvaluateRelevantMemories_async",
    "EvaluateRelevantMemories__build_request",
    "EvaluateRelevantMemories__build_request_async",
    "EvaluateRelevantMemories__build_request_stream",
    "EvaluateRelevantMemories__build_request_stream_async",
    "EvaluateRelevantMemories__parse",
    "EvaluateRelevantMemories__parse_async",
    "EvaluateRelevantMemories__parse_stream",
    "EvaluateRelevantMemories__parse_stream_async",
    "EvaluateRelevantMemories__render_prompt",
    "EvaluateRelevantMemories__render_prompt_async",
    "EvaluateRelevantMemories_stream",
    "EvaluateRelevantMemories_stream_async",
    "EvaluateConversationForMemorySearch",
    "EvaluateConversationForMemorySearch_async",
    "EvaluateConversationForMemorySearch__build_request",
    "EvaluateConversationForMemorySearch__build_request_async",
    "EvaluateConversationForMemorySearch__build_request_stream",
    "EvaluateConversationForMemorySearch__build_request_stream_async",
    "EvaluateConversationForMemorySearch__parse",
    "EvaluateConversationForMemorySearch__parse_async",
    "EvaluateConversationForMemorySearch__parse_stream",
    "EvaluateConversationForMemorySearch__parse_stream_async",
    "EvaluateConversationForMemorySearch__render_prompt",
    "EvaluateConversationForMemorySearch__render_prompt_async",
    "EvaluateConversationForMemorySearch_stream",
    "EvaluateConversationForMemorySearch_stream_async",
    "EvaluateSearchDepths",
    "EvaluateSearchDepths_async",
    "EvaluateSearchDepths__build_request",
    "EvaluateSearchDepths__build_request_async",
    "EvaluateSearchDepths__build_request_stream",
    "EvaluateSearchDepths__build_request_stream_async",
    "EvaluateSearchDepths__parse",
    "EvaluateSearchDepths__parse_async",
    "EvaluateSearchDepths__parse_stream",
    "EvaluateSearchDepths__parse_stream_async",
    "EvaluateSearchDepths__render_prompt",
    "EvaluateSearchDepths__render_prompt_async",
    "EvaluateSearchDepths_stream",
    "EvaluateSearchDepths_stream_async",
]
