# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

from baml_core import BamlRuntime, set_type_map
from . import _inlinedbaml
from ._typemap import _TYPE_MAP

BamlRuntime.initialize_runtime_from_bytecode(_inlinedbaml.BYTECODE)

set_type_map(_TYPE_MAP)

_LAZY_CHILDREN = frozenset({
    "baml",
    "stream_types",
    "vendor",
})

def __getattr__(name):
    if name in _LAZY_CHILDREN:
        import importlib
        return importlib.import_module(f".{name}", __name__)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

import enum
import typing
import pydantic

if typing.TYPE_CHECKING:
    from . import baml
    from . import stream_types

from baml_core import define_function as _define_function


class ConversationMode(str, enum.Enum):
    WAKE_COMMAND = "WAKE_COMMAND"
    CONTINUOUS_CONVERSATION = "CONTINUOUS_CONVERSATION"


class AvailableTask(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: str
    name: str
    description: str
    input: str
    output: str
    prompt: str
    provider_id: str
    created_at: str
    updated_at: str
    read_at: str


class ConversationHistoryMessage(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    created_at: str
    updated_at: str
    read_at: str
    role: str
    content: str


class ConversationHistory(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: str
    name: str
    created_at: str
    updated_at: str
    read_at: str
    messages: typing.List[ConversationHistoryMessage]


class SessionMemoryContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class TaskChoiceMemoryContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class ConversationEvaluationMemoryContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class SearchDepthMemoryContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class RelevanceMemoryContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class TaskPromptMemoryContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class SelectedTaskContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: str
    name: str
    description: str
    input: str
    output: str
    prompt: str
    provider_id: str
    created_at: str
    updated_at: str
    read_at: str


class MemoryTagSearch(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    any_of: typing.List[str]
    all_of: typing.List[str]
    none_of: typing.List[str]


class MemoryStringSearch(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    contains: typing.List[str]
    equals: typing.List[str]


class CandidateMemory(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    title: str
    description: str


class SearchDepthDomain(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: str
    description: str
    searches: str
    hydrates: str


class SearchDepthTimestamps(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    created_after: str
    read_after: str
    updated_after: str


class ConversationMemorySearchHints(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    tags: MemoryTagSearch
    strings: MemoryStringSearch
    candidate_memory: typing.Optional[CandidateMemory]


class SearchDepthDecision(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    depths: typing.Dict[str, SearchDepthTimestamps]
    candidate_memory: typing.Optional[CandidateMemory]


class RetrievedMemoryCandidate(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: str
    kind: str
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str
    retrieval_matched: bool
    parent_session_id: typing.Optional[str]
    parent_conversation_id: typing.Optional[str]


class TaskPromptSelectedMemoryContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class RelevantMemoryDecision(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    kept_memory_ids: typing.List[str]
    candidate_memory: typing.Optional[CandidateMemory]


class TaskChoiceDecision(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    selected_task_id: str
    confidence: float
    reason: str
    agent_thought: typing.Optional[str]
    candidate_memory: typing.Optional[CandidateMemory]


class TaskPromptDecision(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    full_task_prompt: str
    candidate_memory: typing.Optional[CandidateMemory]


class TaskReturnItem(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    name: str
    payload: typing.Optional[typing.Dict[str, str]]


class TaskExecutionResult(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    returns: typing.List[TaskReturnItem]


ChooseInitialTask       = _define_function("user.ChooseInitialTask", "sync",  ["current_user_request", "session_conversations", "session_memories", "available_tasks", "task_choice_memories"], ["client"])
ChooseInitialTask.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
ChooseInitialTask_async = _define_function("user.ChooseInitialTask", "async", ["current_user_request", "session_conversations", "session_memories", "available_tasks", "task_choice_memories"], ["client"])
ChooseInitialTask_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
ChooseInitialTask__build_request       = _define_function("user.ChooseInitialTask$build_request", "sync",  ["current_user_request", "session_conversations", "session_memories", "available_tasks", "task_choice_memories"], ["client"])
ChooseInitialTask__build_request.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseInitialTask__build_request_async = _define_function("user.ChooseInitialTask$build_request", "async", ["current_user_request", "session_conversations", "session_memories", "available_tasks", "task_choice_memories"], ["client"])
ChooseInitialTask__build_request_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseInitialTask__build_request_stream       = _define_function("user.ChooseInitialTask$build_request_stream", "sync",  ["current_user_request", "session_conversations", "session_memories", "available_tasks", "task_choice_memories"], ["client"])
ChooseInitialTask__build_request_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseInitialTask__build_request_stream_async = _define_function("user.ChooseInitialTask$build_request_stream", "async", ["current_user_request", "session_conversations", "session_memories", "available_tasks", "task_choice_memories"], ["client"])
ChooseInitialTask__build_request_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseInitialTask__parse       = _define_function("user.ChooseInitialTask$parse", "sync",  ["json"], ["client"])
ChooseInitialTask__parse.__doc__ = """Raises:
    LlmClient"""
ChooseInitialTask__parse_async = _define_function("user.ChooseInitialTask$parse", "async", ["json"], ["client"])
ChooseInitialTask__parse_async.__doc__ = """Raises:
    LlmClient"""
ChooseInitialTask__parse_stream       = _define_function("user.ChooseInitialTask$parse_stream", "sync",  ["sse"], ["client"])
ChooseInitialTask__parse_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
ChooseInitialTask__parse_stream_async = _define_function("user.ChooseInitialTask$parse_stream", "async", ["sse"], ["client"])
ChooseInitialTask__parse_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
ChooseInitialTask__render_prompt       = _define_function("user.ChooseInitialTask$render_prompt", "sync",  ["current_user_request", "session_conversations", "session_memories", "available_tasks", "task_choice_memories"], ["client"])
ChooseInitialTask__render_prompt.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseInitialTask__render_prompt_async = _define_function("user.ChooseInitialTask$render_prompt", "async", ["current_user_request", "session_conversations", "session_memories", "available_tasks", "task_choice_memories"], ["client"])
ChooseInitialTask__render_prompt_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseInitialTask_stream       = _define_function("user.ChooseInitialTask$stream", "sync",  ["current_user_request", "session_conversations", "session_memories", "available_tasks", "task_choice_memories"], ["client"])
ChooseInitialTask_stream.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
ChooseInitialTask_stream_async = _define_function("user.ChooseInitialTask$stream", "async", ["current_user_request", "session_conversations", "session_memories", "available_tasks", "task_choice_memories"], ["client"])
ChooseInitialTask_stream_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


GenerateTaskPrompt       = _define_function("user.GenerateTaskPrompt", "sync",  ["current_user_request", "session_conversations", "session_memories", "selected_task", "selected_memories", "task_prompt_memories"], ["client"])
GenerateTaskPrompt.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
GenerateTaskPrompt_async = _define_function("user.GenerateTaskPrompt", "async", ["current_user_request", "session_conversations", "session_memories", "selected_task", "selected_memories", "task_prompt_memories"], ["client"])
GenerateTaskPrompt_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
GenerateTaskPrompt__build_request       = _define_function("user.GenerateTaskPrompt$build_request", "sync",  ["current_user_request", "session_conversations", "session_memories", "selected_task", "selected_memories", "task_prompt_memories"], ["client"])
GenerateTaskPrompt__build_request.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
GenerateTaskPrompt__build_request_async = _define_function("user.GenerateTaskPrompt$build_request", "async", ["current_user_request", "session_conversations", "session_memories", "selected_task", "selected_memories", "task_prompt_memories"], ["client"])
GenerateTaskPrompt__build_request_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
GenerateTaskPrompt__build_request_stream       = _define_function("user.GenerateTaskPrompt$build_request_stream", "sync",  ["current_user_request", "session_conversations", "session_memories", "selected_task", "selected_memories", "task_prompt_memories"], ["client"])
GenerateTaskPrompt__build_request_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
GenerateTaskPrompt__build_request_stream_async = _define_function("user.GenerateTaskPrompt$build_request_stream", "async", ["current_user_request", "session_conversations", "session_memories", "selected_task", "selected_memories", "task_prompt_memories"], ["client"])
GenerateTaskPrompt__build_request_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
GenerateTaskPrompt__parse       = _define_function("user.GenerateTaskPrompt$parse", "sync",  ["json"], ["client"])
GenerateTaskPrompt__parse.__doc__ = """Raises:
    LlmClient"""
GenerateTaskPrompt__parse_async = _define_function("user.GenerateTaskPrompt$parse", "async", ["json"], ["client"])
GenerateTaskPrompt__parse_async.__doc__ = """Raises:
    LlmClient"""
GenerateTaskPrompt__parse_stream       = _define_function("user.GenerateTaskPrompt$parse_stream", "sync",  ["sse"], ["client"])
GenerateTaskPrompt__parse_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
GenerateTaskPrompt__parse_stream_async = _define_function("user.GenerateTaskPrompt$parse_stream", "async", ["sse"], ["client"])
GenerateTaskPrompt__parse_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
GenerateTaskPrompt__render_prompt       = _define_function("user.GenerateTaskPrompt$render_prompt", "sync",  ["current_user_request", "session_conversations", "session_memories", "selected_task", "selected_memories", "task_prompt_memories"], ["client"])
GenerateTaskPrompt__render_prompt.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
GenerateTaskPrompt__render_prompt_async = _define_function("user.GenerateTaskPrompt$render_prompt", "async", ["current_user_request", "session_conversations", "session_memories", "selected_task", "selected_memories", "task_prompt_memories"], ["client"])
GenerateTaskPrompt__render_prompt_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
GenerateTaskPrompt_stream       = _define_function("user.GenerateTaskPrompt$stream", "sync",  ["current_user_request", "session_conversations", "session_memories", "selected_task", "selected_memories", "task_prompt_memories"], ["client"])
GenerateTaskPrompt_stream.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
GenerateTaskPrompt_stream_async = _define_function("user.GenerateTaskPrompt$stream", "async", ["current_user_request", "session_conversations", "session_memories", "selected_task", "selected_memories", "task_prompt_memories"], ["client"])
GenerateTaskPrompt_stream_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


ExecuteTask       = _define_function("user.ExecuteTask", "sync",  ["full_task_prompt"], ["client"])
ExecuteTask.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
ExecuteTask_async = _define_function("user.ExecuteTask", "async", ["full_task_prompt"], ["client"])
ExecuteTask_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
ExecuteTask__build_request       = _define_function("user.ExecuteTask$build_request", "sync",  ["full_task_prompt"], ["client"])
ExecuteTask__build_request.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ExecuteTask__build_request_async = _define_function("user.ExecuteTask$build_request", "async", ["full_task_prompt"], ["client"])
ExecuteTask__build_request_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ExecuteTask__build_request_stream       = _define_function("user.ExecuteTask$build_request_stream", "sync",  ["full_task_prompt"], ["client"])
ExecuteTask__build_request_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ExecuteTask__build_request_stream_async = _define_function("user.ExecuteTask$build_request_stream", "async", ["full_task_prompt"], ["client"])
ExecuteTask__build_request_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ExecuteTask__parse       = _define_function("user.ExecuteTask$parse", "sync",  ["json"], ["client"])
ExecuteTask__parse.__doc__ = """Raises:
    LlmClient"""
ExecuteTask__parse_async = _define_function("user.ExecuteTask$parse", "async", ["json"], ["client"])
ExecuteTask__parse_async.__doc__ = """Raises:
    LlmClient"""
ExecuteTask__parse_stream       = _define_function("user.ExecuteTask$parse_stream", "sync",  ["sse"], ["client"])
ExecuteTask__parse_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
ExecuteTask__parse_stream_async = _define_function("user.ExecuteTask$parse_stream", "async", ["sse"], ["client"])
ExecuteTask__parse_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
ExecuteTask__render_prompt       = _define_function("user.ExecuteTask$render_prompt", "sync",  ["full_task_prompt"], ["client"])
ExecuteTask__render_prompt.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ExecuteTask__render_prompt_async = _define_function("user.ExecuteTask$render_prompt", "async", ["full_task_prompt"], ["client"])
ExecuteTask__render_prompt_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ExecuteTask_stream       = _define_function("user.ExecuteTask$stream", "sync",  ["full_task_prompt"], ["client"])
ExecuteTask_stream.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
ExecuteTask_stream_async = _define_function("user.ExecuteTask$stream", "async", ["full_task_prompt"], ["client"])
ExecuteTask_stream_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


EvaluateRelevantMemories       = _define_function("user.EvaluateRelevantMemories", "sync",  ["current_user_request", "session_conversations", "session_memories", "selected_task", "candidate_memories", "relevance_memories"], ["client"])
EvaluateRelevantMemories.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
EvaluateRelevantMemories_async = _define_function("user.EvaluateRelevantMemories", "async", ["current_user_request", "session_conversations", "session_memories", "selected_task", "candidate_memories", "relevance_memories"], ["client"])
EvaluateRelevantMemories_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
EvaluateRelevantMemories__build_request       = _define_function("user.EvaluateRelevantMemories$build_request", "sync",  ["current_user_request", "session_conversations", "session_memories", "selected_task", "candidate_memories", "relevance_memories"], ["client"])
EvaluateRelevantMemories__build_request.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
EvaluateRelevantMemories__build_request_async = _define_function("user.EvaluateRelevantMemories$build_request", "async", ["current_user_request", "session_conversations", "session_memories", "selected_task", "candidate_memories", "relevance_memories"], ["client"])
EvaluateRelevantMemories__build_request_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
EvaluateRelevantMemories__build_request_stream       = _define_function("user.EvaluateRelevantMemories$build_request_stream", "sync",  ["current_user_request", "session_conversations", "session_memories", "selected_task", "candidate_memories", "relevance_memories"], ["client"])
EvaluateRelevantMemories__build_request_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
EvaluateRelevantMemories__build_request_stream_async = _define_function("user.EvaluateRelevantMemories$build_request_stream", "async", ["current_user_request", "session_conversations", "session_memories", "selected_task", "candidate_memories", "relevance_memories"], ["client"])
EvaluateRelevantMemories__build_request_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
EvaluateRelevantMemories__parse       = _define_function("user.EvaluateRelevantMemories$parse", "sync",  ["json"], ["client"])
EvaluateRelevantMemories__parse.__doc__ = """Raises:
    LlmClient"""
EvaluateRelevantMemories__parse_async = _define_function("user.EvaluateRelevantMemories$parse", "async", ["json"], ["client"])
EvaluateRelevantMemories__parse_async.__doc__ = """Raises:
    LlmClient"""
EvaluateRelevantMemories__parse_stream       = _define_function("user.EvaluateRelevantMemories$parse_stream", "sync",  ["sse"], ["client"])
EvaluateRelevantMemories__parse_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
EvaluateRelevantMemories__parse_stream_async = _define_function("user.EvaluateRelevantMemories$parse_stream", "async", ["sse"], ["client"])
EvaluateRelevantMemories__parse_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
EvaluateRelevantMemories__render_prompt       = _define_function("user.EvaluateRelevantMemories$render_prompt", "sync",  ["current_user_request", "session_conversations", "session_memories", "selected_task", "candidate_memories", "relevance_memories"], ["client"])
EvaluateRelevantMemories__render_prompt.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
EvaluateRelevantMemories__render_prompt_async = _define_function("user.EvaluateRelevantMemories$render_prompt", "async", ["current_user_request", "session_conversations", "session_memories", "selected_task", "candidate_memories", "relevance_memories"], ["client"])
EvaluateRelevantMemories__render_prompt_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
EvaluateRelevantMemories_stream       = _define_function("user.EvaluateRelevantMemories$stream", "sync",  ["current_user_request", "session_conversations", "session_memories", "selected_task", "candidate_memories", "relevance_memories"], ["client"])
EvaluateRelevantMemories_stream.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
EvaluateRelevantMemories_stream_async = _define_function("user.EvaluateRelevantMemories$stream", "async", ["current_user_request", "session_conversations", "session_memories", "selected_task", "candidate_memories", "relevance_memories"], ["client"])
EvaluateRelevantMemories_stream_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


EvaluateConversationForMemorySearch       = _define_function("user.EvaluateConversationForMemorySearch", "sync",  ["current_user_request", "session_conversations", "session_memories", "selected_task", "conversation_evaluation_memories"], ["client"])
EvaluateConversationForMemorySearch.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
EvaluateConversationForMemorySearch_async = _define_function("user.EvaluateConversationForMemorySearch", "async", ["current_user_request", "session_conversations", "session_memories", "selected_task", "conversation_evaluation_memories"], ["client"])
EvaluateConversationForMemorySearch_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
EvaluateConversationForMemorySearch__build_request       = _define_function("user.EvaluateConversationForMemorySearch$build_request", "sync",  ["current_user_request", "session_conversations", "session_memories", "selected_task", "conversation_evaluation_memories"], ["client"])
EvaluateConversationForMemorySearch__build_request.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
EvaluateConversationForMemorySearch__build_request_async = _define_function("user.EvaluateConversationForMemorySearch$build_request", "async", ["current_user_request", "session_conversations", "session_memories", "selected_task", "conversation_evaluation_memories"], ["client"])
EvaluateConversationForMemorySearch__build_request_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
EvaluateConversationForMemorySearch__build_request_stream       = _define_function("user.EvaluateConversationForMemorySearch$build_request_stream", "sync",  ["current_user_request", "session_conversations", "session_memories", "selected_task", "conversation_evaluation_memories"], ["client"])
EvaluateConversationForMemorySearch__build_request_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
EvaluateConversationForMemorySearch__build_request_stream_async = _define_function("user.EvaluateConversationForMemorySearch$build_request_stream", "async", ["current_user_request", "session_conversations", "session_memories", "selected_task", "conversation_evaluation_memories"], ["client"])
EvaluateConversationForMemorySearch__build_request_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
EvaluateConversationForMemorySearch__parse       = _define_function("user.EvaluateConversationForMemorySearch$parse", "sync",  ["json"], ["client"])
EvaluateConversationForMemorySearch__parse.__doc__ = """Raises:
    LlmClient"""
EvaluateConversationForMemorySearch__parse_async = _define_function("user.EvaluateConversationForMemorySearch$parse", "async", ["json"], ["client"])
EvaluateConversationForMemorySearch__parse_async.__doc__ = """Raises:
    LlmClient"""
EvaluateConversationForMemorySearch__parse_stream       = _define_function("user.EvaluateConversationForMemorySearch$parse_stream", "sync",  ["sse"], ["client"])
EvaluateConversationForMemorySearch__parse_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
EvaluateConversationForMemorySearch__parse_stream_async = _define_function("user.EvaluateConversationForMemorySearch$parse_stream", "async", ["sse"], ["client"])
EvaluateConversationForMemorySearch__parse_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
EvaluateConversationForMemorySearch__render_prompt       = _define_function("user.EvaluateConversationForMemorySearch$render_prompt", "sync",  ["current_user_request", "session_conversations", "session_memories", "selected_task", "conversation_evaluation_memories"], ["client"])
EvaluateConversationForMemorySearch__render_prompt.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
EvaluateConversationForMemorySearch__render_prompt_async = _define_function("user.EvaluateConversationForMemorySearch$render_prompt", "async", ["current_user_request", "session_conversations", "session_memories", "selected_task", "conversation_evaluation_memories"], ["client"])
EvaluateConversationForMemorySearch__render_prompt_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
EvaluateConversationForMemorySearch_stream       = _define_function("user.EvaluateConversationForMemorySearch$stream", "sync",  ["current_user_request", "session_conversations", "session_memories", "selected_task", "conversation_evaluation_memories"], ["client"])
EvaluateConversationForMemorySearch_stream.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
EvaluateConversationForMemorySearch_stream_async = _define_function("user.EvaluateConversationForMemorySearch$stream", "async", ["current_user_request", "session_conversations", "session_memories", "selected_task", "conversation_evaluation_memories"], ["client"])
EvaluateConversationForMemorySearch_stream_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


EvaluateSearchDepths       = _define_function("user.EvaluateSearchDepths", "sync",  ["current_timestamp", "current_user_request", "session_conversations", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories"], ["client"])
EvaluateSearchDepths.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
EvaluateSearchDepths_async = _define_function("user.EvaluateSearchDepths", "async", ["current_timestamp", "current_user_request", "session_conversations", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories"], ["client"])
EvaluateSearchDepths_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
EvaluateSearchDepths__build_request       = _define_function("user.EvaluateSearchDepths$build_request", "sync",  ["current_timestamp", "current_user_request", "session_conversations", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories"], ["client"])
EvaluateSearchDepths__build_request.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
EvaluateSearchDepths__build_request_async = _define_function("user.EvaluateSearchDepths$build_request", "async", ["current_timestamp", "current_user_request", "session_conversations", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories"], ["client"])
EvaluateSearchDepths__build_request_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
EvaluateSearchDepths__build_request_stream       = _define_function("user.EvaluateSearchDepths$build_request_stream", "sync",  ["current_timestamp", "current_user_request", "session_conversations", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories"], ["client"])
EvaluateSearchDepths__build_request_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
EvaluateSearchDepths__build_request_stream_async = _define_function("user.EvaluateSearchDepths$build_request_stream", "async", ["current_timestamp", "current_user_request", "session_conversations", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories"], ["client"])
EvaluateSearchDepths__build_request_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
EvaluateSearchDepths__parse       = _define_function("user.EvaluateSearchDepths$parse", "sync",  ["json"], ["client"])
EvaluateSearchDepths__parse.__doc__ = """Raises:
    LlmClient"""
EvaluateSearchDepths__parse_async = _define_function("user.EvaluateSearchDepths$parse", "async", ["json"], ["client"])
EvaluateSearchDepths__parse_async.__doc__ = """Raises:
    LlmClient"""
EvaluateSearchDepths__parse_stream       = _define_function("user.EvaluateSearchDepths$parse_stream", "sync",  ["sse"], ["client"])
EvaluateSearchDepths__parse_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
EvaluateSearchDepths__parse_stream_async = _define_function("user.EvaluateSearchDepths$parse_stream", "async", ["sse"], ["client"])
EvaluateSearchDepths__parse_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
EvaluateSearchDepths__render_prompt       = _define_function("user.EvaluateSearchDepths$render_prompt", "sync",  ["current_timestamp", "current_user_request", "session_conversations", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories"], ["client"])
EvaluateSearchDepths__render_prompt.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
EvaluateSearchDepths__render_prompt_async = _define_function("user.EvaluateSearchDepths$render_prompt", "async", ["current_timestamp", "current_user_request", "session_conversations", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories"], ["client"])
EvaluateSearchDepths__render_prompt_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
EvaluateSearchDepths_stream       = _define_function("user.EvaluateSearchDepths$stream", "sync",  ["current_timestamp", "current_user_request", "session_conversations", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories"], ["client"])
EvaluateSearchDepths_stream.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
EvaluateSearchDepths_stream_async = _define_function("user.EvaluateSearchDepths$stream", "async", ["current_timestamp", "current_user_request", "session_conversations", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories"], ["client"])
EvaluateSearchDepths_stream_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


__all__ = [
    "ConversationMode",
    "AvailableTask",
    "ConversationHistoryMessage",
    "ConversationHistory",
    "SessionMemoryContext",
    "TaskChoiceMemoryContext",
    "ConversationEvaluationMemoryContext",
    "SearchDepthMemoryContext",
    "RelevanceMemoryContext",
    "TaskPromptMemoryContext",
    "SelectedTaskContext",
    "MemoryTagSearch",
    "MemoryStringSearch",
    "CandidateMemory",
    "SearchDepthDomain",
    "SearchDepthTimestamps",
    "ConversationMemorySearchHints",
    "SearchDepthDecision",
    "RetrievedMemoryCandidate",
    "TaskPromptSelectedMemoryContext",
    "RelevantMemoryDecision",
    "TaskChoiceDecision",
    "TaskPromptDecision",
    "TaskReturnItem",
    "TaskExecutionResult",
    "ChooseInitialTask",
    "ChooseInitialTask_async",
    "ChooseInitialTask__build_request",
    "ChooseInitialTask__build_request_async",
    "ChooseInitialTask__build_request_stream",
    "ChooseInitialTask__build_request_stream_async",
    "ChooseInitialTask__parse",
    "ChooseInitialTask__parse_async",
    "ChooseInitialTask__parse_stream",
    "ChooseInitialTask__parse_stream_async",
    "ChooseInitialTask__render_prompt",
    "ChooseInitialTask__render_prompt_async",
    "ChooseInitialTask_stream",
    "ChooseInitialTask_stream_async",
    "GenerateTaskPrompt",
    "GenerateTaskPrompt_async",
    "GenerateTaskPrompt__build_request",
    "GenerateTaskPrompt__build_request_async",
    "GenerateTaskPrompt__build_request_stream",
    "GenerateTaskPrompt__build_request_stream_async",
    "GenerateTaskPrompt__parse",
    "GenerateTaskPrompt__parse_async",
    "GenerateTaskPrompt__parse_stream",
    "GenerateTaskPrompt__parse_stream_async",
    "GenerateTaskPrompt__render_prompt",
    "GenerateTaskPrompt__render_prompt_async",
    "GenerateTaskPrompt_stream",
    "GenerateTaskPrompt_stream_async",
    "ExecuteTask",
    "ExecuteTask_async",
    "ExecuteTask__build_request",
    "ExecuteTask__build_request_async",
    "ExecuteTask__build_request_stream",
    "ExecuteTask__build_request_stream_async",
    "ExecuteTask__parse",
    "ExecuteTask__parse_async",
    "ExecuteTask__parse_stream",
    "ExecuteTask__parse_stream_async",
    "ExecuteTask__render_prompt",
    "ExecuteTask__render_prompt_async",
    "ExecuteTask_stream",
    "ExecuteTask_stream_async",
    "EvaluateRelevantMemories",
    "EvaluateRelevantMemories_async",
    "EvaluateRelevantMemories__build_request",
    "EvaluateRelevantMemories__build_request_async",
    "EvaluateRelevantMemories__build_request_stream",
    "EvaluateRelevantMemories__build_request_stream_async",
    "EvaluateRelevantMemories__parse",
    "EvaluateRelevantMemories__parse_async",
    "EvaluateRelevantMemories__parse_stream",
    "EvaluateRelevantMemories__parse_stream_async",
    "EvaluateRelevantMemories__render_prompt",
    "EvaluateRelevantMemories__render_prompt_async",
    "EvaluateRelevantMemories_stream",
    "EvaluateRelevantMemories_stream_async",
    "EvaluateConversationForMemorySearch",
    "EvaluateConversationForMemorySearch_async",
    "EvaluateConversationForMemorySearch__build_request",
    "EvaluateConversationForMemorySearch__build_request_async",
    "EvaluateConversationForMemorySearch__build_request_stream",
    "EvaluateConversationForMemorySearch__build_request_stream_async",
    "EvaluateConversationForMemorySearch__parse",
    "EvaluateConversationForMemorySearch__parse_async",
    "EvaluateConversationForMemorySearch__parse_stream",
    "EvaluateConversationForMemorySearch__parse_stream_async",
    "EvaluateConversationForMemorySearch__render_prompt",
    "EvaluateConversationForMemorySearch__render_prompt_async",
    "EvaluateConversationForMemorySearch_stream",
    "EvaluateConversationForMemorySearch_stream_async",
    "EvaluateSearchDepths",
    "EvaluateSearchDepths_async",
    "EvaluateSearchDepths__build_request",
    "EvaluateSearchDepths__build_request_async",
    "EvaluateSearchDepths__build_request_stream",
    "EvaluateSearchDepths__build_request_stream_async",
    "EvaluateSearchDepths__parse",
    "EvaluateSearchDepths__parse_async",
    "EvaluateSearchDepths__parse_stream",
    "EvaluateSearchDepths__parse_stream_async",
    "EvaluateSearchDepths__render_prompt",
    "EvaluateSearchDepths__render_prompt_async",
    "EvaluateSearchDepths_stream",
    "EvaluateSearchDepths_stream_async",
]
