# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

from baml_core import BamlRuntime, set_type_map
from . import _inlinedbaml
from ._typemap import _TYPE_MAP

BamlRuntime.initialize_runtime_from_bytecode(_inlinedbaml.BYTECODE)

set_type_map(_TYPE_MAP)

_LAZY_CHILDREN = frozenset({
    "baml",
    "stream_types",
    "vendor",
})

def __getattr__(name):
    if name in _LAZY_CHILDREN:
        import importlib
        return importlib.import_module(f".{name}", __name__)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

import enum
import typing
import pydantic

if typing.TYPE_CHECKING:
    from . import baml
    from . import stream_types

from baml_core import define_function as _define_function


SummariseActionHistory       = _define_function("user.SummariseActionHistory", "sync",  ["current_conversation", "recorded_action_history"], ["client"])
SummariseActionHistory.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
SummariseActionHistory_async = _define_function("user.SummariseActionHistory", "async", ["current_conversation", "recorded_action_history"], ["client"])
SummariseActionHistory_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
SummariseActionHistory__build_request       = _define_function("user.SummariseActionHistory$build_request", "sync",  ["current_conversation", "recorded_action_history"], ["client"])
SummariseActionHistory__build_request.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
SummariseActionHistory__build_request_async = _define_function("user.SummariseActionHistory$build_request", "async", ["current_conversation", "recorded_action_history"], ["client"])
SummariseActionHistory__build_request_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
SummariseActionHistory__build_request_stream       = _define_function("user.SummariseActionHistory$build_request_stream", "sync",  ["current_conversation", "recorded_action_history"], ["client"])
SummariseActionHistory__build_request_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
SummariseActionHistory__build_request_stream_async = _define_function("user.SummariseActionHistory$build_request_stream", "async", ["current_conversation", "recorded_action_history"], ["client"])
SummariseActionHistory__build_request_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
SummariseActionHistory__parse       = _define_function("user.SummariseActionHistory$parse", "sync",  ["json"], ["client"])
SummariseActionHistory__parse.__doc__ = """Raises:
    LlmClient"""
SummariseActionHistory__parse_async = _define_function("user.SummariseActionHistory$parse", "async", ["json"], ["client"])
SummariseActionHistory__parse_async.__doc__ = """Raises:
    LlmClient"""
SummariseActionHistory__parse_stream       = _define_function("user.SummariseActionHistory$parse_stream", "sync",  ["sse"], ["client"])
SummariseActionHistory__parse_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
SummariseActionHistory__parse_stream_async = _define_function("user.SummariseActionHistory$parse_stream", "async", ["sse"], ["client"])
SummariseActionHistory__parse_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
SummariseActionHistory__render_prompt       = _define_function("user.SummariseActionHistory$render_prompt", "sync",  ["current_conversation", "recorded_action_history"], ["client"])
SummariseActionHistory__render_prompt.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
SummariseActionHistory__render_prompt_async = _define_function("user.SummariseActionHistory$render_prompt", "async", ["current_conversation", "recorded_action_history"], ["client"])
SummariseActionHistory__render_prompt_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
SummariseActionHistory_stream       = _define_function("user.SummariseActionHistory$stream", "sync",  ["current_conversation", "recorded_action_history"], ["client"])
SummariseActionHistory_stream.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
SummariseActionHistory_stream_async = _define_function("user.SummariseActionHistory$stream", "async", ["current_conversation", "recorded_action_history"], ["client"])
SummariseActionHistory_stream_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


class ConversationMode(str, enum.Enum):
    WAKE_COMMAND = "WAKE_COMMAND"
    CONTINUOUS_CONVERSATION = "CONTINUOUS_CONVERSATION"


class AvailableTask(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: str
    name: str
    description: str
    input: str
    output: str
    prompt: str
    provider_id: str
    created_at: str
    updated_at: str
    read_at: str


class ConversationHistoryMessage(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    created_at: str
    updated_at: str
    read_at: str
    role: str
    content: str


class ConversationHistory(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: str
    name: str
    created_at: str
    updated_at: str
    read_at: str
    messages: typing.List[ConversationHistoryMessage]


class SessionMemoryContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class TaskChoiceMemoryContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class ConversationEvaluationMemoryContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class SearchDepthMemoryContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class RelevanceMemoryContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class TaskPromptMemoryContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class SelectedTaskContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: str
    name: str
    description: str
    input: str
    output: str
    prompt: str
    provider_id: str
    created_at: str
    updated_at: str
    read_at: str


class MemoryTagSearch(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    any_of: typing.List[str]
    all_of: typing.List[str]
    none_of: typing.List[str]


class MemoryStringSearch(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    contains: typing.List[str]
    equals: typing.List[str]


class CandidateMemory(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    title: str
    description: str


class SearchDepthDomain(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: str
    description: str
    searches: str
    hydrates: str


class SearchDepthTimestamps(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    created_after: str
    read_after: str
    updated_after: str


class ConversationMemorySearchHints(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    tags: MemoryTagSearch
    strings: MemoryStringSearch
    candidate_memory: typing.Optional[CandidateMemory]


class SearchDepthDecision(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    depths: typing.Dict[str, SearchDepthTimestamps]
    candidate_memory: typing.Optional[CandidateMemory]


class RetrievedMemoryCandidate(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: str
    kind: str
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str
    retrieval_matched: bool
    parent_session_id: typing.Optional[str]
    parent_conversation_id: typing.Optional[str]


class TaskPromptSelectedMemoryContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class RelevantMemoryDecision(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    kept_memory_ids: typing.List[str]
    candidate_memory: typing.Optional[CandidateMemory]


class TaskChoiceDecision(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    selected_task_id: str
    confidence: float
    agent_thought: typing.Optional[str]
    candidate_memory: typing.Optional[CandidateMemory]


class TaskPromptDecision(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    full_task_prompt: str
    candidate_memory: typing.Optional[CandidateMemory]


class TaskPromptComposition(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    task_input: str
    candidate_memory: typing.Optional[CandidateMemory]


class TaskReturnItem(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    name: str
    payload: typing.Optional[typing.Dict[str, str]]


class TaskExecutionResult(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    returns: typing.List[TaskReturnItem]


SelectRelevantMemories       = _define_function("user.SelectRelevantMemories", "sync",  ["current_user_request", "current_conversation", "session_memories", "selected_task", "candidate_memories", "relevance_memories"], ["client"])
SelectRelevantMemories.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
SelectRelevantMemories_async = _define_function("user.SelectRelevantMemories", "async", ["current_user_request", "current_conversation", "session_memories", "selected_task", "candidate_memories", "relevance_memories"], ["client"])
SelectRelevantMemories_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
SelectRelevantMemories__build_request       = _define_function("user.SelectRelevantMemories$build_request", "sync",  ["current_user_request", "current_conversation", "session_memories", "selected_task", "candidate_memories", "relevance_memories"], ["client"])
SelectRelevantMemories__build_request.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
SelectRelevantMemories__build_request_async = _define_function("user.SelectRelevantMemories$build_request", "async", ["current_user_request", "current_conversation", "session_memories", "selected_task", "candidate_memories", "relevance_memories"], ["client"])
SelectRelevantMemories__build_request_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
SelectRelevantMemories__build_request_stream       = _define_function("user.SelectRelevantMemories$build_request_stream", "sync",  ["current_user_request", "current_conversation", "session_memories", "selected_task", "candidate_memories", "relevance_memories"], ["client"])
SelectRelevantMemories__build_request_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
SelectRelevantMemories__build_request_stream_async = _define_function("user.SelectRelevantMemories$build_request_stream", "async", ["current_user_request", "current_conversation", "session_memories", "selected_task", "candidate_memories", "relevance_memories"], ["client"])
SelectRelevantMemories__build_request_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
SelectRelevantMemories__parse       = _define_function("user.SelectRelevantMemories$parse", "sync",  ["json"], ["client"])
SelectRelevantMemories__parse.__doc__ = """Raises:
    LlmClient"""
SelectRelevantMemories__parse_async = _define_function("user.SelectRelevantMemories$parse", "async", ["json"], ["client"])
SelectRelevantMemories__parse_async.__doc__ = """Raises:
    LlmClient"""
SelectRelevantMemories__parse_stream       = _define_function("user.SelectRelevantMemories$parse_stream", "sync",  ["sse"], ["client"])
SelectRelevantMemories__parse_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
SelectRelevantMemories__parse_stream_async = _define_function("user.SelectRelevantMemories$parse_stream", "async", ["sse"], ["client"])
SelectRelevantMemories__parse_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
SelectRelevantMemories__render_prompt       = _define_function("user.SelectRelevantMemories$render_prompt", "sync",  ["current_user_request", "current_conversation", "session_memories", "selected_task", "candidate_memories", "relevance_memories"], ["client"])
SelectRelevantMemories__render_prompt.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
SelectRelevantMemories__render_prompt_async = _define_function("user.SelectRelevantMemories$render_prompt", "async", ["current_user_request", "current_conversation", "session_memories", "selected_task", "candidate_memories", "relevance_memories"], ["client"])
SelectRelevantMemories__render_prompt_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
SelectRelevantMemories_stream       = _define_function("user.SelectRelevantMemories$stream", "sync",  ["current_user_request", "current_conversation", "session_memories", "selected_task", "candidate_memories", "relevance_memories"], ["client"])
SelectRelevantMemories_stream.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
SelectRelevantMemories_stream_async = _define_function("user.SelectRelevantMemories$stream", "async", ["current_user_request", "current_conversation", "session_memories", "selected_task", "candidate_memories", "relevance_memories"], ["client"])
SelectRelevantMemories_stream_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


ChooseMemorySearch       = _define_function("user.ChooseMemorySearch", "sync",  ["current_user_request", "current_conversation", "session_memories", "selected_task", "conversation_evaluation_memories"], ["client"])
ChooseMemorySearch.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
ChooseMemorySearch_async = _define_function("user.ChooseMemorySearch", "async", ["current_user_request", "current_conversation", "session_memories", "selected_task", "conversation_evaluation_memories"], ["client"])
ChooseMemorySearch_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
ChooseMemorySearch__build_request       = _define_function("user.ChooseMemorySearch$build_request", "sync",  ["current_user_request", "current_conversation", "session_memories", "selected_task", "conversation_evaluation_memories"], ["client"])
ChooseMemorySearch__build_request.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearch__build_request_async = _define_function("user.ChooseMemorySearch$build_request", "async", ["current_user_request", "current_conversation", "session_memories", "selected_task", "conversation_evaluation_memories"], ["client"])
ChooseMemorySearch__build_request_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearch__build_request_stream       = _define_function("user.ChooseMemorySearch$build_request_stream", "sync",  ["current_user_request", "current_conversation", "session_memories", "selected_task", "conversation_evaluation_memories"], ["client"])
ChooseMemorySearch__build_request_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearch__build_request_stream_async = _define_function("user.ChooseMemorySearch$build_request_stream", "async", ["current_user_request", "current_conversation", "session_memories", "selected_task", "conversation_evaluation_memories"], ["client"])
ChooseMemorySearch__build_request_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearch__parse       = _define_function("user.ChooseMemorySearch$parse", "sync",  ["json"], ["client"])
ChooseMemorySearch__parse.__doc__ = """Raises:
    LlmClient"""
ChooseMemorySearch__parse_async = _define_function("user.ChooseMemorySearch$parse", "async", ["json"], ["client"])
ChooseMemorySearch__parse_async.__doc__ = """Raises:
    LlmClient"""
ChooseMemorySearch__parse_stream       = _define_function("user.ChooseMemorySearch$parse_stream", "sync",  ["sse"], ["client"])
ChooseMemorySearch__parse_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
ChooseMemorySearch__parse_stream_async = _define_function("user.ChooseMemorySearch$parse_stream", "async", ["sse"], ["client"])
ChooseMemorySearch__parse_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
ChooseMemorySearch__render_prompt       = _define_function("user.ChooseMemorySearch$render_prompt", "sync",  ["current_user_request", "current_conversation", "session_memories", "selected_task", "conversation_evaluation_memories"], ["client"])
ChooseMemorySearch__render_prompt.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearch__render_prompt_async = _define_function("user.ChooseMemorySearch$render_prompt", "async", ["current_user_request", "current_conversation", "session_memories", "selected_task", "conversation_evaluation_memories"], ["client"])
ChooseMemorySearch__render_prompt_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearch_stream       = _define_function("user.ChooseMemorySearch$stream", "sync",  ["current_user_request", "current_conversation", "session_memories", "selected_task", "conversation_evaluation_memories"], ["client"])
ChooseMemorySearch_stream.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
ChooseMemorySearch_stream_async = _define_function("user.ChooseMemorySearch$stream", "async", ["current_user_request", "current_conversation", "session_memories", "selected_task", "conversation_evaluation_memories"], ["client"])
ChooseMemorySearch_stream_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


class RetrievedTaskNode(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: str
    name: str
    description: str
    input: str
    output: str
    prompt: str
    provider_id: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class RetrievedSessionNode(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: str
    name: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class RetrievedSessionMemoryNode(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: str
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class RetrievedConversationNode(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: str
    name: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class RetrievedConversationMessageNode(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: str
    role: str
    content: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class RetrievedConversationGraph(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    conversation: RetrievedConversationNode
    matched: bool
    messages: typing.List[RetrievedConversationMessageNode]
    matched_message_ids: typing.List[str]


class RetrievedSessionGraph(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    session: RetrievedSessionNode
    matched: bool
    conversations: typing.List[RetrievedConversationGraph]
    session_memories: typing.List[RetrievedSessionMemoryNode]


class RetrievedMemoryGraph(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    task_catalog: typing.List[RetrievedTaskNode]
    past_sessions: typing.List[RetrievedSessionGraph]
    current_session_memories: typing.List[RetrievedSessionMemoryNode]


MemoryCandidates       = _define_function("user.MemoryCandidates", "sync",  ["memories", "current_session_id"])
MemoryCandidates_async = _define_function("user.MemoryCandidates", "async", ["memories", "current_session_id"])


RelevantMemoryGraph       = _define_function("user.RelevantMemoryGraph", "sync",  ["memories", "decision"])
RelevantMemoryGraph_async = _define_function("user.RelevantMemoryGraph", "async", ["memories", "decision"])


TaskPromptMemoryContexts       = _define_function("user.TaskPromptMemoryContexts", "sync",  ["memories", "selected_memory_ids", "current_session_id"])
TaskPromptMemoryContexts_async = _define_function("user.TaskPromptMemoryContexts", "async", ["memories", "selected_memory_ids", "current_session_id"])


RelevantSessionGraph       = _define_function("user.RelevantSessionGraph", "sync",  ["session", "kept_ids"])
RelevantSessionGraph_async = _define_function("user.RelevantSessionGraph", "async", ["session", "kept_ids"])


RelevantConversationGraph       = _define_function("user.RelevantConversationGraph", "sync",  ["conversation", "kept_ids"])
RelevantConversationGraph_async = _define_function("user.RelevantConversationGraph", "async", ["conversation", "kept_ids"])


TaskCandidate       = _define_function("user.TaskCandidate", "sync",  ["task"])
TaskCandidate_async = _define_function("user.TaskCandidate", "async", ["task"])


CurrentSessionMemoryCandidate       = _define_function("user.CurrentSessionMemoryCandidate", "sync",  ["memory", "current_session_id"])
CurrentSessionMemoryCandidate_async = _define_function("user.CurrentSessionMemoryCandidate", "async", ["memory", "current_session_id"])


SessionCandidate       = _define_function("user.SessionCandidate", "sync",  ["session", "is_current_session"])
SessionCandidate_async = _define_function("user.SessionCandidate", "async", ["session", "is_current_session"])


SessionMemoryCandidate       = _define_function("user.SessionMemoryCandidate", "sync",  ["session", "memory", "is_current_session"])
SessionMemoryCandidate_async = _define_function("user.SessionMemoryCandidate", "async", ["session", "memory", "is_current_session"])


ConversationCandidate       = _define_function("user.ConversationCandidate", "sync",  ["session", "conversation", "is_current_session"])
ConversationCandidate_async = _define_function("user.ConversationCandidate", "async", ["session", "conversation", "is_current_session"])


ConversationMessageCandidate       = _define_function("user.ConversationMessageCandidate", "sync",  ["session", "conversation", "message", "is_current_session"])
ConversationMessageCandidate_async = _define_function("user.ConversationMessageCandidate", "async", ["session", "conversation", "message", "is_current_session"])


TaskPromptContextFromTask       = _define_function("user.TaskPromptContextFromTask", "sync",  ["task"])
TaskPromptContextFromTask_async = _define_function("user.TaskPromptContextFromTask", "async", ["task"])


TaskPromptContextFromSession       = _define_function("user.TaskPromptContextFromSession", "sync",  ["session", "is_current_session"])
TaskPromptContextFromSession_async = _define_function("user.TaskPromptContextFromSession", "async", ["session", "is_current_session"])


TaskPromptContextFromConversation       = _define_function("user.TaskPromptContextFromConversation", "sync",  ["session", "conversation", "is_current_session"])
TaskPromptContextFromConversation_async = _define_function("user.TaskPromptContextFromConversation", "async", ["session", "conversation", "is_current_session"])


TaskPromptContextFromSessionMemory       = _define_function("user.TaskPromptContextFromSessionMemory", "sync",  ["memory"])
TaskPromptContextFromSessionMemory_async = _define_function("user.TaskPromptContextFromSessionMemory", "async", ["memory"])


TaskPromptContextFromMessage       = _define_function("user.TaskPromptContextFromMessage", "sync",  ["message"])
TaskPromptContextFromMessage_async = _define_function("user.TaskPromptContextFromMessage", "async", ["message"])


TaskCandidateDescription       = _define_function("user.TaskCandidateDescription", "sync",  ["task"])
TaskCandidateDescription_async = _define_function("user.TaskCandidateDescription", "async", ["task"])


MessageMatchedMemorySearch       = _define_function("user.MessageMatchedMemorySearch", "sync",  ["conversation", "message"])
MessageMatchedMemorySearch_async = _define_function("user.MessageMatchedMemorySearch", "async", ["conversation", "message"])


KeepSessionContextForPrompt       = _define_function("user.KeepSessionContextForPrompt", "sync",  ["session", "selected_ids"])
KeepSessionContextForPrompt_async = _define_function("user.KeepSessionContextForPrompt", "async", ["session", "selected_ids"])


KeepConversationContextForPrompt       = _define_function("user.KeepConversationContextForPrompt", "sync",  ["conversation", "selected_ids"])
KeepConversationContextForPrompt_async = _define_function("user.KeepConversationContextForPrompt", "async", ["conversation", "selected_ids"])


IsCurrentSession       = _define_function("user.IsCurrentSession", "sync",  ["session", "current_session_id"])
IsCurrentSession_async = _define_function("user.IsCurrentSession", "async", ["session", "current_session_id"])


ChooseMemorySearchDepths       = _define_function("user.ChooseMemorySearchDepths", "sync",  ["current_timestamp", "current_user_request", "current_conversation", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories"], ["client"])
ChooseMemorySearchDepths.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
ChooseMemorySearchDepths_async = _define_function("user.ChooseMemorySearchDepths", "async", ["current_timestamp", "current_user_request", "current_conversation", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories"], ["client"])
ChooseMemorySearchDepths_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
ChooseMemorySearchDepths__build_request       = _define_function("user.ChooseMemorySearchDepths$build_request", "sync",  ["current_timestamp", "current_user_request", "current_conversation", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories"], ["client"])
ChooseMemorySearchDepths__build_request.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearchDepths__build_request_async = _define_function("user.ChooseMemorySearchDepths$build_request", "async", ["current_timestamp", "current_user_request", "current_conversation", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories"], ["client"])
ChooseMemorySearchDepths__build_request_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearchDepths__build_request_stream       = _define_function("user.ChooseMemorySearchDepths$build_request_stream", "sync",  ["current_timestamp", "current_user_request", "current_conversation", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories"], ["client"])
ChooseMemorySearchDepths__build_request_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearchDepths__build_request_stream_async = _define_function("user.ChooseMemorySearchDepths$build_request_stream", "async", ["current_timestamp", "current_user_request", "current_conversation", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories"], ["client"])
ChooseMemorySearchDepths__build_request_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearchDepths__parse       = _define_function("user.ChooseMemorySearchDepths$parse", "sync",  ["json"], ["client"])
ChooseMemorySearchDepths__parse.__doc__ = """Raises:
    LlmClient"""
ChooseMemorySearchDepths__parse_async = _define_function("user.ChooseMemorySearchDepths$parse", "async", ["json"], ["client"])
ChooseMemorySearchDepths__parse_async.__doc__ = """Raises:
    LlmClient"""
ChooseMemorySearchDepths__parse_stream       = _define_function("user.ChooseMemorySearchDepths$parse_stream", "sync",  ["sse"], ["client"])
ChooseMemorySearchDepths__parse_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
ChooseMemorySearchDepths__parse_stream_async = _define_function("user.ChooseMemorySearchDepths$parse_stream", "async", ["sse"], ["client"])
ChooseMemorySearchDepths__parse_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
ChooseMemorySearchDepths__render_prompt       = _define_function("user.ChooseMemorySearchDepths$render_prompt", "sync",  ["current_timestamp", "current_user_request", "current_conversation", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories"], ["client"])
ChooseMemorySearchDepths__render_prompt.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearchDepths__render_prompt_async = _define_function("user.ChooseMemorySearchDepths$render_prompt", "async", ["current_timestamp", "current_user_request", "current_conversation", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories"], ["client"])
ChooseMemorySearchDepths__render_prompt_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearchDepths_stream       = _define_function("user.ChooseMemorySearchDepths$stream", "sync",  ["current_timestamp", "current_user_request", "current_conversation", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories"], ["client"])
ChooseMemorySearchDepths_stream.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
ChooseMemorySearchDepths_stream_async = _define_function("user.ChooseMemorySearchDepths$stream", "async", ["current_timestamp", "current_user_request", "current_conversation", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories"], ["client"])
ChooseMemorySearchDepths_stream_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


ChooseTask       = _define_function("user.ChooseTask", "sync",  ["current_user_request", "current_conversation", "session_memories", "available_tasks", "task_choice_memories"], ["client"])
ChooseTask.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
ChooseTask_async = _define_function("user.ChooseTask", "async", ["current_user_request", "current_conversation", "session_memories", "available_tasks", "task_choice_memories"], ["client"])
ChooseTask_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
ChooseTask__build_request       = _define_function("user.ChooseTask$build_request", "sync",  ["current_user_request", "current_conversation", "session_memories", "available_tasks", "task_choice_memories"], ["client"])
ChooseTask__build_request.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseTask__build_request_async = _define_function("user.ChooseTask$build_request", "async", ["current_user_request", "current_conversation", "session_memories", "available_tasks", "task_choice_memories"], ["client"])
ChooseTask__build_request_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseTask__build_request_stream       = _define_function("user.ChooseTask$build_request_stream", "sync",  ["current_user_request", "current_conversation", "session_memories", "available_tasks", "task_choice_memories"], ["client"])
ChooseTask__build_request_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseTask__build_request_stream_async = _define_function("user.ChooseTask$build_request_stream", "async", ["current_user_request", "current_conversation", "session_memories", "available_tasks", "task_choice_memories"], ["client"])
ChooseTask__build_request_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseTask__parse       = _define_function("user.ChooseTask$parse", "sync",  ["json"], ["client"])
ChooseTask__parse.__doc__ = """Raises:
    LlmClient"""
ChooseTask__parse_async = _define_function("user.ChooseTask$parse", "async", ["json"], ["client"])
ChooseTask__parse_async.__doc__ = """Raises:
    LlmClient"""
ChooseTask__parse_stream       = _define_function("user.ChooseTask$parse_stream", "sync",  ["sse"], ["client"])
ChooseTask__parse_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
ChooseTask__parse_stream_async = _define_function("user.ChooseTask$parse_stream", "async", ["sse"], ["client"])
ChooseTask__parse_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
ChooseTask__render_prompt       = _define_function("user.ChooseTask$render_prompt", "sync",  ["current_user_request", "current_conversation", "session_memories", "available_tasks", "task_choice_memories"], ["client"])
ChooseTask__render_prompt.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseTask__render_prompt_async = _define_function("user.ChooseTask$render_prompt", "async", ["current_user_request", "current_conversation", "session_memories", "available_tasks", "task_choice_memories"], ["client"])
ChooseTask__render_prompt_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseTask_stream       = _define_function("user.ChooseTask$stream", "sync",  ["current_user_request", "current_conversation", "session_memories", "available_tasks", "task_choice_memories"], ["client"])
ChooseTask_stream.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
ChooseTask_stream_async = _define_function("user.ChooseTask$stream", "async", ["current_user_request", "current_conversation", "session_memories", "available_tasks", "task_choice_memories"], ["client"])
ChooseTask_stream_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


PerformTask       = _define_function("user.PerformTask", "sync",  ["full_task_prompt"], ["client"])
PerformTask.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
PerformTask_async = _define_function("user.PerformTask", "async", ["full_task_prompt"], ["client"])
PerformTask_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
PerformTask__build_request       = _define_function("user.PerformTask$build_request", "sync",  ["full_task_prompt"], ["client"])
PerformTask__build_request.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
PerformTask__build_request_async = _define_function("user.PerformTask$build_request", "async", ["full_task_prompt"], ["client"])
PerformTask__build_request_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
PerformTask__build_request_stream       = _define_function("user.PerformTask$build_request_stream", "sync",  ["full_task_prompt"], ["client"])
PerformTask__build_request_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
PerformTask__build_request_stream_async = _define_function("user.PerformTask$build_request_stream", "async", ["full_task_prompt"], ["client"])
PerformTask__build_request_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
PerformTask__parse       = _define_function("user.PerformTask$parse", "sync",  ["json"], ["client"])
PerformTask__parse.__doc__ = """Raises:
    LlmClient"""
PerformTask__parse_async = _define_function("user.PerformTask$parse", "async", ["json"], ["client"])
PerformTask__parse_async.__doc__ = """Raises:
    LlmClient"""
PerformTask__parse_stream       = _define_function("user.PerformTask$parse_stream", "sync",  ["sse"], ["client"])
PerformTask__parse_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
PerformTask__parse_stream_async = _define_function("user.PerformTask$parse_stream", "async", ["sse"], ["client"])
PerformTask__parse_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
PerformTask__render_prompt       = _define_function("user.PerformTask$render_prompt", "sync",  ["full_task_prompt"], ["client"])
PerformTask__render_prompt.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
PerformTask__render_prompt_async = _define_function("user.PerformTask$render_prompt", "async", ["full_task_prompt"], ["client"])
PerformTask__render_prompt_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
PerformTask_stream       = _define_function("user.PerformTask$stream", "sync",  ["full_task_prompt"], ["client"])
PerformTask_stream.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
PerformTask_stream_async = _define_function("user.PerformTask$stream", "async", ["full_task_prompt"], ["client"])
PerformTask_stream_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


MemorySearchDomains       = _define_function("user.MemorySearchDomains", "sync",  [])
MemorySearchDomains_async = _define_function("user.MemorySearchDomains", "async", [])


SelectedTaskDetails       = _define_function("user.SelectedTaskDetails", "sync",  ["available_tasks", "selected_task_id"])
SelectedTaskDetails.__doc__ = """Raises:
    InvalidArgument"""
SelectedTaskDetails_async = _define_function("user.SelectedTaskDetails", "async", ["available_tasks", "selected_task_id"])
SelectedTaskDetails_async.__doc__ = """Raises:
    InvalidArgument"""


TaskPromptText       = _define_function("user.TaskPromptText", "sync",  ["selected_task_prompt", "task_input"])
TaskPromptText_async = _define_function("user.TaskPromptText", "async", ["selected_task_prompt", "task_input"])


FinishTaskPrompt       = _define_function("user.FinishTaskPrompt", "sync",  ["selected_task_prompt", "composition"])
FinishTaskPrompt_async = _define_function("user.FinishTaskPrompt", "async", ["selected_task_prompt", "composition"])


ComposeTaskInput       = _define_function("user.ComposeTaskInput", "sync",  ["current_user_request", "current_conversation", "session_memories", "selected_task", "selected_memories", "task_prompt_memories"], ["client"])
ComposeTaskInput.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
ComposeTaskInput_async = _define_function("user.ComposeTaskInput", "async", ["current_user_request", "current_conversation", "session_memories", "selected_task", "selected_memories", "task_prompt_memories"], ["client"])
ComposeTaskInput_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
ComposeTaskInput__build_request       = _define_function("user.ComposeTaskInput$build_request", "sync",  ["current_user_request", "current_conversation", "session_memories", "selected_task", "selected_memories", "task_prompt_memories"], ["client"])
ComposeTaskInput__build_request.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ComposeTaskInput__build_request_async = _define_function("user.ComposeTaskInput$build_request", "async", ["current_user_request", "current_conversation", "session_memories", "selected_task", "selected_memories", "task_prompt_memories"], ["client"])
ComposeTaskInput__build_request_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ComposeTaskInput__build_request_stream       = _define_function("user.ComposeTaskInput$build_request_stream", "sync",  ["current_user_request", "current_conversation", "session_memories", "selected_task", "selected_memories", "task_prompt_memories"], ["client"])
ComposeTaskInput__build_request_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ComposeTaskInput__build_request_stream_async = _define_function("user.ComposeTaskInput$build_request_stream", "async", ["current_user_request", "current_conversation", "session_memories", "selected_task", "selected_memories", "task_prompt_memories"], ["client"])
ComposeTaskInput__build_request_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ComposeTaskInput__parse       = _define_function("user.ComposeTaskInput$parse", "sync",  ["json"], ["client"])
ComposeTaskInput__parse.__doc__ = """Raises:
    LlmClient"""
ComposeTaskInput__parse_async = _define_function("user.ComposeTaskInput$parse", "async", ["json"], ["client"])
ComposeTaskInput__parse_async.__doc__ = """Raises:
    LlmClient"""
ComposeTaskInput__parse_stream       = _define_function("user.ComposeTaskInput$parse_stream", "sync",  ["sse"], ["client"])
ComposeTaskInput__parse_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
ComposeTaskInput__parse_stream_async = _define_function("user.ComposeTaskInput$parse_stream", "async", ["sse"], ["client"])
ComposeTaskInput__parse_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
ComposeTaskInput__render_prompt       = _define_function("user.ComposeTaskInput$render_prompt", "sync",  ["current_user_request", "current_conversation", "session_memories", "selected_task", "selected_memories", "task_prompt_memories"], ["client"])
ComposeTaskInput__render_prompt.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ComposeTaskInput__render_prompt_async = _define_function("user.ComposeTaskInput$render_prompt", "async", ["current_user_request", "current_conversation", "session_memories", "selected_task", "selected_memories", "task_prompt_memories"], ["client"])
ComposeTaskInput__render_prompt_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ComposeTaskInput_stream       = _define_function("user.ComposeTaskInput$stream", "sync",  ["current_user_request", "current_conversation", "session_memories", "selected_task", "selected_memories", "task_prompt_memories"], ["client"])
ComposeTaskInput_stream.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
ComposeTaskInput_stream_async = _define_function("user.ComposeTaskInput$stream", "async", ["current_user_request", "current_conversation", "session_memories", "selected_task", "selected_memories", "task_prompt_memories"], ["client"])
ComposeTaskInput_stream_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


class VoicePromptUnderstanding(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    task_choice: TaskChoiceDecision
    selected_task: SelectedTaskContext
    memory_search_hints: ConversationMemorySearchHints
    search_depths: SearchDepthDecision
    timings: VoicePromptUnderstandingTimings


class VoicePromptContinuation(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    relevance_decision: RelevantMemoryDecision
    selected_memories: RetrievedMemoryGraph
    selected_memory_contexts: typing.List[TaskPromptSelectedMemoryContext]
    task_prompt: TaskPromptDecision
    timings: VoicePromptContinuationTimings


class VoicePromptUnderstandingTimings(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    task_choice_ms: int
    memory_search_ms: int
    search_depth_ms: int


class VoicePromptContinuationTimings(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    memory_relevance_ms: int
    task_prompt_ms: int


UnderstandVoicePrompt       = _define_function("user.UnderstandVoicePrompt", "sync",  ["current_timestamp", "current_user_request", "current_conversation", "session_memories", "available_tasks", "task_choice_memories", "conversation_evaluation_memories", "search_depth_memories"])
UnderstandVoicePrompt.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
UnderstandVoicePrompt_async = _define_function("user.UnderstandVoicePrompt", "async", ["current_timestamp", "current_user_request", "current_conversation", "session_memories", "available_tasks", "task_choice_memories", "conversation_evaluation_memories", "search_depth_memories"])
UnderstandVoicePrompt_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


ContinueVoicePrompt       = _define_function("user.ContinueVoicePrompt", "sync",  ["current_user_request", "current_conversation", "session_memories", "selected_task", "retrieved_memories", "current_session_id", "relevance_memories", "task_prompt_memories"])
ContinueVoicePrompt.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
ContinueVoicePrompt_async = _define_function("user.ContinueVoicePrompt", "async", ["current_user_request", "current_conversation", "session_memories", "selected_task", "retrieved_memories", "current_session_id", "relevance_memories", "task_prompt_memories"])
ContinueVoicePrompt_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


__all__ = [
    "SummariseActionHistory",
    "SummariseActionHistory_async",
    "SummariseActionHistory__build_request",
    "SummariseActionHistory__build_request_async",
    "SummariseActionHistory__build_request_stream",
    "SummariseActionHistory__build_request_stream_async",
    "SummariseActionHistory__parse",
    "SummariseActionHistory__parse_async",
    "SummariseActionHistory__parse_stream",
    "SummariseActionHistory__parse_stream_async",
    "SummariseActionHistory__render_prompt",
    "SummariseActionHistory__render_prompt_async",
    "SummariseActionHistory_stream",
    "SummariseActionHistory_stream_async",
    "ConversationMode",
    "AvailableTask",
    "ConversationHistoryMessage",
    "ConversationHistory",
    "SessionMemoryContext",
    "TaskChoiceMemoryContext",
    "ConversationEvaluationMemoryContext",
    "SearchDepthMemoryContext",
    "RelevanceMemoryContext",
    "TaskPromptMemoryContext",
    "SelectedTaskContext",
    "MemoryTagSearch",
    "MemoryStringSearch",
    "CandidateMemory",
    "SearchDepthDomain",
    "SearchDepthTimestamps",
    "ConversationMemorySearchHints",
    "SearchDepthDecision",
    "RetrievedMemoryCandidate",
    "TaskPromptSelectedMemoryContext",
    "RelevantMemoryDecision",
    "TaskChoiceDecision",
    "TaskPromptDecision",
    "TaskPromptComposition",
    "TaskReturnItem",
    "TaskExecutionResult",
    "SelectRelevantMemories",
    "SelectRelevantMemories_async",
    "SelectRelevantMemories__build_request",
    "SelectRelevantMemories__build_request_async",
    "SelectRelevantMemories__build_request_stream",
    "SelectRelevantMemories__build_request_stream_async",
    "SelectRelevantMemories__parse",
    "SelectRelevantMemories__parse_async",
    "SelectRelevantMemories__parse_stream",
    "SelectRelevantMemories__parse_stream_async",
    "SelectRelevantMemories__render_prompt",
    "SelectRelevantMemories__render_prompt_async",
    "SelectRelevantMemories_stream",
    "SelectRelevantMemories_stream_async",
    "ChooseMemorySearch",
    "ChooseMemorySearch_async",
    "ChooseMemorySearch__build_request",
    "ChooseMemorySearch__build_request_async",
    "ChooseMemorySearch__build_request_stream",
    "ChooseMemorySearch__build_request_stream_async",
    "ChooseMemorySearch__parse",
    "ChooseMemorySearch__parse_async",
    "ChooseMemorySearch__parse_stream",
    "ChooseMemorySearch__parse_stream_async",
    "ChooseMemorySearch__render_prompt",
    "ChooseMemorySearch__render_prompt_async",
    "ChooseMemorySearch_stream",
    "ChooseMemorySearch_stream_async",
    "RetrievedTaskNode",
    "RetrievedSessionNode",
    "RetrievedSessionMemoryNode",
    "RetrievedConversationNode",
    "RetrievedConversationMessageNode",
    "RetrievedConversationGraph",
    "RetrievedSessionGraph",
    "RetrievedMemoryGraph",
    "MemoryCandidates",
    "MemoryCandidates_async",
    "RelevantMemoryGraph",
    "RelevantMemoryGraph_async",
    "TaskPromptMemoryContexts",
    "TaskPromptMemoryContexts_async",
    "RelevantSessionGraph",
    "RelevantSessionGraph_async",
    "RelevantConversationGraph",
    "RelevantConversationGraph_async",
    "TaskCandidate",
    "TaskCandidate_async",
    "CurrentSessionMemoryCandidate",
    "CurrentSessionMemoryCandidate_async",
    "SessionCandidate",
    "SessionCandidate_async",
    "SessionMemoryCandidate",
    "SessionMemoryCandidate_async",
    "ConversationCandidate",
    "ConversationCandidate_async",
    "ConversationMessageCandidate",
    "ConversationMessageCandidate_async",
    "TaskPromptContextFromTask",
    "TaskPromptContextFromTask_async",
    "TaskPromptContextFromSession",
    "TaskPromptContextFromSession_async",
    "TaskPromptContextFromConversation",
    "TaskPromptContextFromConversation_async",
    "TaskPromptContextFromSessionMemory",
    "TaskPromptContextFromSessionMemory_async",
    "TaskPromptContextFromMessage",
    "TaskPromptContextFromMessage_async",
    "TaskCandidateDescription",
    "TaskCandidateDescription_async",
    "MessageMatchedMemorySearch",
    "MessageMatchedMemorySearch_async",
    "KeepSessionContextForPrompt",
    "KeepSessionContextForPrompt_async",
    "KeepConversationContextForPrompt",
    "KeepConversationContextForPrompt_async",
    "IsCurrentSession",
    "IsCurrentSession_async",
    "ChooseMemorySearchDepths",
    "ChooseMemorySearchDepths_async",
    "ChooseMemorySearchDepths__build_request",
    "ChooseMemorySearchDepths__build_request_async",
    "ChooseMemorySearchDepths__build_request_stream",
    "ChooseMemorySearchDepths__build_request_stream_async",
    "ChooseMemorySearchDepths__parse",
    "ChooseMemorySearchDepths__parse_async",
    "ChooseMemorySearchDepths__parse_stream",
    "ChooseMemorySearchDepths__parse_stream_async",
    "ChooseMemorySearchDepths__render_prompt",
    "ChooseMemorySearchDepths__render_prompt_async",
    "ChooseMemorySearchDepths_stream",
    "ChooseMemorySearchDepths_stream_async",
    "ChooseTask",
    "ChooseTask_async",
    "ChooseTask__build_request",
    "ChooseTask__build_request_async",
    "ChooseTask__build_request_stream",
    "ChooseTask__build_request_stream_async",
    "ChooseTask__parse",
    "ChooseTask__parse_async",
    "ChooseTask__parse_stream",
    "ChooseTask__parse_stream_async",
    "ChooseTask__render_prompt",
    "ChooseTask__render_prompt_async",
    "ChooseTask_stream",
    "ChooseTask_stream_async",
    "PerformTask",
    "PerformTask_async",
    "PerformTask__build_request",
    "PerformTask__build_request_async",
    "PerformTask__build_request_stream",
    "PerformTask__build_request_stream_async",
    "PerformTask__parse",
    "PerformTask__parse_async",
    "PerformTask__parse_stream",
    "PerformTask__parse_stream_async",
    "PerformTask__render_prompt",
    "PerformTask__render_prompt_async",
    "PerformTask_stream",
    "PerformTask_stream_async",
    "MemorySearchDomains",
    "MemorySearchDomains_async",
    "SelectedTaskDetails",
    "SelectedTaskDetails_async",
    "TaskPromptText",
    "TaskPromptText_async",
    "FinishTaskPrompt",
    "FinishTaskPrompt_async",
    "ComposeTaskInput",
    "ComposeTaskInput_async",
    "ComposeTaskInput__build_request",
    "ComposeTaskInput__build_request_async",
    "ComposeTaskInput__build_request_stream",
    "ComposeTaskInput__build_request_stream_async",
    "ComposeTaskInput__parse",
    "ComposeTaskInput__parse_async",
    "ComposeTaskInput__parse_stream",
    "ComposeTaskInput__parse_stream_async",
    "ComposeTaskInput__render_prompt",
    "ComposeTaskInput__render_prompt_async",
    "ComposeTaskInput_stream",
    "ComposeTaskInput_stream_async",
    "VoicePromptUnderstanding",
    "VoicePromptContinuation",
    "VoicePromptUnderstandingTimings",
    "VoicePromptContinuationTimings",
    "UnderstandVoicePrompt",
    "UnderstandVoicePrompt_async",
    "ContinueVoicePrompt",
    "ContinueVoicePrompt_async",
]
