# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import typing
import pydantic

if typing.TYPE_CHECKING:
    from ... import baml


T = typing.TypeVar("T")


class YamlParseError(pydantic.BaseModel):
    message: str


def parse(s: str) -> baml.json.json:
    """Raises:
        YamlParseError"""
async def parse_async(s: str) -> baml.json.json:
    """Raises:
        YamlParseError"""


def deserialize(s: str, *, _types: dict[str, type]) -> T:
    """Parses YAML text and decodes it to `T`, honoring user-defined `baml.FromJson`
    overrides (via `baml.json.from_json<T>`). The YAML counterpart of
    `baml.json.deserialize<T>`. Parsing throws `YamlParseError`; decoding the
    resulting `json` into `T` throws `JsonDecodeError` (decoding never re-parses,
    so no `JsonParseError` arises here).
    
    Raises:
        YamlParseError, JsonDecodeError"""
async def deserialize_async(s: str, *, _types: dict[str, type]) -> T:
    """Parses YAML text and decodes it to `T`, honoring user-defined `baml.FromJson`
    overrides (via `baml.json.from_json<T>`). The YAML counterpart of
    `baml.json.deserialize<T>`. Parsing throws `YamlParseError`; decoding the
    resulting `json` into `T` throws `JsonDecodeError` (decoding never re-parses,
    so no `JsonParseError` arises here).
    
    Raises:
        YamlParseError, JsonDecodeError"""


__all__ = [
    "YamlParseError",
    "parse",
    "parse_async",
    "deserialize",
    "deserialize_async",
]
