# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import typing
import pydantic

from baml_core import BamlPyHandle as _BamlPyHandle


E = typing.TypeVar("E")
T = typing.TypeVar("T")


class CancelToken(pydantic.BaseModel):
    _handle: _BamlPyHandle


class SpawnParams(pydantic.BaseModel, typing.Generic[T, E]):
    body: typing.Any
    name: typing.Optional[str]
    group: typing.Optional[TaskGroup]
    cancel: typing.Optional[CancelToken]
    detach: typing.Optional[bool]


class TaskGroup(pydantic.BaseModel):
    _handle: _BamlPyHandle


__all__ = [
    "CancelToken",
    "SpawnParams",
    "TaskGroup",
]
