# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import typing
import pydantic

from baml_core import BamlPyHandle as _BamlPyHandle


E = typing.TypeVar("E")
T = typing.TypeVar("T")


class CancelToken(pydantic.BaseModel):
    """
    A cooperative, one-shot cancellation handle backed by a runtime
    cancellation token. Passing one via `options(cancel = ...)` links it into a
    spawned task's effective token: once fired, the task's next `await` throws
    `baml.panics.Cancelled`. Once cancelled, a token stays cancelled forever.
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    _handle: _BamlPyHandle


class SpawnParams(pydantic.BaseModel, typing.Generic[T, E]):
    """
    BEP-034 — spawn options and `with` middleware.
    
    This namespace holds the values a `spawn` can be configured with: a
    `CancelToken` for cooperative cancellation, a `TaskGroup` for rate
    limiting, and the `detach` flag — plus `SpawnParams`, the value a
    `spawn ... with` middleware pipeline transforms before the runtime
    creates the future.
    Every `spawn` implicitly constructs a `SpawnParams` from its name and
    body; the `with` pipeline transforms it left-to-right before the runtime
    creates the future. Each transformer is an ordinary function
    `(SpawnParams<T, E>) -> SpawnParams<U, F>` — it may set config fields,
    wrap `body` (retry, timing), or replace it entirely (type-changing
    transformers like a fallback that erases the error type).
    
    NOTE for the runtime: the engine reads these fields BY INDEX at the spawn
    dispatch site (body=0, name=1, group=2, cancel=3, detach=4) — keep the
    declaration order in sync with `bex_engine`'s `read_spawn_params`.
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    body: typing.Any
    name: typing.Optional[str]
    group: typing.Optional[TaskGroup]
    cancel: typing.Optional[CancelToken]
    detach: typing.Optional[bool]


class TaskGroup(pydantic.BaseModel):
    """
    Caps how many spawns referencing it run concurrently. Excess spawns queue
    FIFO and start as earlier ones settle; the `spawn` still returns its
    `Future` immediately, so queueing is invisible. Two spawns share a limit iff
    they reference the same `TaskGroup` value — there is no global registry.
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    _handle: _BamlPyHandle


__all__ = [
    "CancelToken",
    "SpawnParams",
    "TaskGroup",
]
