# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import typing
import pydantic

from baml_core import BamlPyHandle as _BamlPyHandle


class DirEntry(pydantic.BaseModel):
    name: typing.Optional[str]
    is_dir: typing.Optional[bool]
    is_file: typing.Optional[bool]
    is_symlink: typing.Optional[bool]


class File(pydantic.BaseModel):
    _handle: _BamlPyHandle


class MkdirOptions(pydantic.BaseModel):
    recursive: typing.Optional[bool]


__all__ = [
    "DirEntry",
    "File",
    "MkdirOptions",
]
