# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import typing
import pydantic

if typing.TYPE_CHECKING:
    from .. import baml
    from .. import stream_types
    from ..baml import UNSET as UNSET


def PerformTask(full_task_prompt: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> TaskExecutionResult:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
async def PerformTask_async(full_task_prompt: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> TaskExecutionResult:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
def PerformTask__build_request(full_task_prompt: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def PerformTask__build_request_async(full_task_prompt: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def PerformTask__build_request_stream(full_task_prompt: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def PerformTask__build_request_stream_async(full_task_prompt: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def PerformTask__parse(json: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> TaskExecutionResult:
    """Raises:
        LlmClient"""
async def PerformTask__parse_async(json: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> TaskExecutionResult:
    """Raises:
        LlmClient"""
def PerformTask__parse_stream(sse: baml.http.SseStream, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.task_execution.TaskExecutionResult], TaskExecutionResult]:
    """Raises:
        InvalidArgument, LlmClient"""
async def PerformTask__parse_stream_async(sse: baml.http.SseStream, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.task_execution.TaskExecutionResult], TaskExecutionResult]:
    """Raises:
        InvalidArgument, LlmClient"""
def PerformTask__render_prompt(full_task_prompt: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.PromptAst:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def PerformTask__render_prompt_async(full_task_prompt: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.PromptAst:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def PerformTask_stream(full_task_prompt: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.task_execution.TaskExecutionResult], TaskExecutionResult]:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
async def PerformTask_stream_async(full_task_prompt: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.task_execution.TaskExecutionResult], TaskExecutionResult]:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


class TaskReturnItem(pydantic.BaseModel):
    name: str
    payload: typing.Optional[typing.Dict[str, str]]


class TaskExecutionResult(pydantic.BaseModel):
    returns: typing.List[TaskReturnItem]


__all__ = [
    "PerformTask",
    "PerformTask_async",
    "PerformTask__build_request",
    "PerformTask__build_request_async",
    "PerformTask__build_request_stream",
    "PerformTask__build_request_stream_async",
    "PerformTask__parse",
    "PerformTask__parse_async",
    "PerformTask__parse_stream",
    "PerformTask__parse_stream_async",
    "PerformTask__render_prompt",
    "PerformTask__render_prompt_async",
    "PerformTask_stream",
    "PerformTask_stream_async",
    "TaskReturnItem",
    "TaskExecutionResult",
]
