from __future__ import annotations

import ast
from pathlib import Path
import re
import struct


_LOADER = """from __future__ import annotations

from pathlib import Path


BYTECODE: bytes = Path(__file__).with_name("_inlinedbaml.bin").read_bytes()
"""
_MARKER = b"baml_src"
_MAX_PREFIX_SEARCH = 2048


def normalize_generated_output(generated: Path) -> None:
    module = generated / "_inlinedbaml.py"
    bytecode = _load_bytecode_literal(module)
    normalized = normalize_borsh_source_paths(bytecode)
    (generated / "_inlinedbaml.bin").write_bytes(normalized)
    module.write_text(_LOADER, encoding="utf-8", newline="\n")
    normalize_generated_text_files(generated)


def normalize_borsh_source_paths(bytecode: bytes) -> bytes:
    source_paths = _source_paths(bytecode)
    symbol_prefixes = _symbol_prefixes(source_paths)
    replacements: dict[int, tuple[int, bytes]] = {}

    search_from = 0
    while (marker_at := bytecode.find(_MARKER, search_from)) >= 0:
        search_from = marker_at + len(_MARKER)
        match = _length_prefixed_string_containing(bytecode, marker_at)
        if match is None:
            continue
        prefix_at, end, value = match
        stable = _normalize_embedded_source(value, symbol_prefixes)
        if stable != value:
            replacements[prefix_at] = (end, stable.encode("utf-8"))

    output = _apply_replacements(bytecode, replacements)
    _reject_checkout_fragments(output, source_paths, symbol_prefixes)
    return output


def normalize_generated_text_files(generated: Path) -> None:
    for pattern in ("*.py", "*.pyi"):
        for path in generated.rglob(pattern):
            original = path.read_bytes()
            normalized = normalize_generated_text(original.decode("utf-8")).encode()
            if normalized != original:
                path.write_bytes(normalized)


def normalize_generated_text(text: str) -> str:
    had_final_newline = text.endswith(("\n", "\r"))
    lines = text.splitlines()
    normalized = "\n".join(line.rstrip(" \t") for line in lines)
    if had_final_newline:
        normalized += "\n"
    return normalized


def _load_bytecode_literal(module: Path) -> bytes:
    tree = ast.parse(module.read_text(encoding="utf-8"), filename=str(module))
    for node in ast.walk(tree):
        if (
            isinstance(node, ast.AnnAssign)
            and isinstance(node.target, ast.Name)
            and node.target.id == "BYTECODE"
        ):
            value = ast.literal_eval(node.value)
            if isinstance(value, bytes):
                return value
    raise ValueError(f"generated BYTECODE literal not found in {module}")


def _source_paths(bytecode: bytes) -> set[str]:
    paths: set[str] = set()
    search_from = 0
    while (marker_at := bytecode.find(_MARKER, search_from)) >= 0:
        search_from = marker_at + len(_MARKER)
        suffix_at = bytecode.find(b".baml", marker_at)
        if suffix_at < 0:
            continue
        match = _length_prefixed_string_ending(
            bytecode,
            marker_at,
            suffix_at + len(b".baml"),
        )
        if match is not None:
            paths.add(match[1])
    return paths


def _symbol_prefixes(source_paths: set[str]) -> set[str]:
    prefixes: set[str] = set()
    for source in source_paths:
        marker_at = source.find("baml_src")
        if marker_at < 0:
            continue
        root = source[:marker_at]
        if root.startswith(("\\\\?\\", "//?/")):
            variants = {root[4:]}
        else:
            variants = {root}
        for variant in variants:
            symbol = re.sub(r"[^A-Za-z0-9_]", "_", variant)
            if symbol:
                prefixes.add(symbol)
    return prefixes


def _normalize_embedded_source(value: str, symbol_prefixes: set[str]) -> str:
    if value.endswith(".baml"):
        normalized = value.replace("\\", "/")
        marker_at = normalized.find("baml_src/")
        if marker_at >= 0:
            return normalized[marker_at:]

    for prefix in sorted(symbol_prefixes, key=len, reverse=True):
        value = value.replace(f"{prefix}baml_src", "baml_src")
    return value


def _length_prefixed_string_ending(
    bytecode: bytes,
    marker_at: int,
    end: int,
) -> tuple[int, str] | None:
    for prefix_at in _candidate_prefixes(marker_at):
        length = struct.unpack_from("<I", bytecode, prefix_at)[0]
        start = prefix_at + 4
        if start + length != end or start > marker_at:
            continue
        value = _decode_string(bytecode, start, end)
        if value is not None and value.endswith(".baml"):
            return prefix_at, value
    return None


def _length_prefixed_string_containing(
    bytecode: bytes,
    marker_at: int,
) -> tuple[int, int, str] | None:
    for prefix_at in _candidate_prefixes(marker_at):
        length = struct.unpack_from("<I", bytecode, prefix_at)[0]
        start = prefix_at + 4
        end = start + length
        if start > marker_at or end <= marker_at or end > len(bytecode):
            continue
        value = _decode_string(bytecode, start, end)
        if value is not None and "baml_src" in value and value.isprintable():
            return prefix_at, end, value
    return None


def _candidate_prefixes(marker_at: int) -> range:
    lower_bound = max(0, marker_at - _MAX_PREFIX_SEARCH)
    return range(marker_at - 4, lower_bound - 1, -1)


def _decode_string(bytecode: bytes, start: int, end: int) -> str | None:
    try:
        return bytecode[start:end].decode("utf-8")
    except UnicodeDecodeError:
        return None


def _apply_replacements(
    bytecode: bytes,
    replacements: dict[int, tuple[int, bytes]],
) -> bytes:
    output = bytearray()
    cursor = 0
    for prefix_at, (end, stable) in sorted(replacements.items()):
        if prefix_at < cursor:
            continue
        output.extend(bytecode[cursor:prefix_at])
        output.extend(struct.pack("<I", len(stable)))
        output.extend(stable)
        cursor = end
    output.extend(bytecode[cursor:])
    return bytes(output)


def _reject_checkout_fragments(
    bytecode: bytes,
    source_paths: set[str],
    symbol_prefixes: set[str],
) -> None:
    fragments = symbol_prefixes | {
        source[: source.find("baml_src")]
        for source in source_paths
        if source.find("baml_src") > 0
    }
    remaining = [fragment for fragment in fragments if fragment.encode() in bytecode]
    if remaining:
        raise ValueError("checkout-specific BAML paths remain after normalization")
