# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import typing
import pydantic


class ModelReference(pydantic.BaseModel):
    model_id: str
    direct_baml_surface: str
    workspace_baml_surface: str
    reasoning_efforts: typing.List[str]


def StandardReasoningEfforts() -> typing.List[str]: ...
async def StandardReasoningEfforts_async() -> typing.List[str]: ...


def ModelInventory() -> typing.List[ModelReference]: ...
async def ModelInventory_async() -> typing.List[ModelReference]: ...


__all__ = [
    "ModelReference",
    "StandardReasoningEfforts",
    "StandardReasoningEfforts_async",
    "ModelInventory",
    "ModelInventory_async",
]
