# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import typing
import pydantic

if typing.TYPE_CHECKING:
    from .. import baml
    from .. import context
    from .. import stream_types
    from .. import task_routing

from baml_core import define_function as _define_function


ChooseMemorySearchDepths       = _define_function("user.memory_search.ChooseMemorySearchDepths", "sync",  ["current_timestamp", "current_user_request", "current_conversation", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories", "machine_state"], ["client"])
ChooseMemorySearchDepths.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
ChooseMemorySearchDepths_async = _define_function("user.memory_search.ChooseMemorySearchDepths", "async", ["current_timestamp", "current_user_request", "current_conversation", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories", "machine_state"], ["client"])
ChooseMemorySearchDepths_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
ChooseMemorySearchDepths__build_request       = _define_function("user.memory_search.ChooseMemorySearchDepths$build_request", "sync",  ["current_timestamp", "current_user_request", "current_conversation", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories", "machine_state"], ["client"])
ChooseMemorySearchDepths__build_request.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearchDepths__build_request_async = _define_function("user.memory_search.ChooseMemorySearchDepths$build_request", "async", ["current_timestamp", "current_user_request", "current_conversation", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories", "machine_state"], ["client"])
ChooseMemorySearchDepths__build_request_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearchDepths__build_request_stream       = _define_function("user.memory_search.ChooseMemorySearchDepths$build_request_stream", "sync",  ["current_timestamp", "current_user_request", "current_conversation", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories", "machine_state"], ["client"])
ChooseMemorySearchDepths__build_request_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearchDepths__build_request_stream_async = _define_function("user.memory_search.ChooseMemorySearchDepths$build_request_stream", "async", ["current_timestamp", "current_user_request", "current_conversation", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories", "machine_state"], ["client"])
ChooseMemorySearchDepths__build_request_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearchDepths__parse       = _define_function("user.memory_search.ChooseMemorySearchDepths$parse", "sync",  ["json"], ["client"])
ChooseMemorySearchDepths__parse.__doc__ = """Raises:
    LlmClient"""
ChooseMemorySearchDepths__parse_async = _define_function("user.memory_search.ChooseMemorySearchDepths$parse", "async", ["json"], ["client"])
ChooseMemorySearchDepths__parse_async.__doc__ = """Raises:
    LlmClient"""
ChooseMemorySearchDepths__parse_stream       = _define_function("user.memory_search.ChooseMemorySearchDepths$parse_stream", "sync",  ["sse"], ["client"])
ChooseMemorySearchDepths__parse_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
ChooseMemorySearchDepths__parse_stream_async = _define_function("user.memory_search.ChooseMemorySearchDepths$parse_stream", "async", ["sse"], ["client"])
ChooseMemorySearchDepths__parse_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
ChooseMemorySearchDepths__render_prompt       = _define_function("user.memory_search.ChooseMemorySearchDepths$render_prompt", "sync",  ["current_timestamp", "current_user_request", "current_conversation", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories", "machine_state"], ["client"])
ChooseMemorySearchDepths__render_prompt.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearchDepths__render_prompt_async = _define_function("user.memory_search.ChooseMemorySearchDepths$render_prompt", "async", ["current_timestamp", "current_user_request", "current_conversation", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories", "machine_state"], ["client"])
ChooseMemorySearchDepths__render_prompt_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearchDepths_stream       = _define_function("user.memory_search.ChooseMemorySearchDepths$stream", "sync",  ["current_timestamp", "current_user_request", "current_conversation", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories", "machine_state"], ["client"])
ChooseMemorySearchDepths_stream.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
ChooseMemorySearchDepths_stream_async = _define_function("user.memory_search.ChooseMemorySearchDepths$stream", "async", ["current_timestamp", "current_user_request", "current_conversation", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories", "machine_state"], ["client"])
ChooseMemorySearchDepths_stream_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


SearchDomains       = _define_function("user.memory_search.SearchDomains", "sync",  [])
SearchDomains_async = _define_function("user.memory_search.SearchDomains", "async", [])


ChooseMemorySearch       = _define_function("user.memory_search.ChooseMemorySearch", "sync",  ["current_user_request", "current_conversation", "session_memories", "selected_task", "conversation_evaluation_memories", "machine_state"], ["client"])
ChooseMemorySearch.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
ChooseMemorySearch_async = _define_function("user.memory_search.ChooseMemorySearch", "async", ["current_user_request", "current_conversation", "session_memories", "selected_task", "conversation_evaluation_memories", "machine_state"], ["client"])
ChooseMemorySearch_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
ChooseMemorySearch__build_request       = _define_function("user.memory_search.ChooseMemorySearch$build_request", "sync",  ["current_user_request", "current_conversation", "session_memories", "selected_task", "conversation_evaluation_memories", "machine_state"], ["client"])
ChooseMemorySearch__build_request.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearch__build_request_async = _define_function("user.memory_search.ChooseMemorySearch$build_request", "async", ["current_user_request", "current_conversation", "session_memories", "selected_task", "conversation_evaluation_memories", "machine_state"], ["client"])
ChooseMemorySearch__build_request_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearch__build_request_stream       = _define_function("user.memory_search.ChooseMemorySearch$build_request_stream", "sync",  ["current_user_request", "current_conversation", "session_memories", "selected_task", "conversation_evaluation_memories", "machine_state"], ["client"])
ChooseMemorySearch__build_request_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearch__build_request_stream_async = _define_function("user.memory_search.ChooseMemorySearch$build_request_stream", "async", ["current_user_request", "current_conversation", "session_memories", "selected_task", "conversation_evaluation_memories", "machine_state"], ["client"])
ChooseMemorySearch__build_request_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearch__parse       = _define_function("user.memory_search.ChooseMemorySearch$parse", "sync",  ["json"], ["client"])
ChooseMemorySearch__parse.__doc__ = """Raises:
    LlmClient"""
ChooseMemorySearch__parse_async = _define_function("user.memory_search.ChooseMemorySearch$parse", "async", ["json"], ["client"])
ChooseMemorySearch__parse_async.__doc__ = """Raises:
    LlmClient"""
ChooseMemorySearch__parse_stream       = _define_function("user.memory_search.ChooseMemorySearch$parse_stream", "sync",  ["sse"], ["client"])
ChooseMemorySearch__parse_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
ChooseMemorySearch__parse_stream_async = _define_function("user.memory_search.ChooseMemorySearch$parse_stream", "async", ["sse"], ["client"])
ChooseMemorySearch__parse_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
ChooseMemorySearch__render_prompt       = _define_function("user.memory_search.ChooseMemorySearch$render_prompt", "sync",  ["current_user_request", "current_conversation", "session_memories", "selected_task", "conversation_evaluation_memories", "machine_state"], ["client"])
ChooseMemorySearch__render_prompt.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearch__render_prompt_async = _define_function("user.memory_search.ChooseMemorySearch$render_prompt", "async", ["current_user_request", "current_conversation", "session_memories", "selected_task", "conversation_evaluation_memories", "machine_state"], ["client"])
ChooseMemorySearch__render_prompt_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearch_stream       = _define_function("user.memory_search.ChooseMemorySearch$stream", "sync",  ["current_user_request", "current_conversation", "session_memories", "selected_task", "conversation_evaluation_memories", "machine_state"], ["client"])
ChooseMemorySearch_stream.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
ChooseMemorySearch_stream_async = _define_function("user.memory_search.ChooseMemorySearch$stream", "async", ["current_user_request", "current_conversation", "session_memories", "selected_task", "conversation_evaluation_memories", "machine_state"], ["client"])
ChooseMemorySearch_stream_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


class ConversationEvaluationMemoryContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class SearchDepthMemoryContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class MemoryTagSearch(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    any_of: typing.List[str]
    all_of: typing.List[str]
    none_of: typing.List[str]


class MemoryStringSearch(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    contains: typing.List[str]
    equals: typing.List[str]


class CandidateMemory(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    title: str
    description: str


class SearchDepthDomain(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: str
    description: str
    searches: str
    hydrates: str


class SearchDepthTimestamps(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    created_after: str
    read_after: str
    updated_after: str


class ConversationMemorySearchHints(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    tags: MemoryTagSearch
    strings: MemoryStringSearch
    candidate_memory: typing.Optional[CandidateMemory]


class SearchDepthDecision(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    depths: typing.Dict[str, SearchDepthTimestamps]
    candidate_memory: typing.Optional[CandidateMemory]


__all__ = [
    "ChooseMemorySearchDepths",
    "ChooseMemorySearchDepths_async",
    "ChooseMemorySearchDepths__build_request",
    "ChooseMemorySearchDepths__build_request_async",
    "ChooseMemorySearchDepths__build_request_stream",
    "ChooseMemorySearchDepths__build_request_stream_async",
    "ChooseMemorySearchDepths__parse",
    "ChooseMemorySearchDepths__parse_async",
    "ChooseMemorySearchDepths__parse_stream",
    "ChooseMemorySearchDepths__parse_stream_async",
    "ChooseMemorySearchDepths__render_prompt",
    "ChooseMemorySearchDepths__render_prompt_async",
    "ChooseMemorySearchDepths_stream",
    "ChooseMemorySearchDepths_stream_async",
    "SearchDomains",
    "SearchDomains_async",
    "ChooseMemorySearch",
    "ChooseMemorySearch_async",
    "ChooseMemorySearch__build_request",
    "ChooseMemorySearch__build_request_async",
    "ChooseMemorySearch__build_request_stream",
    "ChooseMemorySearch__build_request_stream_async",
    "ChooseMemorySearch__parse",
    "ChooseMemorySearch__parse_async",
    "ChooseMemorySearch__parse_stream",
    "ChooseMemorySearch__parse_stream_async",
    "ChooseMemorySearch__render_prompt",
    "ChooseMemorySearch__render_prompt_async",
    "ChooseMemorySearch_stream",
    "ChooseMemorySearch_stream_async",
    "ConversationEvaluationMemoryContext",
    "SearchDepthMemoryContext",
    "MemoryTagSearch",
    "MemoryStringSearch",
    "CandidateMemory",
    "SearchDepthDomain",
    "SearchDepthTimestamps",
    "ConversationMemorySearchHints",
    "SearchDepthDecision",
]
