# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import typing
import pydantic

from baml_bridge import define_function as _define_function


E = typing.TypeVar("E")
T = typing.TypeVar("T")


call_host_value       = _define_function("baml.host.call_host_value", "sync",  ["handle", "args"], type_params=["T", "E"])
call_host_value_async = _define_function("baml.host.call_host_value", "async", ["handle", "args"], type_params=["T", "E"])


class HostValue(pydantic.BaseModel):
    """
    Opaque builtin class. Construction is reserved to the bridge
    boundary; users cannot construct or destructure it.
    """
    model_config = pydantic.ConfigDict(extra="forbid")


__all__ = [
    "call_host_value",
    "call_host_value_async",
    "HostValue",
]
