# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

_LAZY_CHILDREN = frozenset({
    "csv",
    "errors",
    "fs",
    "future",
    "glob",
    "host",
    "http",
    "iter",
    "json",
    "llm",
    "media",
    "net",
    "panics",
    "spawn",
    "stream",
    "sys",
    "time",
    "toml",
    "yaml",
})

def __getattr__(name):
    if name in _LAZY_CHILDREN:
        import importlib
        return importlib.import_module(f".{name}", __name__)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

import typing
import pydantic


K = typing.TypeVar("K")
T = typing.TypeVar("T")
V = typing.TypeVar("V")


class Bigint(pydantic.BaseModel):
    """
    Arbitrary-precision signed integer.
    
    # Bitwise on negatives
    
    `&`, `|`, `^` use two's-complement semantics — bigints are treated as if
    they had an infinite sign-extended bit string. So `(-1n) & 1n == 1n`,
    `(-1n) | 0n == -1n`, `(-1n) ^ 0n == -1n`. This matches JavaScript `BigInt`
    and Python `int`.
    
    # Panics
    
    Bigint operators and methods can raise the following unrecoverable
    panics. These are not declared via `throws` because they signal that
    the program tried to do something invalid (rather than a recoverable
    runtime condition):
    
    - `baml.panics.DivisionByZero` — `a / 0n` or `a % 0n`.
    - `baml.panics.NegativeBitShift` — `a << -1n` or `a >> -1n`. The shift
      count must be non-negative.
    - `baml.panics.AllocFailure` — the operand or result would require
      more than ~268M bits (`bigint`'s workspace cap). Sources:
        * `a * b`, `a << n`, `a.pow(n)` where the predicted result exceeds
          the cap.
        * `bigint.parse(s)` where `s` carries more decimal digits than the
          cap permits.
    """
    model_config = pydantic.ConfigDict(extra="forbid")


class Bool(pydantic.BaseModel):
    """A boolean value — either `true` or `false`."""
    model_config = pydantic.ConfigDict(extra="forbid")


class Array(pydantic.BaseModel, typing.Generic[T]):
    """An ordered, growable collection of elements of type T."""
    model_config = pydantic.ConfigDict(extra="forbid")


class Map(pydantic.BaseModel, typing.Generic[K, V]):
    """An unordered collection of key-value pairs."""
    model_config = pydantic.ConfigDict(extra="forbid")


class TaggedString(pydantic.BaseModel):
    """
    The structured value a tagged template literal produces.
    
    BEP-049 §10. A `tag` ` `…` ` call site lowers to `tag(body = () -> TaggedString { … })`;
    when `body()` runs it returns this struct. The invariant is
    `parts.length == values.length + 1` (literals and values alternate, starting and
    ending with a literal — empty strings fill the leading/trailing slot when the
    template begins or ends with an interpolation).

    Attributes:
        parts: Literal text segments between interpolations, in source order.
        values: Interpolated values, in source order. Heterogeneous: each entry has the
            type of its `${expr}` site; tags inspect element types at runtime.
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    parts: typing.List[str]
    values: typing.List[typing.Any]


class Float(pydantic.BaseModel):
    """
    A 64-bit IEEE 754 floating-point number (f64).
    
    Note: division by zero (`x / 0.0`) does not follow raw IEEE — it throws a
    catchable `baml.panics.DivisionByZero` rather than yielding `±inf`/`NaN`,
    matching integer division. `inf` and `NaN` still arise from `float.inf()` /
    `float.nan()`, from overflow (e.g. `1e308 * 10.0` → `inf`), and from other
    invalid operations (e.g. `(-1.0).sqrt()` → `NaN`).
    """
    model_config = pydantic.ConfigDict(extra="forbid")


class Int(pydantic.BaseModel):
    """
    A 63-bit signed integer. Range: -2^62 to 2^62-1
    (`-4_611_686_018_427_387_904` to `4_611_686_018_427_387_903`).
    
    The value is stored in a 64-bit machine word with one bit reserved for the
    runtime's pointer/value tag, so the usable range is 63-bit, not 64-bit. Use
    `bigint` for arbitrary-precision integers.
    
    Arithmetic (`+`, `-`, `*`, `/`, unary `-`) that would leave this range
    throws a catchable `baml.panics.IntegerOverflow` rather than wrapping or
    crashing; `/` and `%` by zero throw `baml.panics.DivisionByZero`.
    """
    model_config = pydantic.ConfigDict(extra="forbid")


class Null(pydantic.BaseModel):
    """The null type, representing the absence of a value."""
    model_config = pydantic.ConfigDict(extra="forbid")


class String(pydantic.BaseModel):
    """
    A UTF-8 encoded string.
    
    String literals use double quotes: `"hello"`. Multiline strings use the `#"..."#` syntax.
    All methods returning a new string do not mutate `self` unless noted otherwise.
    """
    model_config = pydantic.ConfigDict(extra="forbid")


class TypeValue(pydantic.BaseModel):
    """
    Companion class for the built-in `type` primitive.
    
    The BAML `type` primitive represents a runtime type value returned by
    `reflect.type_of<T>()`. This class provides methods on `type` values,
    mirroring how `class String` provides methods on `string`.
    
    Users never construct `Type` directly; they receive `type` values via
    `reflect.type_of<User>()` and call methods on them.
    """
    model_config = pydantic.ConfigDict(extra="forbid")


class Uint8Array(pydantic.BaseModel):
    """
    A mutable, growable array of bytes (u8 values in the range 0–255).
    
    Used for binary data such as file contents, network payloads, and encoded strings.
    `push` silently masks values to u8; `from_array` throws `InvalidArgument` for out-of-range values.
    """
    model_config = pydantic.ConfigDict(extra="forbid")


__all__ = [
    "Bigint",
    "Bool",
    "Array",
    "Map",
    "TaggedString",
    "Float",
    "Int",
    "Null",
    "String",
    "TypeValue",
    "Uint8Array",
]
