# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

_LAZY_CHILDREN = frozenset({
    "postgres",
    "sqlite",
})

def __getattr__(name):
    if name in _LAZY_CHILDREN:
        import importlib
        return importlib.import_module(f".{name}", __name__)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

import enum
import typing
import pydantic

from ... import baml

from baml_bridge import (
    BamlPyHandle as _BamlPyHandle,
    define_function as _define_function,
)


E = typing.TypeVar("E")
T = typing.TypeVar("T")


class SqlIsolation(str, enum.Enum):
    ReadCommitted = "ReadCommitted"
    RepeatableRead = "RepeatableRead"
    Serializable = "Serializable"


class SqlErrorKind(str, enum.Enum):
    Connection = "Connection"
    Closed = "Closed"
    Timeout = "Timeout"
    Syntax = "Syntax"
    Constraint = "Constraint"
    NotFound = "NotFound"
    TooManyRows = "TooManyRows"
    Decode = "Decode"
    Unsupported = "Unsupported"
    Database = "Database"


class SqlError(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    kind: SqlErrorKind
    message: str
    code: typing.Optional[str]
    constraint: typing.Optional[str]
    table: typing.Optional[str]
    column: typing.Optional[str]


class ConnectOptions(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    max_connections: typing.Optional[int]
    connect_timeout: typing.Optional[baml.time.Duration]
    query_timeout: typing.Optional[baml.time.Duration]
    validate: typing.Optional[bool]


class QueryOptions(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    timeout: typing.Optional[baml.time.Duration]


class TransactionOptions(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    isolation: typing.Optional[SqlIsolation]
    read_only: typing.Optional[bool]


class CommandResult(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    rows_affected: int


class JsonValue(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    value: baml.json.json


json       = _define_function("baml.sql.json", "sync",  ["value"])
json_async = _define_function("baml.sql.json", "async", ["value"])


class Statement(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    _handle: _BamlPyHandle


statement       = _define_function("baml.sql.statement", "sync",  ["body"])
statement.__doc__ = """Raises:
    SqlError"""
statement_async = _define_function("baml.sql.statement", "async", ["body"])
statement_async.__doc__ = """Raises:
    SqlError"""


_statement       = _define_function("baml.sql._statement", "sync",  ["parts", "values"])
_statement.__doc__ = """Raises:
    SqlError"""
_statement_async = _define_function("baml.sql._statement", "async", ["parts", "values"])
_statement_async.__doc__ = """Raises:
    SqlError"""


_duration_nanos       = _define_function("baml.sql._duration_nanos", "sync",  ["value"])
_duration_nanos_async = _define_function("baml.sql._duration_nanos", "async", ["value"])


class Database(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    _handle: _BamlPyHandle
    close       = _define_function("baml.sql.Database.close", "sync",  ["self"])
    close_async = _define_function("baml.sql.Database.close", "async", ["self"])
    _close       = _define_function("baml.sql.Database._close", "sync",  ["self"])
    _close_async = _define_function("baml.sql.Database._close", "async", ["self"])
    execute       = _define_function("baml.sql.Database.execute", "sync",  ["self", "statement"], ["options"])
    execute_async = _define_function("baml.sql.Database.execute", "async", ["self", "statement"], ["options"])
    _execute       = _define_function("baml.sql.Database._execute", "sync",  ["self", "statement", "timeout_nanos"])
    _execute_async = _define_function("baml.sql.Database._execute", "async", ["self", "statement", "timeout_nanos"])
    query       = _define_function("baml.sql.Database.query", "sync",  ["self", "statement"], ["options"], type_params=["T"])
    query_async = _define_function("baml.sql.Database.query", "async", ["self", "statement"], ["options"], type_params=["T"])
    query_optional       = _define_function("baml.sql.Database.query_optional", "sync",  ["self", "statement"], ["options"], type_params=["T"])
    query_optional_async = _define_function("baml.sql.Database.query_optional", "async", ["self", "statement"], ["options"], type_params=["T"])
    query_one       = _define_function("baml.sql.Database.query_one", "sync",  ["self", "statement"], ["options"], type_params=["T"])
    query_one_async = _define_function("baml.sql.Database.query_one", "async", ["self", "statement"], ["options"], type_params=["T"])
    scalar       = _define_function("baml.sql.Database.scalar", "sync",  ["self", "statement"], ["options"], type_params=["T"])
    scalar_async = _define_function("baml.sql.Database.scalar", "async", ["self", "statement"], ["options"], type_params=["T"])
    _query       = _define_function("baml.sql.Database._query", "sync",  ["self", "statement", "timeout_nanos", "row_limit"], type_params=["T"])
    _query_async = _define_function("baml.sql.Database._query", "async", ["self", "statement", "timeout_nanos", "row_limit"], type_params=["T"])
    _scalar       = _define_function("baml.sql.Database._scalar", "sync",  ["self", "statement", "timeout_nanos", "row_limit"], type_params=["T"])
    _scalar_async = _define_function("baml.sql.Database._scalar", "async", ["self", "statement", "timeout_nanos", "row_limit"], type_params=["T"])
    transaction       = _define_function("baml.sql.Database.transaction", "sync",  ["self", "body"], ["options"], type_params=["T", "E"])
    transaction_async = _define_function("baml.sql.Database.transaction", "async", ["self", "body"], ["options"], type_params=["T", "E"])
    _begin       = _define_function("baml.sql.Database._begin", "sync",  ["self", "options"])
    _begin_async = _define_function("baml.sql.Database._begin", "async", ["self", "options"])


class Transaction(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    _handle: _BamlPyHandle
    execute       = _define_function("baml.sql.Transaction.execute", "sync",  ["self", "statement"], ["options"])
    execute_async = _define_function("baml.sql.Transaction.execute", "async", ["self", "statement"], ["options"])
    _execute       = _define_function("baml.sql.Transaction._execute", "sync",  ["self", "statement", "timeout_nanos"])
    _execute_async = _define_function("baml.sql.Transaction._execute", "async", ["self", "statement", "timeout_nanos"])
    query       = _define_function("baml.sql.Transaction.query", "sync",  ["self", "statement"], ["options"], type_params=["T"])
    query_async = _define_function("baml.sql.Transaction.query", "async", ["self", "statement"], ["options"], type_params=["T"])
    query_optional       = _define_function("baml.sql.Transaction.query_optional", "sync",  ["self", "statement"], ["options"], type_params=["T"])
    query_optional_async = _define_function("baml.sql.Transaction.query_optional", "async", ["self", "statement"], ["options"], type_params=["T"])
    query_one       = _define_function("baml.sql.Transaction.query_one", "sync",  ["self", "statement"], ["options"], type_params=["T"])
    query_one_async = _define_function("baml.sql.Transaction.query_one", "async", ["self", "statement"], ["options"], type_params=["T"])
    scalar       = _define_function("baml.sql.Transaction.scalar", "sync",  ["self", "statement"], ["options"], type_params=["T"])
    scalar_async = _define_function("baml.sql.Transaction.scalar", "async", ["self", "statement"], ["options"], type_params=["T"])
    _query       = _define_function("baml.sql.Transaction._query", "sync",  ["self", "statement", "timeout_nanos", "row_limit"], type_params=["T"])
    _query_async = _define_function("baml.sql.Transaction._query", "async", ["self", "statement", "timeout_nanos", "row_limit"], type_params=["T"])
    _scalar       = _define_function("baml.sql.Transaction._scalar", "sync",  ["self", "statement", "timeout_nanos", "row_limit"], type_params=["T"])
    _scalar_async = _define_function("baml.sql.Transaction._scalar", "async", ["self", "statement", "timeout_nanos", "row_limit"], type_params=["T"])
    _commit       = _define_function("baml.sql.Transaction._commit", "sync",  ["self"])
    _commit_async = _define_function("baml.sql.Transaction._commit", "async", ["self"])
    _rollback_if_open       = _define_function("baml.sql.Transaction._rollback_if_open", "sync",  ["self"])
    _rollback_if_open_async = _define_function("baml.sql.Transaction._rollback_if_open", "async", ["self"])


_query_timeout       = _define_function("baml.sql._query_timeout", "sync",  ["options"])
_query_timeout_async = _define_function("baml.sql._query_timeout", "async", ["options"])


connect       = _define_function("baml.sql.connect", "sync",  ["url"], ["options"])
connect.__doc__ = """Raises:
    SqlError"""
connect_async = _define_function("baml.sql.connect", "async", ["url"], ["options"])
connect_async.__doc__ = """Raises:
    SqlError"""


_connect       = _define_function("baml.sql._connect", "sync",  ["url", "options"])
_connect.__doc__ = """Raises:
    SqlError, Unsupported"""
_connect_async = _define_function("baml.sql._connect", "async", ["url", "options"])
_connect_async.__doc__ = """Raises:
    SqlError, Unsupported"""


__all__ = [
    "SqlIsolation",
    "SqlErrorKind",
    "SqlError",
    "ConnectOptions",
    "QueryOptions",
    "TransactionOptions",
    "CommandResult",
    "JsonValue",
    "json",
    "json_async",
    "Statement",
    "statement",
    "statement_async",
    "Database",
    "Transaction",
    "connect",
    "connect_async",
]
