# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import typing
import pydantic


class CoreTaskDefinition(pydantic.BaseModel):
    name: typing.Optional[str]
    description: typing.Optional[str]
    input: typing.Optional[str]
    output: typing.Optional[str]
    prompt: typing.Optional[str]
    tags: typing.List[str]
    model_id: typing.Optional[str]
    reasoning_effort: typing.Optional[str]


__all__ = [
    "CoreTaskDefinition",
]
