# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import typing
import pydantic

if typing.TYPE_CHECKING:
    from ... import baml

from baml_bridge import (
    BamlPyHandle as _BamlPyHandle,
    define_function as _define_function,
)


class Request(pydantic.BaseModel):
    """
    An HTTP request — outgoing (built for `baml.http.send`/`fetch_sse`) or
    incoming (passed to an `http.Server` handler).
    
    For an incoming server request: `url` is the request-target as received
    (origin-form, e.g. `/path?q=1`, on HTTP/1; the authority lives in the `host`
    header), `body` is the bytes decoded lossily as UTF-8 (non-UTF-8 bytes become
    U+FFFD), and a header sent multiple times has its values joined with `, `.
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    method: str
    url: str
    headers: typing.Dict[str, str]
    body: str


class Response(pydantic.BaseModel):
    """An HTTP response returned by `baml.http.fetch` or `baml.http.send`."""
    model_config = pydantic.ConfigDict(extra="forbid")
    status_code: int
    headers: typing.Dict[str, str]
    url: str
    _body: _BamlPyHandle
    new       = staticmethod(_define_function("baml.http.Response.new", "sync",  ["status_code", "headers", "body"]))
    new_async = staticmethod(_define_function("baml.http.Response.new", "async", ["status_code", "headers", "body"]))
    new_streaming       = staticmethod(_define_function("baml.http.Response.new_streaming", "sync",  ["status_code", "headers"]))
    new_streaming_async = staticmethod(_define_function("baml.http.Response.new_streaming", "async", ["status_code", "headers"]))
    text       = _define_function("baml.http.Response.text", "sync",  ["self"])
    text_async = _define_function("baml.http.Response.text", "async", ["self"])
    bytes       = _define_function("baml.http.Response.bytes", "sync",  ["self"])
    bytes_async = _define_function("baml.http.Response.bytes", "async", ["self"])
    ok       = _define_function("baml.http.Response.ok", "sync",  ["self"])
    ok_async = _define_function("baml.http.Response.ok", "async", ["self"])
    write       = _define_function("baml.http.Response.write", "sync",  ["self", "data"])
    write_async = _define_function("baml.http.Response.write", "async", ["self", "data"])
    end       = _define_function("baml.http.Response.end", "sync",  ["self"])
    end_async = _define_function("baml.http.Response.end", "async", ["self"])


class SseStream(pydantic.BaseModel):
    """A Server-Sent Events (SSE) stream. Created by `baml.http.fetch_sse`."""
    model_config = pydantic.ConfigDict(extra="forbid")
    url: str
    _handle: _BamlPyHandle
    next       = _define_function("baml.http.SseStream.next", "sync",  ["self"])
    next_async = _define_function("baml.http.SseStream.next", "async", ["self"])
    close       = _define_function("baml.http.SseStream.close", "sync",  ["self"])
    close_async = _define_function("baml.http.SseStream.close", "async", ["self"])


_timeout_nanos       = _define_function("baml.http._timeout_nanos", "sync",  ["timeout"])
_timeout_nanos_async = _define_function("baml.http._timeout_nanos", "async", ["timeout"])


fetch       = _define_function("baml.http.fetch", "sync",  ["url"], ["timeout"])
fetch.__doc__ = """Sends a GET request to `url` and returns the response.

`timeout` is the total deadline for the request (connection + response
headers + body). `null` (the default) imposes no deadline. On expiry this
throws `root.errors.Timeout`.

Raises:
    Io, Timeout"""
fetch_async = _define_function("baml.http.fetch", "async", ["url"], ["timeout"])
fetch_async.__doc__ = """Sends a GET request to `url` and returns the response.

`timeout` is the total deadline for the request (connection + response
headers + body). `null` (the default) imposes no deadline. On expiry this
throws `root.errors.Timeout`.

Raises:
    Io, Timeout"""


_fetch       = _define_function("baml.http._fetch", "sync",  ["url", "timeout_nanos"])
_fetch.__doc__ = """Raises:
    Io, Timeout"""
_fetch_async = _define_function("baml.http._fetch", "async", ["url", "timeout_nanos"])
_fetch_async.__doc__ = """Raises:
    Io, Timeout"""


send       = _define_function("baml.http.send", "sync",  ["request"], ["timeout"])
send.__doc__ = """Sends an HTTP request and returns the response.

`timeout` is the total deadline for the request, as in `fetch`. `null` (the
default) imposes no deadline.

Raises:
    Io, Timeout"""
send_async = _define_function("baml.http.send", "async", ["request"], ["timeout"])
send_async.__doc__ = """Sends an HTTP request and returns the response.

`timeout` is the total deadline for the request, as in `fetch`. `null` (the
default) imposes no deadline.

Raises:
    Io, Timeout"""


_send       = _define_function("baml.http._send", "sync",  ["request", "timeout_nanos"])
_send.__doc__ = """Raises:
    Io, Timeout"""
_send_async = _define_function("baml.http._send", "async", ["request", "timeout_nanos"])
_send_async.__doc__ = """Raises:
    Io, Timeout"""


fetch_sse       = _define_function("baml.http.fetch_sse", "sync",  ["request"])
fetch_sse.__doc__ = """Sends an HTTP request and returns a Server-Sent Events stream for streaming responses.

Raises:
    Io, Timeout"""
fetch_sse_async = _define_function("baml.http.fetch_sse", "async", ["request"])
fetch_sse_async.__doc__ = """Sends an HTTP request and returns a Server-Sent Events stream for streaming responses.

Raises:
    Io, Timeout"""


class Server(pydantic.BaseModel):
    """
    A minimal HTTP/HTTPS server.
    
    Bind a listening socket with `Server.bind`, then call `serve` with a request
    handler to start serving:
    ```baml
    let server = baml.http.Server.bind("127.0.0.1:0");
    spawn { server.serve((req) -> { baml.http.Response.new(200, { }, "hi".to_utf8()) }) };
    // server.addr now holds the actual bound address, e.g. "127.0.0.1:54321".
    ```

    Attributes:
        addr: The resolved local address the listener is bound to, e.g.
            `"127.0.0.1:54321"`. Use it to discover the port after binding `":0"`.
        _state
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    addr: str
    _state: _BamlPyHandle
    bind       = staticmethod(_define_function("baml.http.Server.bind", "sync",  ["addr"]))
    bind_async = staticmethod(_define_function("baml.http.Server.bind", "async", ["addr"]))
    serve       = _define_function("baml.http.Server.serve", "sync",  ["self", "handler"], ["tls_config", "allow_http1", "allow_http2", "max_body_size", "max_connections", "header_read_timeout"])
    serve_async = _define_function("baml.http.Server.serve", "async", ["self", "handler"], ["tls_config", "allow_http1", "allow_http2", "max_body_size", "max_connections", "header_read_timeout"])
    _serve       = _define_function("baml.http.Server._serve", "sync",  ["self", "handler", "tls_config", "allow_http1", "allow_http2", "max_body_size", "max_connections", "header_read_timeout_nanos"])
    _serve_async = _define_function("baml.http.Server._serve", "async", ["self", "handler", "tls_config", "allow_http1", "allow_http2", "max_body_size", "max_connections", "header_read_timeout_nanos"])


class TlsConfig(pydantic.BaseModel):
    """
    Used to convert an HTTP server into an HTTPS server for secure connections.
    
    To force HTTP clients onto HTTPS, run two servers — a plaintext one on the
    HTTP port whose handler redirects, and the TLS one on the HTTPS port:
    ```baml
    let secure = http.Server.bind("0.0.0.0:443");
    let upgrade = http.Server.bind("0.0.0.0:80");
    spawn { upgrade.serve((req) -> {
        baml.http.Response.new(308, { "Location": "https://" + req.headers.get("host") + req.url }, "".to_utf8())
    }) };
    spawn { secure.serve(my_handler, tls_config = my_tls) };
    ```

    Attributes:
        allow_tls1_2: Whether to allow connections using TLSv1.2.
            This is enabled by default, but may be disabled to require TLSv1.3.
            
            BAML's standard HTTPS server does not provide TLS/SSL versions lower than TLSv1.2 as they are insecure.
        _certificate
        _private_key
        _handshake_timeout_nanos
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    allow_tls1_2: bool
    _certificate: _BamlPyHandle
    _private_key: _BamlPyHandle
    _handshake_timeout_nanos: int
    new       = staticmethod(_define_function("baml.http.TlsConfig.new", "sync",  ["cert_pem", "key_pem"], ["allow_tls1_2", "handshake_timeout"]))
    new_async = staticmethod(_define_function("baml.http.TlsConfig.new", "async", ["cert_pem", "key_pem"], ["allow_tls1_2", "handshake_timeout"]))
    _new       = staticmethod(_define_function("baml.http.TlsConfig._new", "sync",  ["cert_pem", "key_pem", "allow_tls1_2", "handshake_timeout_nanos"]))
    _new_async = staticmethod(_define_function("baml.http.TlsConfig._new", "async", ["cert_pem", "key_pem", "allow_tls1_2", "handshake_timeout_nanos"]))


__all__ = [
    "Request",
    "Response",
    "SseStream",
    "fetch",
    "fetch_async",
    "send",
    "send_async",
    "fetch_sse",
    "fetch_sse_async",
    "Server",
    "TlsConfig",
]
