# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import typing

if typing.TYPE_CHECKING:
    from .. import baml
    from .. import context
    from ..baml import UNSET as UNSET


def SummariseActionHistory(current_conversation: typing.Optional[context.ConversationHistory], recorded_action_history: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> str:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
async def SummariseActionHistory_async(current_conversation: typing.Optional[context.ConversationHistory], recorded_action_history: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> str:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
def SummariseActionHistory__build_request(current_conversation: typing.Optional[context.ConversationHistory], recorded_action_history: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def SummariseActionHistory__build_request_async(current_conversation: typing.Optional[context.ConversationHistory], recorded_action_history: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def SummariseActionHistory__build_request_stream(current_conversation: typing.Optional[context.ConversationHistory], recorded_action_history: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def SummariseActionHistory__build_request_stream_async(current_conversation: typing.Optional[context.ConversationHistory], recorded_action_history: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def SummariseActionHistory__parse(json: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> str:
    """Raises:
        LlmClient"""
async def SummariseActionHistory__parse_async(json: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> str:
    """Raises:
        LlmClient"""
def SummariseActionHistory__parse_stream(sse: baml.http.SseStream, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[str], str]:
    """Raises:
        InvalidArgument, LlmClient"""
async def SummariseActionHistory__parse_stream_async(sse: baml.http.SseStream, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[str], str]:
    """Raises:
        InvalidArgument, LlmClient"""
def SummariseActionHistory__render_prompt(current_conversation: typing.Optional[context.ConversationHistory], recorded_action_history: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.PromptAst:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def SummariseActionHistory__render_prompt_async(current_conversation: typing.Optional[context.ConversationHistory], recorded_action_history: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.PromptAst:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def SummariseActionHistory_stream(current_conversation: typing.Optional[context.ConversationHistory], recorded_action_history: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[str], str]:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
async def SummariseActionHistory_stream_async(current_conversation: typing.Optional[context.ConversationHistory], recorded_action_history: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[str], str]:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


__all__ = [
    "SummariseActionHistory",
    "SummariseActionHistory_async",
    "SummariseActionHistory__build_request",
    "SummariseActionHistory__build_request_async",
    "SummariseActionHistory__build_request_stream",
    "SummariseActionHistory__build_request_stream_async",
    "SummariseActionHistory__parse",
    "SummariseActionHistory__parse_async",
    "SummariseActionHistory__parse_stream",
    "SummariseActionHistory__parse_stream_async",
    "SummariseActionHistory__render_prompt",
    "SummariseActionHistory__render_prompt_async",
    "SummariseActionHistory_stream",
    "SummariseActionHistory_stream_async",
]
