# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import typing
import pydantic

from baml_core import (
    BamlPyHandle as _BamlPyHandle,
    define_function as _define_function,
)


class ErrorContext(pydantic.BaseModel):
    """
    The temporal context of a thrown error: the error value itself, where it
    was thrown, and the error it superseded while the scope was unwinding (its
    `cause`), if any. Bound by the second parameter of a `catch (e, ctx)`
    handler.
    
    The chain runs newest → oldest through `cause`; `root_cause` walks to the
    original failure at the tail, and `to_string` renders the whole chain
    Python-style ("During handling of the above error, another error occurred").
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    error: typing.Any
    stack_trace: StackTrace
    cause: typing.Optional[ErrorContext]
    root_cause       = _define_function("baml.errors.ErrorContext.root_cause", "sync",  ["self"])
    root_cause_async = _define_function("baml.errors.ErrorContext.root_cause", "async", ["self"])
    to_string       = _define_function("baml.errors.ErrorContext.to_string", "sync",  ["self"])
    to_string_async = _define_function("baml.errors.ErrorContext.to_string", "async", ["self"])
    _to_string_impl       = _define_function("baml.errors.ErrorContext._to_string_impl", "sync",  ["self"])
    _to_string_impl_async = _define_function("baml.errors.ErrorContext._to_string_impl", "async", ["self"])


class InvalidArgument(pydantic.BaseModel):
    """An argument is out of range or otherwise invalid."""
    model_config = pydantic.ConfigDict(extra="forbid")
    message: str


class ParseError(pydantic.BaseModel):
    """
    Thrown when text cannot be parsed into the requested type — e.g.
    `int.parse("abc")` or `float.parse("")`.
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    message: str


class Io(pydantic.BaseModel):
    """An I/O operation failed (file, network, etc.)."""
    model_config = pydantic.ConfigDict(extra="forbid")
    message: str


class Timeout(pydantic.BaseModel):
    """An operation exceeded its time limit."""
    model_config = pydantic.ConfigDict(extra="forbid")
    message: str
    duration_ms: typing.Optional[int]


class Unsupported(pydantic.BaseModel):
    """The requested operation is not supported in this context."""
    model_config = pydantic.ConfigDict(extra="forbid")
    message: str


class AccessError(pydantic.BaseModel):
    """Access to a resource was denied."""
    model_config = pydantic.ConfigDict(extra="forbid")
    message: str


class RenderPrompt(pydantic.BaseModel):
    """A prompt template could not be rendered."""
    model_config = pydantic.ConfigDict(extra="forbid")
    message: str


class NotImplemented(pydantic.BaseModel):
    """The operation has not been implemented."""
    model_config = pydantic.ConfigDict(extra="forbid")
    message: str


class LlmClient(pydantic.BaseModel):
    """An LLM client request failed."""
    model_config = pydantic.ConfigDict(extra="forbid")
    message: str


class DevOther(pydantic.BaseModel):
    """A catch-all error for development-time issues."""
    model_config = pydantic.ConfigDict(extra="forbid")
    message: str


class HostCallable(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    message: str
    class_name: str
    language: str
    traceback: typing.Optional[str]
    _handle: _BamlPyHandle


class GenericSdkError(pydantic.BaseModel):
    """
    A catch-all SDK-boundary failure with no more specific class. Synthesized
    host-side from `RuntimeError::Other` so a call-setup failure crosses the
    boundary as structured data rather than a stringified error.
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    message: str


class CompilationError(pydantic.BaseModel):
    """
    A BAML compilation failure surfaced at the call boundary. Synthesized
    host-side from `RuntimeError::Compilation`.
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    message: str


class TypeMismatch(pydantic.BaseModel):
    """
    A value/type mismatch at the call boundary — a caller passed an argument
    that doesn't fit the callee's (possibly inferred) type, a generic `TypeVar`
    could not be inferred and must be specified, or repeat occurrences of a
    `TypeVar` have no consistent binding. Synthesized host-side from
    `EngineError::TypeMismatch`; each host SDK surfaces it as its native
    type-error (Python `TypeError`).
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    message: str


class StackFrame(pydantic.BaseModel):
    """A single frame in a call stack, identifying a source location."""
    model_config = pydantic.ConfigDict(extra="forbid")
    file: str
    line: int
    function_name: str


class StackTrace(pydantic.BaseModel):
    """A captured call stack, consisting of one or more `StackFrame` entries."""
    model_config = pydantic.ConfigDict(extra="forbid")
    frames: typing.List[StackFrame]
    to_string       = _define_function("baml.errors.StackTrace.to_string", "sync",  ["self"])
    to_string_async = _define_function("baml.errors.StackTrace.to_string", "async", ["self"])
    _to_string_impl       = _define_function("baml.errors.StackTrace._to_string_impl", "sync",  ["self"])
    _to_string_impl_async = _define_function("baml.errors.StackTrace._to_string_impl", "async", ["self"])


__all__ = [
    "ErrorContext",
    "InvalidArgument",
    "ParseError",
    "Io",
    "Timeout",
    "Unsupported",
    "AccessError",
    "RenderPrompt",
    "NotImplemented",
    "LlmClient",
    "DevOther",
    "HostCallable",
    "GenericSdkError",
    "CompilationError",
    "TypeMismatch",
    "StackFrame",
    "StackTrace",
]
