# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import typing
import pydantic

from baml_core import BamlPyHandle as _BamlPyHandle


class ErrorContext(pydantic.BaseModel):
    error: typing.Any
    stack_trace: StackTrace
    cause: typing.Optional[ErrorContext]
    def root_cause(self) -> ErrorContext:
        """The original error at the tail of the cause chain — walks `cause` to the
        deepest link. Returns `self` when nothing was superseded."""
    async def root_cause_async(self) -> ErrorContext:
        """The original error at the tail of the cause chain — walks `cause` to the
        deepest link. Returns `self` when nothing was superseded."""
    def to_string(self) -> str: ...
    async def to_string_async(self) -> str: ...
    def _to_string_impl(self) -> str: ...
    async def _to_string_impl_async(self) -> str: ...


class InvalidArgument(pydantic.BaseModel):
    message: str


class ParseError(pydantic.BaseModel):
    message: str


class Io(pydantic.BaseModel):
    message: str


class Timeout(pydantic.BaseModel):
    message: str
    duration_ms: typing.Optional[int]


class Unsupported(pydantic.BaseModel):
    message: str


class AccessError(pydantic.BaseModel):
    message: str


class RenderPrompt(pydantic.BaseModel):
    message: str


class NotImplemented(pydantic.BaseModel):
    message: str


class LlmClient(pydantic.BaseModel):
    message: str


class DevOther(pydantic.BaseModel):
    message: str


class HostCallable(pydantic.BaseModel):
    message: str
    class_name: str
    language: str
    traceback: typing.Optional[str]
    _handle: _BamlPyHandle


class GenericSdkError(pydantic.BaseModel):
    message: str


class CompilationError(pydantic.BaseModel):
    message: str


class TypeMismatch(pydantic.BaseModel):
    message: str


class StackFrame(pydantic.BaseModel):
    file: str
    line: int
    function_name: str


class StackTrace(pydantic.BaseModel):
    frames: typing.List[StackFrame]
    def to_string(self) -> str: ...
    async def to_string_async(self) -> str: ...
    def _to_string_impl(self) -> str: ...
    async def _to_string_impl_async(self) -> str: ...


__all__ = [
    "ErrorContext",
    "InvalidArgument",
    "ParseError",
    "Io",
    "Timeout",
    "Unsupported",
    "AccessError",
    "RenderPrompt",
    "NotImplemented",
    "LlmClient",
    "DevOther",
    "HostCallable",
    "GenericSdkError",
    "CompilationError",
    "TypeMismatch",
    "StackFrame",
    "StackTrace",
]
