client<llm> OpenCodeGoModelKimiK27CodeReasoningNone {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "kimi-k2.7-code"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "none"
  }
}

client<llm> OpenCodeGoModelKimiK27CodeReasoningMinimal {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "kimi-k2.7-code"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "minimal"
  }
}

client<llm> OpenCodeGoModelKimiK27CodeReasoningLow {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "kimi-k2.7-code"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "low"
  }
}

client<llm> OpenCodeGoModelKimiK27CodeReasoningMedium {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "kimi-k2.7-code"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "medium"
  }
}

client<llm> OpenCodeGoModelKimiK27CodeReasoningHigh {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "kimi-k2.7-code"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "high"
  }
}

client<llm> OpenCodeGoModelKimiK27CodeReasoningXhigh {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "kimi-k2.7-code"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "xhigh"
  }
}

client<llm> OpenCodeGoModelKimiK26ReasoningNone {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "kimi-k2.6"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "none"
  }
}

client<llm> OpenCodeGoModelKimiK26ReasoningMinimal {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "kimi-k2.6"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "minimal"
  }
}

client<llm> OpenCodeGoModelKimiK26ReasoningLow {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "kimi-k2.6"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "low"
  }
}

client<llm> OpenCodeGoModelKimiK26ReasoningMedium {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "kimi-k2.6"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "medium"
  }
}

client<llm> OpenCodeGoModelKimiK26ReasoningHigh {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "kimi-k2.6"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "high"
  }
}

client<llm> OpenCodeGoModelKimiK26ReasoningXhigh {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "kimi-k2.6"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "xhigh"
  }
}

client<llm> OpenCodeGoModelKimiK25ReasoningNone {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "kimi-k2.5"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "none"
  }
}

client<llm> OpenCodeGoModelKimiK25ReasoningMinimal {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "kimi-k2.5"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "minimal"
  }
}

client<llm> OpenCodeGoModelKimiK25ReasoningLow {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "kimi-k2.5"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "low"
  }
}

client<llm> OpenCodeGoModelKimiK25ReasoningMedium {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "kimi-k2.5"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "medium"
  }
}

client<llm> OpenCodeGoModelKimiK25ReasoningHigh {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "kimi-k2.5"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "high"
  }
}

client<llm> OpenCodeGoModelKimiK25ReasoningXhigh {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "kimi-k2.5"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "xhigh"
  }
}

client<llm> OpenCodeGoModelGlm51ReasoningNone {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "glm-5.1"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "none"
  }
}

client<llm> OpenCodeGoModelGlm51ReasoningMinimal {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "glm-5.1"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "minimal"
  }
}

client<llm> OpenCodeGoModelGlm51ReasoningLow {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "glm-5.1"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "low"
  }
}

client<llm> OpenCodeGoModelGlm51ReasoningMedium {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "glm-5.1"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "medium"
  }
}

client<llm> OpenCodeGoModelGlm51ReasoningHigh {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "glm-5.1"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "high"
  }
}

client<llm> OpenCodeGoModelGlm51ReasoningXhigh {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "glm-5.1"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "xhigh"
  }
}

client<llm> OpenCodeGoModelGlm5ReasoningNone {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "glm-5"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "none"
  }
}

client<llm> OpenCodeGoModelGlm5ReasoningMinimal {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "glm-5"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "minimal"
  }
}

client<llm> OpenCodeGoModelGlm5ReasoningLow {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "glm-5"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "low"
  }
}

client<llm> OpenCodeGoModelGlm5ReasoningMedium {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "glm-5"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "medium"
  }
}

client<llm> OpenCodeGoModelGlm5ReasoningHigh {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "glm-5"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "high"
  }
}

client<llm> OpenCodeGoModelGlm5ReasoningXhigh {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "glm-5"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "xhigh"
  }
}

client<llm> OpenCodeGoModelDeepseekV4ProReasoningNone {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "deepseek-v4-pro"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "none"
  }
}

client<llm> OpenCodeGoModelDeepseekV4ProReasoningMinimal {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "deepseek-v4-pro"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "minimal"
  }
}

client<llm> OpenCodeGoModelDeepseekV4ProReasoningLow {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "deepseek-v4-pro"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "low"
  }
}

client<llm> OpenCodeGoModelDeepseekV4ProReasoningMedium {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "deepseek-v4-pro"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "medium"
  }
}

client<llm> OpenCodeGoModelDeepseekV4ProReasoningHigh {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "deepseek-v4-pro"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "high"
  }
}

client<llm> OpenCodeGoModelDeepseekV4ProReasoningXhigh {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "deepseek-v4-pro"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "xhigh"
  }
}

client<llm> OpenCodeGoModelDeepseekV4FlashReasoningNone {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "deepseek-v4-flash"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "none"
  }
}

client<llm> OpenCodeGoModelDeepseekV4FlashReasoningMinimal {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "deepseek-v4-flash"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "minimal"
  }
}

client<llm> OpenCodeGoModelDeepseekV4FlashReasoningLow {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "deepseek-v4-flash"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "low"
  }
}

client<llm> OpenCodeGoModelDeepseekV4FlashReasoningMedium {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "deepseek-v4-flash"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "medium"
  }
}

client<llm> OpenCodeGoModelDeepseekV4FlashReasoningHigh {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "deepseek-v4-flash"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "high"
  }
}

client<llm> OpenCodeGoModelDeepseekV4FlashReasoningXhigh {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "deepseek-v4-flash"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "xhigh"
  }
}

client<llm> OpenCodeGoModelMimoV25ProReasoningNone {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "mimo-v2.5-pro"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "none"
  }
}

client<llm> OpenCodeGoModelMimoV25ProReasoningMinimal {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "mimo-v2.5-pro"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "minimal"
  }
}

client<llm> OpenCodeGoModelMimoV25ProReasoningLow {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "mimo-v2.5-pro"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "low"
  }
}

client<llm> OpenCodeGoModelMimoV25ProReasoningMedium {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "mimo-v2.5-pro"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "medium"
  }
}

client<llm> OpenCodeGoModelMimoV25ProReasoningHigh {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "mimo-v2.5-pro"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "high"
  }
}

client<llm> OpenCodeGoModelMimoV25ProReasoningXhigh {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "mimo-v2.5-pro"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "xhigh"
  }
}

client<llm> OpenCodeGoModelMimoV25ReasoningNone {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "mimo-v2.5"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "none"
  }
}

client<llm> OpenCodeGoModelMimoV25ReasoningMinimal {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "mimo-v2.5"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "minimal"
  }
}

client<llm> OpenCodeGoModelMimoV25ReasoningLow {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "mimo-v2.5"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "low"
  }
}

client<llm> OpenCodeGoModelMimoV25ReasoningMedium {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "mimo-v2.5"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "medium"
  }
}

client<llm> OpenCodeGoModelMimoV25ReasoningHigh {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "mimo-v2.5"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "high"
  }
}

client<llm> OpenCodeGoModelMimoV25ReasoningXhigh {
  provider openai-generic
  options {
    base_url "https://opencode.ai/zen/go/v1"
    model "mimo-v2.5"
    api_key env.OPENCODE_GO_API_KEY
    reasoning_effort "xhigh"
  }
}
