# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import enum
import typing
import pydantic

if typing.TYPE_CHECKING:
    from .. import baml
    from .. import memory
    from .. import stream_types
    from .. import task_catalog
    from .. import turn_context
    from ..baml import UNSET as UNSET


def SummariseActionHistory(current_conversation: typing.Optional[turn_context.ConversationHistory], recorded_action_history: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> str:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
async def SummariseActionHistory_async(current_conversation: typing.Optional[turn_context.ConversationHistory], recorded_action_history: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> str:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
def SummariseActionHistory__build_request(current_conversation: typing.Optional[turn_context.ConversationHistory], recorded_action_history: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def SummariseActionHistory__build_request_async(current_conversation: typing.Optional[turn_context.ConversationHistory], recorded_action_history: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def SummariseActionHistory__build_request_stream(current_conversation: typing.Optional[turn_context.ConversationHistory], recorded_action_history: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def SummariseActionHistory__build_request_stream_async(current_conversation: typing.Optional[turn_context.ConversationHistory], recorded_action_history: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def SummariseActionHistory__parse(json: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> str:
    """Raises:
        ParseError"""
async def SummariseActionHistory__parse_async(json: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> str:
    """Raises:
        ParseError"""
def SummariseActionHistory__parse_stream(sse: baml.http.SseStream, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[str], str]:
    """Raises:
        InvalidArgument, LlmClient"""
async def SummariseActionHistory__parse_stream_async(sse: baml.http.SseStream, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[str], str]:
    """Raises:
        InvalidArgument, LlmClient"""
def SummariseActionHistory__render_prompt(current_conversation: typing.Optional[turn_context.ConversationHistory], recorded_action_history: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.PromptAst:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def SummariseActionHistory__render_prompt_async(current_conversation: typing.Optional[turn_context.ConversationHistory], recorded_action_history: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.PromptAst:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def SummariseActionHistory_stream(current_conversation: typing.Optional[turn_context.ConversationHistory], recorded_action_history: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[str], str]:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
async def SummariseActionHistory_stream_async(current_conversation: typing.Optional[turn_context.ConversationHistory], recorded_action_history: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[str], str]:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


def CheckTaskCompletion(completion_string: str, output_summary: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> CompletionResult:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
async def CheckTaskCompletion_async(completion_string: str, output_summary: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> CompletionResult:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
def CheckTaskCompletion__build_request(completion_string: str, output_summary: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def CheckTaskCompletion__build_request_async(completion_string: str, output_summary: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def CheckTaskCompletion__build_request_stream(completion_string: str, output_summary: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def CheckTaskCompletion__build_request_stream_async(completion_string: str, output_summary: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def CheckTaskCompletion__parse(json: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> CompletionResult:
    """Raises:
        ParseError"""
async def CheckTaskCompletion__parse_async(json: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> CompletionResult:
    """Raises:
        ParseError"""
def CheckTaskCompletion__parse_stream(sse: baml.http.SseStream, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[CompletionResult], CompletionResult]:
    """Raises:
        InvalidArgument, LlmClient"""
async def CheckTaskCompletion__parse_stream_async(sse: baml.http.SseStream, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[CompletionResult], CompletionResult]:
    """Raises:
        InvalidArgument, LlmClient"""
def CheckTaskCompletion__render_prompt(completion_string: str, output_summary: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.PromptAst:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def CheckTaskCompletion__render_prompt_async(completion_string: str, output_summary: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.PromptAst:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def CheckTaskCompletion_stream(completion_string: str, output_summary: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[CompletionResult], CompletionResult]:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
async def CheckTaskCompletion_stream_async(completion_string: str, output_summary: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[CompletionResult], CompletionResult]:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


class CompletionResult(str, enum.Enum):
    PASS = "PASS"
    FAIL = "FAIL"


def PerformTask(full_task_prompt: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> TaskExecutionResult:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
async def PerformTask_async(full_task_prompt: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> TaskExecutionResult:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
def PerformTask__build_request(full_task_prompt: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def PerformTask__build_request_async(full_task_prompt: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def PerformTask__build_request_stream(full_task_prompt: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def PerformTask__build_request_stream_async(full_task_prompt: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def PerformTask__parse(json: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> TaskExecutionResult:
    """Raises:
        ParseError"""
async def PerformTask__parse_async(json: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> TaskExecutionResult:
    """Raises:
        ParseError"""
def PerformTask__parse_stream(sse: baml.http.SseStream, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.task.TaskExecutionResult], TaskExecutionResult]:
    """Raises:
        InvalidArgument, LlmClient"""
async def PerformTask__parse_stream_async(sse: baml.http.SseStream, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.task.TaskExecutionResult], TaskExecutionResult]:
    """Raises:
        InvalidArgument, LlmClient"""
def PerformTask__render_prompt(full_task_prompt: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.PromptAst:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def PerformTask__render_prompt_async(full_task_prompt: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.PromptAst:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def PerformTask_stream(full_task_prompt: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.task.TaskExecutionResult], TaskExecutionResult]:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
async def PerformTask_stream_async(full_task_prompt: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.task.TaskExecutionResult], TaskExecutionResult]:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


class TaskReturnItem(pydantic.BaseModel):
    name: str
    payload: typing.Optional[typing.Dict[str, str]]


class TaskExecutionResult(pydantic.BaseModel):
    returns: typing.List[TaskReturnItem]


def PromptText(selected_task_prompt: str, task_input: str) -> str: ...
async def PromptText_async(selected_task_prompt: str, task_input: str) -> str: ...


def PromptDecision(selected_task_prompt: str, composition: TaskPromptComposition) -> TaskPromptDecision: ...
async def PromptDecision_async(selected_task_prompt: str, composition: TaskPromptComposition) -> TaskPromptDecision: ...


def ComposeTaskInput(current_user_request: str, current_conversation: typing.Optional[turn_context.ConversationHistory], session_memories: typing.List[turn_context.SessionMemoryContext], selected_task: task_catalog.SelectedTaskContext, selected_memories: typing.List[TaskPromptSelectedMemoryContext], task_prompt_memories: typing.List[TaskPromptMemoryContext], machine_state: turn_context.MachineStateContext, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> TaskPromptComposition:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
async def ComposeTaskInput_async(current_user_request: str, current_conversation: typing.Optional[turn_context.ConversationHistory], session_memories: typing.List[turn_context.SessionMemoryContext], selected_task: task_catalog.SelectedTaskContext, selected_memories: typing.List[TaskPromptSelectedMemoryContext], task_prompt_memories: typing.List[TaskPromptMemoryContext], machine_state: turn_context.MachineStateContext, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> TaskPromptComposition:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
def ComposeTaskInput__build_request(current_user_request: str, current_conversation: typing.Optional[turn_context.ConversationHistory], session_memories: typing.List[turn_context.SessionMemoryContext], selected_task: task_catalog.SelectedTaskContext, selected_memories: typing.List[TaskPromptSelectedMemoryContext], task_prompt_memories: typing.List[TaskPromptMemoryContext], machine_state: turn_context.MachineStateContext, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def ComposeTaskInput__build_request_async(current_user_request: str, current_conversation: typing.Optional[turn_context.ConversationHistory], session_memories: typing.List[turn_context.SessionMemoryContext], selected_task: task_catalog.SelectedTaskContext, selected_memories: typing.List[TaskPromptSelectedMemoryContext], task_prompt_memories: typing.List[TaskPromptMemoryContext], machine_state: turn_context.MachineStateContext, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def ComposeTaskInput__build_request_stream(current_user_request: str, current_conversation: typing.Optional[turn_context.ConversationHistory], session_memories: typing.List[turn_context.SessionMemoryContext], selected_task: task_catalog.SelectedTaskContext, selected_memories: typing.List[TaskPromptSelectedMemoryContext], task_prompt_memories: typing.List[TaskPromptMemoryContext], machine_state: turn_context.MachineStateContext, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def ComposeTaskInput__build_request_stream_async(current_user_request: str, current_conversation: typing.Optional[turn_context.ConversationHistory], session_memories: typing.List[turn_context.SessionMemoryContext], selected_task: task_catalog.SelectedTaskContext, selected_memories: typing.List[TaskPromptSelectedMemoryContext], task_prompt_memories: typing.List[TaskPromptMemoryContext], machine_state: turn_context.MachineStateContext, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def ComposeTaskInput__parse(json: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> TaskPromptComposition:
    """Raises:
        ParseError"""
async def ComposeTaskInput__parse_async(json: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> TaskPromptComposition:
    """Raises:
        ParseError"""
def ComposeTaskInput__parse_stream(sse: baml.http.SseStream, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.task.TaskPromptComposition], TaskPromptComposition]:
    """Raises:
        InvalidArgument, LlmClient"""
async def ComposeTaskInput__parse_stream_async(sse: baml.http.SseStream, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.task.TaskPromptComposition], TaskPromptComposition]:
    """Raises:
        InvalidArgument, LlmClient"""
def ComposeTaskInput__render_prompt(current_user_request: str, current_conversation: typing.Optional[turn_context.ConversationHistory], session_memories: typing.List[turn_context.SessionMemoryContext], selected_task: task_catalog.SelectedTaskContext, selected_memories: typing.List[TaskPromptSelectedMemoryContext], task_prompt_memories: typing.List[TaskPromptMemoryContext], machine_state: turn_context.MachineStateContext, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.PromptAst:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def ComposeTaskInput__render_prompt_async(current_user_request: str, current_conversation: typing.Optional[turn_context.ConversationHistory], session_memories: typing.List[turn_context.SessionMemoryContext], selected_task: task_catalog.SelectedTaskContext, selected_memories: typing.List[TaskPromptSelectedMemoryContext], task_prompt_memories: typing.List[TaskPromptMemoryContext], machine_state: turn_context.MachineStateContext, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.PromptAst:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def ComposeTaskInput_stream(current_user_request: str, current_conversation: typing.Optional[turn_context.ConversationHistory], session_memories: typing.List[turn_context.SessionMemoryContext], selected_task: task_catalog.SelectedTaskContext, selected_memories: typing.List[TaskPromptSelectedMemoryContext], task_prompt_memories: typing.List[TaskPromptMemoryContext], machine_state: turn_context.MachineStateContext, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.task.TaskPromptComposition], TaskPromptComposition]:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
async def ComposeTaskInput_stream_async(current_user_request: str, current_conversation: typing.Optional[turn_context.ConversationHistory], session_memories: typing.List[turn_context.SessionMemoryContext], selected_task: task_catalog.SelectedTaskContext, selected_memories: typing.List[TaskPromptSelectedMemoryContext], task_prompt_memories: typing.List[TaskPromptMemoryContext], machine_state: turn_context.MachineStateContext, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.task.TaskPromptComposition], TaskPromptComposition]:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


def PromptContexts(memories: memory.RetrievedMemoryGraph, selected_memory_ids: typing.List[str], current_session_id: typing.Optional[str], user_preferences: typing.List[turn_context.UserPreferenceMemoryContext]) -> typing.List[TaskPromptSelectedMemoryContext]: ...
async def PromptContexts_async(memories: memory.RetrievedMemoryGraph, selected_memory_ids: typing.List[str], current_session_id: typing.Optional[str], user_preferences: typing.List[turn_context.UserPreferenceMemoryContext]) -> typing.List[TaskPromptSelectedMemoryContext]: ...


def ContextFromTask(task: memory.RetrievedTaskNode) -> TaskPromptSelectedMemoryContext: ...
async def ContextFromTask_async(task: memory.RetrievedTaskNode) -> TaskPromptSelectedMemoryContext: ...


def ContextFromSession(session: memory.RetrievedSessionGraph, is_current_session: bool) -> TaskPromptSelectedMemoryContext: ...
async def ContextFromSession_async(session: memory.RetrievedSessionGraph, is_current_session: bool) -> TaskPromptSelectedMemoryContext: ...


def ContextFromConversation(session: memory.RetrievedSessionGraph, conversation: memory.RetrievedConversationGraph, is_current_session: bool) -> TaskPromptSelectedMemoryContext: ...
async def ContextFromConversation_async(session: memory.RetrievedSessionGraph, conversation: memory.RetrievedConversationGraph, is_current_session: bool) -> TaskPromptSelectedMemoryContext: ...


def ContextFromSessionMemory(memory: memory.RetrievedSessionMemoryNode) -> TaskPromptSelectedMemoryContext: ...
async def ContextFromSessionMemory_async(memory: memory.RetrievedSessionMemoryNode) -> TaskPromptSelectedMemoryContext: ...


def ContextFromUserPreference(preference: turn_context.UserPreferenceMemoryContext) -> TaskPromptSelectedMemoryContext: ...
async def ContextFromUserPreference_async(preference: turn_context.UserPreferenceMemoryContext) -> TaskPromptSelectedMemoryContext: ...


def ContextFromMessage(message: memory.RetrievedConversationMessageNode) -> TaskPromptSelectedMemoryContext: ...
async def ContextFromMessage_async(message: memory.RetrievedConversationMessageNode) -> TaskPromptSelectedMemoryContext: ...


def KeepSessionContext(session: memory.RetrievedSessionGraph, selected_ids: typing.List[str]) -> bool: ...
async def KeepSessionContext_async(session: memory.RetrievedSessionGraph, selected_ids: typing.List[str]) -> bool: ...


def KeepConversationContext(conversation: memory.RetrievedConversationGraph, selected_ids: typing.List[str]) -> bool: ...
async def KeepConversationContext_async(conversation: memory.RetrievedConversationGraph, selected_ids: typing.List[str]) -> bool: ...


class TaskPromptMemoryContext(pydantic.BaseModel):
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class TaskPromptSelectedMemoryContext(pydantic.BaseModel):
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class TaskPromptDecision(pydantic.BaseModel):
    full_task_prompt: str
    candidate_memory: typing.Optional[memory.CandidateMemory]


class TaskPromptComposition(pydantic.BaseModel):
    task_input: str
    candidate_memory: typing.Optional[memory.CandidateMemory]


def ChooseTask(current_user_request: str, current_conversation: typing.Optional[turn_context.ConversationHistory], session_memories: typing.List[turn_context.SessionMemoryContext], user_preferences: typing.List[turn_context.UserPreferenceMemoryContext], available_tasks: typing.List[task_catalog.AvailableTask], task_choice_memories: typing.List[TaskChoiceMemoryContext], machine_state: turn_context.MachineStateContext, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> TaskChoiceDecision:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
async def ChooseTask_async(current_user_request: str, current_conversation: typing.Optional[turn_context.ConversationHistory], session_memories: typing.List[turn_context.SessionMemoryContext], user_preferences: typing.List[turn_context.UserPreferenceMemoryContext], available_tasks: typing.List[task_catalog.AvailableTask], task_choice_memories: typing.List[TaskChoiceMemoryContext], machine_state: turn_context.MachineStateContext, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> TaskChoiceDecision:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
def ChooseTask__build_request(current_user_request: str, current_conversation: typing.Optional[turn_context.ConversationHistory], session_memories: typing.List[turn_context.SessionMemoryContext], user_preferences: typing.List[turn_context.UserPreferenceMemoryContext], available_tasks: typing.List[task_catalog.AvailableTask], task_choice_memories: typing.List[TaskChoiceMemoryContext], machine_state: turn_context.MachineStateContext, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def ChooseTask__build_request_async(current_user_request: str, current_conversation: typing.Optional[turn_context.ConversationHistory], session_memories: typing.List[turn_context.SessionMemoryContext], user_preferences: typing.List[turn_context.UserPreferenceMemoryContext], available_tasks: typing.List[task_catalog.AvailableTask], task_choice_memories: typing.List[TaskChoiceMemoryContext], machine_state: turn_context.MachineStateContext, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def ChooseTask__build_request_stream(current_user_request: str, current_conversation: typing.Optional[turn_context.ConversationHistory], session_memories: typing.List[turn_context.SessionMemoryContext], user_preferences: typing.List[turn_context.UserPreferenceMemoryContext], available_tasks: typing.List[task_catalog.AvailableTask], task_choice_memories: typing.List[TaskChoiceMemoryContext], machine_state: turn_context.MachineStateContext, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def ChooseTask__build_request_stream_async(current_user_request: str, current_conversation: typing.Optional[turn_context.ConversationHistory], session_memories: typing.List[turn_context.SessionMemoryContext], user_preferences: typing.List[turn_context.UserPreferenceMemoryContext], available_tasks: typing.List[task_catalog.AvailableTask], task_choice_memories: typing.List[TaskChoiceMemoryContext], machine_state: turn_context.MachineStateContext, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def ChooseTask__parse(json: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> TaskChoiceDecision:
    """Raises:
        ParseError"""
async def ChooseTask__parse_async(json: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> TaskChoiceDecision:
    """Raises:
        ParseError"""
def ChooseTask__parse_stream(sse: baml.http.SseStream, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.task.TaskChoiceDecision], TaskChoiceDecision]:
    """Raises:
        InvalidArgument, LlmClient"""
async def ChooseTask__parse_stream_async(sse: baml.http.SseStream, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.task.TaskChoiceDecision], TaskChoiceDecision]:
    """Raises:
        InvalidArgument, LlmClient"""
def ChooseTask__render_prompt(current_user_request: str, current_conversation: typing.Optional[turn_context.ConversationHistory], session_memories: typing.List[turn_context.SessionMemoryContext], user_preferences: typing.List[turn_context.UserPreferenceMemoryContext], available_tasks: typing.List[task_catalog.AvailableTask], task_choice_memories: typing.List[TaskChoiceMemoryContext], machine_state: turn_context.MachineStateContext, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.PromptAst:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def ChooseTask__render_prompt_async(current_user_request: str, current_conversation: typing.Optional[turn_context.ConversationHistory], session_memories: typing.List[turn_context.SessionMemoryContext], user_preferences: typing.List[turn_context.UserPreferenceMemoryContext], available_tasks: typing.List[task_catalog.AvailableTask], task_choice_memories: typing.List[TaskChoiceMemoryContext], machine_state: turn_context.MachineStateContext, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.PromptAst:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def ChooseTask_stream(current_user_request: str, current_conversation: typing.Optional[turn_context.ConversationHistory], session_memories: typing.List[turn_context.SessionMemoryContext], user_preferences: typing.List[turn_context.UserPreferenceMemoryContext], available_tasks: typing.List[task_catalog.AvailableTask], task_choice_memories: typing.List[TaskChoiceMemoryContext], machine_state: turn_context.MachineStateContext, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.task.TaskChoiceDecision], TaskChoiceDecision]:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
async def ChooseTask_stream_async(current_user_request: str, current_conversation: typing.Optional[turn_context.ConversationHistory], session_memories: typing.List[turn_context.SessionMemoryContext], user_preferences: typing.List[turn_context.UserPreferenceMemoryContext], available_tasks: typing.List[task_catalog.AvailableTask], task_choice_memories: typing.List[TaskChoiceMemoryContext], machine_state: turn_context.MachineStateContext, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.task.TaskChoiceDecision], TaskChoiceDecision]:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


class TaskChoiceMemoryContext(pydantic.BaseModel):
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class TaskChoiceDecision(pydantic.BaseModel):
    selected_task_id: str
    confidence: float
    candidate_memory: typing.Optional[memory.CandidateMemory]


__all__ = [
    "SummariseActionHistory",
    "SummariseActionHistory_async",
    "SummariseActionHistory__build_request",
    "SummariseActionHistory__build_request_async",
    "SummariseActionHistory__build_request_stream",
    "SummariseActionHistory__build_request_stream_async",
    "SummariseActionHistory__parse",
    "SummariseActionHistory__parse_async",
    "SummariseActionHistory__parse_stream",
    "SummariseActionHistory__parse_stream_async",
    "SummariseActionHistory__render_prompt",
    "SummariseActionHistory__render_prompt_async",
    "SummariseActionHistory_stream",
    "SummariseActionHistory_stream_async",
    "CheckTaskCompletion",
    "CheckTaskCompletion_async",
    "CheckTaskCompletion__build_request",
    "CheckTaskCompletion__build_request_async",
    "CheckTaskCompletion__build_request_stream",
    "CheckTaskCompletion__build_request_stream_async",
    "CheckTaskCompletion__parse",
    "CheckTaskCompletion__parse_async",
    "CheckTaskCompletion__parse_stream",
    "CheckTaskCompletion__parse_stream_async",
    "CheckTaskCompletion__render_prompt",
    "CheckTaskCompletion__render_prompt_async",
    "CheckTaskCompletion_stream",
    "CheckTaskCompletion_stream_async",
    "CompletionResult",
    "PerformTask",
    "PerformTask_async",
    "PerformTask__build_request",
    "PerformTask__build_request_async",
    "PerformTask__build_request_stream",
    "PerformTask__build_request_stream_async",
    "PerformTask__parse",
    "PerformTask__parse_async",
    "PerformTask__parse_stream",
    "PerformTask__parse_stream_async",
    "PerformTask__render_prompt",
    "PerformTask__render_prompt_async",
    "PerformTask_stream",
    "PerformTask_stream_async",
    "TaskReturnItem",
    "TaskExecutionResult",
    "PromptText",
    "PromptText_async",
    "PromptDecision",
    "PromptDecision_async",
    "ComposeTaskInput",
    "ComposeTaskInput_async",
    "ComposeTaskInput__build_request",
    "ComposeTaskInput__build_request_async",
    "ComposeTaskInput__build_request_stream",
    "ComposeTaskInput__build_request_stream_async",
    "ComposeTaskInput__parse",
    "ComposeTaskInput__parse_async",
    "ComposeTaskInput__parse_stream",
    "ComposeTaskInput__parse_stream_async",
    "ComposeTaskInput__render_prompt",
    "ComposeTaskInput__render_prompt_async",
    "ComposeTaskInput_stream",
    "ComposeTaskInput_stream_async",
    "PromptContexts",
    "PromptContexts_async",
    "ContextFromTask",
    "ContextFromTask_async",
    "ContextFromSession",
    "ContextFromSession_async",
    "ContextFromConversation",
    "ContextFromConversation_async",
    "ContextFromSessionMemory",
    "ContextFromSessionMemory_async",
    "ContextFromUserPreference",
    "ContextFromUserPreference_async",
    "ContextFromMessage",
    "ContextFromMessage_async",
    "KeepSessionContext",
    "KeepSessionContext_async",
    "KeepConversationContext",
    "KeepConversationContext_async",
    "TaskPromptMemoryContext",
    "TaskPromptSelectedMemoryContext",
    "TaskPromptDecision",
    "TaskPromptComposition",
    "ChooseTask",
    "ChooseTask_async",
    "ChooseTask__build_request",
    "ChooseTask__build_request_async",
    "ChooseTask__build_request_stream",
    "ChooseTask__build_request_stream_async",
    "ChooseTask__parse",
    "ChooseTask__parse_async",
    "ChooseTask__parse_stream",
    "ChooseTask__parse_stream_async",
    "ChooseTask__render_prompt",
    "ChooseTask__render_prompt_async",
    "ChooseTask_stream",
    "ChooseTask_stream_async",
    "TaskChoiceMemoryContext",
    "TaskChoiceDecision",
]
