# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import typing
import pydantic

if typing.TYPE_CHECKING:
    from .... import memory
    from .... import stream_types


class CandidateMemoryReview(pydantic.BaseModel):
    layer: typing.Optional[memory.CandidateMemoryLayer]
    candidates: typing.List[stream_types.memory.CandidateMemoryEntry]
    kept_candidates: typing.List[stream_types.memory.CandidateMemoryEntry]


class CandidateMemoryReviewInput(pydantic.BaseModel):
    layer: typing.Optional[memory.CandidateMemoryLayer]
    purpose: typing.Optional[str]
    candidates: typing.List[stream_types.memory.CandidateMemoryEntry]
    stored_memories: typing.List[stream_types.memory.StoredCandidateMemory]


__all__ = [
    "CandidateMemoryReview",
    "CandidateMemoryReviewInput",
]
