# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

from . import postgres
from . import sqlite

import typing
import pydantic

if typing.TYPE_CHECKING:
    from .... import baml
    from .... import stream_types

from baml_bridge import BamlPyHandle as _BamlPyHandle


class CommandResult(pydantic.BaseModel):
    rows_affected: typing.Optional[int]


class ConnectOptions(pydantic.BaseModel):
    max_connections: typing.Optional[int]
    connect_timeout: typing.Optional[stream_types.baml.time.Duration]
    query_timeout: typing.Optional[stream_types.baml.time.Duration]
    validate: typing.Optional[bool]


class Database(pydantic.BaseModel):
    _handle: _BamlPyHandle


class JsonValue(pydantic.BaseModel):
    value: typing.Optional[stream_types.baml.json.json]


class QueryOptions(pydantic.BaseModel):
    timeout: typing.Optional[stream_types.baml.time.Duration]


class SqlError(pydantic.BaseModel):
    kind: typing.Optional[baml.sql.SqlErrorKind]
    message: typing.Optional[str]
    code: typing.Optional[str]
    constraint: typing.Optional[str]
    table: typing.Optional[str]
    column: typing.Optional[str]


class Statement(pydantic.BaseModel):
    _handle: _BamlPyHandle


class Transaction(pydantic.BaseModel):
    _handle: _BamlPyHandle


class TransactionOptions(pydantic.BaseModel):
    isolation: typing.Optional[baml.sql.SqlIsolation]
    read_only: typing.Optional[bool]


__all__ = [
    "CommandResult",
    "ConnectOptions",
    "Database",
    "JsonValue",
    "QueryOptions",
    "SqlError",
    "Statement",
    "Transaction",
    "TransactionOptions",
]
