# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import enum
import typing
import pydantic

from .... import baml

from baml_bridge import define_function as _define_function


class PostgresSslMode(str, enum.Enum):
    Disable = "Disable"
    Allow = "Allow"
    Prefer = "Prefer"
    Require = "Require"
    VerifyCa = "VerifyCa"
    VerifyFull = "VerifyFull"


class PostgresOptions(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    max_connections: typing.Optional[int]
    min_connections: typing.Optional[int]
    connect_timeout: typing.Optional[baml.time.Duration]
    query_timeout: typing.Optional[baml.time.Duration]
    idle_timeout: typing.Optional[baml.time.Duration]
    max_lifetime: typing.Optional[baml.time.Duration]
    application_name: typing.Optional[str]
    ssl_mode: typing.Optional[PostgresSslMode]
    validate: typing.Optional[bool]


connect       = _define_function("baml.sql.postgres.connect", "sync",  ["url"], ["options"])
connect.__doc__ = """Raises:
    SqlError"""
connect_async = _define_function("baml.sql.postgres.connect", "async", ["url"], ["options"])
connect_async.__doc__ = """Raises:
    SqlError"""


_connect_postgres       = _define_function("baml.sql.postgres._connect_postgres", "sync",  ["url", "options"])
_connect_postgres.__doc__ = """Raises:
    SqlError, Unsupported"""
_connect_postgres_async = _define_function("baml.sql.postgres._connect_postgres", "async", ["url", "options"])
_connect_postgres_async.__doc__ = """Raises:
    SqlError, Unsupported"""


__all__ = [
    "PostgresSslMode",
    "PostgresOptions",
    "connect",
    "connect_async",
]
