# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

_LAZY_CHILDREN = frozenset({
    "baml",
    "vendor",
})

def __getattr__(name):
    if name in _LAZY_CHILDREN:
        import importlib
        return importlib.import_module(f".{name}", __name__)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

import typing
import pydantic


class AvailableTask(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: typing.Optional[str]
    name: typing.Optional[str]
    description: typing.Optional[str]
    input: typing.Optional[str]
    output: typing.Optional[str]
    prompt: typing.Optional[str]
    provider_id: typing.Optional[str]
    created_at: typing.Optional[str]
    updated_at: typing.Optional[str]
    read_at: typing.Optional[str]


class CandidateMemory(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    title: typing.Optional[str]
    description: typing.Optional[str]


class ConversationEvaluationMemoryContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    title: typing.Optional[str]
    description: typing.Optional[str]
    tags: typing.List[str]
    created_at: typing.Optional[str]
    updated_at: typing.Optional[str]
    read_at: typing.Optional[str]


class ConversationHistory(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: typing.Optional[str]
    name: typing.Optional[str]
    created_at: typing.Optional[str]
    updated_at: typing.Optional[str]
    read_at: typing.Optional[str]
    messages: typing.List[ConversationHistoryMessage]


class ConversationHistoryMessage(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    created_at: typing.Optional[str]
    updated_at: typing.Optional[str]
    read_at: typing.Optional[str]
    role: typing.Optional[str]
    content: typing.Optional[str]


class ConversationMemorySearchHints(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    tags: typing.Optional[MemoryTagSearch]
    strings: typing.Optional[MemoryStringSearch]
    candidate_memory: typing.Optional[CandidateMemory]


class MachineMonitorContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    horizontal_resolution: typing.Optional[int]
    vertical_resolution: typing.Optional[int]


class MachineStateContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    captured_at_utc: typing.Optional[str]
    current_local_time: typing.Optional[str]
    current_utc_time: typing.Optional[str]
    timezone_name: typing.Optional[str]
    utc_offset: typing.Optional[str]
    os_architecture: typing.Optional[str]
    monitor_count: typing.Optional[int]
    monitors: typing.List[MachineMonitorContext]
    geolocation_status: typing.Optional[str]
    geolocation_source: typing.Optional[str]
    ip_address: typing.Optional[str]
    country: typing.Optional[str]
    country_code: typing.Optional[str]
    region: typing.Optional[str]
    city: typing.Optional[str]
    postal_code: typing.Optional[str]
    latitude: typing.Optional[str]
    longitude: typing.Optional[str]
    geolocation_timezone: typing.Optional[str]
    organization: typing.Optional[str]
    asn: typing.Optional[str]
    geolocation_error: typing.Optional[str]


class MemoryStringSearch(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    contains: typing.List[str]
    equals: typing.List[str]


class MemoryTagSearch(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    any_of: typing.List[str]
    all_of: typing.List[str]
    none_of: typing.List[str]


class RelevanceMemoryContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    title: typing.Optional[str]
    description: typing.Optional[str]
    tags: typing.List[str]
    created_at: typing.Optional[str]
    updated_at: typing.Optional[str]
    read_at: typing.Optional[str]


class RelevantMemoryDecision(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    kept_memory_ids: typing.List[str]
    candidate_memory: typing.Optional[CandidateMemory]


class RetrievedMemoryCandidate(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: typing.Optional[str]
    kind: typing.Optional[str]
    title: typing.Optional[str]
    description: typing.Optional[str]
    tags: typing.List[str]
    created_at: typing.Optional[str]
    updated_at: typing.Optional[str]
    read_at: typing.Optional[str]
    retrieval_matched: typing.Optional[bool]
    parent_session_id: typing.Optional[str]
    parent_conversation_id: typing.Optional[str]


class SearchDepthDecision(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    depths: typing.Dict[str, SearchDepthTimestamps]
    candidate_memory: typing.Optional[CandidateMemory]


class SearchDepthDomain(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: typing.Optional[str]
    description: typing.Optional[str]
    searches: typing.Optional[str]
    hydrates: typing.Optional[str]


class SearchDepthMemoryContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    title: typing.Optional[str]
    description: typing.Optional[str]
    tags: typing.List[str]
    created_at: typing.Optional[str]
    updated_at: typing.Optional[str]
    read_at: typing.Optional[str]


class SearchDepthTimestamps(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    created_after: typing.Optional[str]
    read_after: typing.Optional[str]
    updated_after: typing.Optional[str]


class SelectedTaskContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: typing.Optional[str]
    name: typing.Optional[str]
    description: typing.Optional[str]
    input: typing.Optional[str]
    output: typing.Optional[str]
    prompt: typing.Optional[str]
    provider_id: typing.Optional[str]
    created_at: typing.Optional[str]
    updated_at: typing.Optional[str]
    read_at: typing.Optional[str]


class SessionMemoryContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    title: typing.Optional[str]
    description: typing.Optional[str]
    tags: typing.List[str]
    created_at: typing.Optional[str]
    updated_at: typing.Optional[str]
    read_at: typing.Optional[str]


class TaskChoiceDecision(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    selected_task_id: typing.Optional[str]
    confidence: typing.Optional[float]
    candidate_memory: typing.Optional[CandidateMemory]


class TaskChoiceMemoryContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    title: typing.Optional[str]
    description: typing.Optional[str]
    tags: typing.List[str]
    created_at: typing.Optional[str]
    updated_at: typing.Optional[str]
    read_at: typing.Optional[str]


class TaskExecutionResult(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    returns: typing.List[TaskReturnItem]


class TaskPromptComposition(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    task_input: typing.Optional[str]
    candidate_memory: typing.Optional[CandidateMemory]


class TaskPromptDecision(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    full_task_prompt: typing.Optional[str]
    candidate_memory: typing.Optional[CandidateMemory]


class TaskPromptMemoryContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    title: typing.Optional[str]
    description: typing.Optional[str]
    tags: typing.List[str]
    created_at: typing.Optional[str]
    updated_at: typing.Optional[str]
    read_at: typing.Optional[str]


class TaskPromptSelectedMemoryContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    title: typing.Optional[str]
    description: typing.Optional[str]
    tags: typing.List[str]
    created_at: typing.Optional[str]
    updated_at: typing.Optional[str]
    read_at: typing.Optional[str]


class TaskReturnItem(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    name: typing.Optional[str]
    payload: typing.Optional[typing.Dict[str, str]]


class UserPreferenceMemoryContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: typing.Optional[str]
    title: typing.Optional[str]
    description: typing.Optional[str]
    tags: typing.List[str]
    created_at: typing.Optional[str]
    updated_at: typing.Optional[str]
    read_at: typing.Optional[str]


class RetrievedConversationGraph(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    conversation: typing.Optional[RetrievedConversationNode]
    matched: typing.Optional[bool]
    messages: typing.List[RetrievedConversationMessageNode]
    matched_message_ids: typing.List[str]


class RetrievedConversationMessageNode(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: typing.Optional[str]
    role: typing.Optional[str]
    content: typing.Optional[str]
    tags: typing.List[str]
    created_at: typing.Optional[str]
    updated_at: typing.Optional[str]
    read_at: typing.Optional[str]


class RetrievedConversationNode(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: typing.Optional[str]
    name: typing.Optional[str]
    tags: typing.List[str]
    created_at: typing.Optional[str]
    updated_at: typing.Optional[str]
    read_at: typing.Optional[str]


class RetrievedMemoryGraph(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    task_catalog: typing.List[RetrievedTaskNode]
    past_sessions: typing.List[RetrievedSessionGraph]
    current_session_memories: typing.List[RetrievedSessionMemoryNode]


class RetrievedSessionGraph(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    session: typing.Optional[RetrievedSessionNode]
    matched: typing.Optional[bool]
    conversations: typing.List[RetrievedConversationGraph]
    session_memories: typing.List[RetrievedSessionMemoryNode]


class RetrievedSessionMemoryNode(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: typing.Optional[str]
    title: typing.Optional[str]
    description: typing.Optional[str]
    tags: typing.List[str]
    created_at: typing.Optional[str]
    updated_at: typing.Optional[str]
    read_at: typing.Optional[str]


class RetrievedSessionNode(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: typing.Optional[str]
    name: typing.Optional[str]
    tags: typing.List[str]
    created_at: typing.Optional[str]
    updated_at: typing.Optional[str]
    read_at: typing.Optional[str]


class RetrievedTaskNode(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: typing.Optional[str]
    name: typing.Optional[str]
    description: typing.Optional[str]
    input: typing.Optional[str]
    output: typing.Optional[str]
    prompt: typing.Optional[str]
    provider_id: typing.Optional[str]
    tags: typing.List[str]
    created_at: typing.Optional[str]
    updated_at: typing.Optional[str]
    read_at: typing.Optional[str]


class VoicePromptContinuation(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    relevance_decision: typing.Optional[RelevantMemoryDecision]
    selected_memories: typing.Optional[RetrievedMemoryGraph]
    selected_memory_contexts: typing.List[TaskPromptSelectedMemoryContext]
    task_prompt: typing.Optional[TaskPromptDecision]
    timings: typing.Optional[VoicePromptContinuationTimings]


class VoicePromptContinuationTimings(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    memory_relevance_ms: typing.Optional[int]
    task_prompt_ms: typing.Optional[int]


class VoicePromptUnderstanding(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    task_choice: typing.Optional[TaskChoiceDecision]
    selected_task: typing.Optional[SelectedTaskContext]
    memory_search_hints: typing.Optional[ConversationMemorySearchHints]
    search_depths: typing.Optional[SearchDepthDecision]
    timings: typing.Optional[VoicePromptUnderstandingTimings]


class VoicePromptUnderstandingTimings(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    task_choice_ms: typing.Optional[int]
    memory_search_ms: typing.Optional[int]
    search_depth_ms: typing.Optional[int]


__all__ = [
    "AvailableTask",
    "CandidateMemory",
    "ConversationEvaluationMemoryContext",
    "ConversationHistory",
    "ConversationHistoryMessage",
    "ConversationMemorySearchHints",
    "MachineMonitorContext",
    "MachineStateContext",
    "MemoryStringSearch",
    "MemoryTagSearch",
    "RelevanceMemoryContext",
    "RelevantMemoryDecision",
    "RetrievedMemoryCandidate",
    "SearchDepthDecision",
    "SearchDepthDomain",
    "SearchDepthMemoryContext",
    "SearchDepthTimestamps",
    "SelectedTaskContext",
    "SessionMemoryContext",
    "TaskChoiceDecision",
    "TaskChoiceMemoryContext",
    "TaskExecutionResult",
    "TaskPromptComposition",
    "TaskPromptDecision",
    "TaskPromptMemoryContext",
    "TaskPromptSelectedMemoryContext",
    "TaskReturnItem",
    "UserPreferenceMemoryContext",
    "RetrievedConversationGraph",
    "RetrievedConversationMessageNode",
    "RetrievedConversationNode",
    "RetrievedMemoryGraph",
    "RetrievedSessionGraph",
    "RetrievedSessionMemoryNode",
    "RetrievedSessionNode",
    "RetrievedTaskNode",
    "VoicePromptContinuation",
    "VoicePromptContinuationTimings",
    "VoicePromptUnderstanding",
    "VoicePromptUnderstandingTimings",
]
