# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import typing
import pydantic

if typing.TYPE_CHECKING:
    from .. import baml
    from .. import context
    from .. import memory_search
    from .. import retrieved_memory
    from .. import stream_types
    from .. import task_routing
    from ..baml import UNSET as UNSET


def Candidates(memories: retrieved_memory.RetrievedMemoryGraph, current_session_id: typing.Optional[str], user_preferences: typing.List[context.UserPreferenceMemoryContext]) -> typing.List[RetrievedMemoryCandidate]: ...
async def Candidates_async(memories: retrieved_memory.RetrievedMemoryGraph, current_session_id: typing.Optional[str], user_preferences: typing.List[context.UserPreferenceMemoryContext]) -> typing.List[RetrievedMemoryCandidate]: ...


def TaskCandidate(task: retrieved_memory.RetrievedTaskNode) -> RetrievedMemoryCandidate: ...
async def TaskCandidate_async(task: retrieved_memory.RetrievedTaskNode) -> RetrievedMemoryCandidate: ...


def CurrentSessionMemoryCandidate(memory: retrieved_memory.RetrievedSessionMemoryNode, current_session_id: typing.Optional[str]) -> RetrievedMemoryCandidate: ...
async def CurrentSessionMemoryCandidate_async(memory: retrieved_memory.RetrievedSessionMemoryNode, current_session_id: typing.Optional[str]) -> RetrievedMemoryCandidate: ...


def UserPreferenceCandidate(preference: context.UserPreferenceMemoryContext) -> RetrievedMemoryCandidate: ...
async def UserPreferenceCandidate_async(preference: context.UserPreferenceMemoryContext) -> RetrievedMemoryCandidate: ...


def TaskCandidateDescription(task: retrieved_memory.RetrievedTaskNode) -> str: ...
async def TaskCandidateDescription_async(task: retrieved_memory.RetrievedTaskNode) -> str: ...


def SessionCandidate(session: retrieved_memory.RetrievedSessionGraph, is_current_session: bool) -> RetrievedMemoryCandidate: ...
async def SessionCandidate_async(session: retrieved_memory.RetrievedSessionGraph, is_current_session: bool) -> RetrievedMemoryCandidate: ...


def SessionMemoryCandidate(session: retrieved_memory.RetrievedSessionGraph, memory: retrieved_memory.RetrievedSessionMemoryNode, is_current_session: bool) -> RetrievedMemoryCandidate: ...
async def SessionMemoryCandidate_async(session: retrieved_memory.RetrievedSessionGraph, memory: retrieved_memory.RetrievedSessionMemoryNode, is_current_session: bool) -> RetrievedMemoryCandidate: ...


def ConversationCandidate(session: retrieved_memory.RetrievedSessionGraph, conversation: retrieved_memory.RetrievedConversationGraph, is_current_session: bool) -> RetrievedMemoryCandidate: ...
async def ConversationCandidate_async(session: retrieved_memory.RetrievedSessionGraph, conversation: retrieved_memory.RetrievedConversationGraph, is_current_session: bool) -> RetrievedMemoryCandidate: ...


def ConversationMessageCandidate(session: retrieved_memory.RetrievedSessionGraph, conversation: retrieved_memory.RetrievedConversationGraph, message: retrieved_memory.RetrievedConversationMessageNode, is_current_session: bool) -> RetrievedMemoryCandidate: ...
async def ConversationMessageCandidate_async(session: retrieved_memory.RetrievedSessionGraph, conversation: retrieved_memory.RetrievedConversationGraph, message: retrieved_memory.RetrievedConversationMessageNode, is_current_session: bool) -> RetrievedMemoryCandidate: ...


def MessageMatchedMemorySearch(conversation: retrieved_memory.RetrievedConversationGraph, message: retrieved_memory.RetrievedConversationMessageNode) -> bool: ...
async def MessageMatchedMemorySearch_async(conversation: retrieved_memory.RetrievedConversationGraph, message: retrieved_memory.RetrievedConversationMessageNode) -> bool: ...


def IsCurrentSession(session: retrieved_memory.RetrievedSessionGraph, current_session_id: typing.Optional[str]) -> bool: ...
async def IsCurrentSession_async(session: retrieved_memory.RetrievedSessionGraph, current_session_id: typing.Optional[str]) -> bool: ...


def SelectRelevantMemories(current_user_request: str, current_conversation: typing.Optional[context.ConversationHistory], session_memories: typing.List[context.SessionMemoryContext], selected_task: task_routing.SelectedTaskContext, candidate_memories: typing.List[RetrievedMemoryCandidate], relevance_memories: typing.List[RelevanceMemoryContext], machine_state: context.MachineStateContext, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> RelevantMemoryDecision:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
async def SelectRelevantMemories_async(current_user_request: str, current_conversation: typing.Optional[context.ConversationHistory], session_memories: typing.List[context.SessionMemoryContext], selected_task: task_routing.SelectedTaskContext, candidate_memories: typing.List[RetrievedMemoryCandidate], relevance_memories: typing.List[RelevanceMemoryContext], machine_state: context.MachineStateContext, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> RelevantMemoryDecision:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
def SelectRelevantMemories__build_request(current_user_request: str, current_conversation: typing.Optional[context.ConversationHistory], session_memories: typing.List[context.SessionMemoryContext], selected_task: task_routing.SelectedTaskContext, candidate_memories: typing.List[RetrievedMemoryCandidate], relevance_memories: typing.List[RelevanceMemoryContext], machine_state: context.MachineStateContext, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def SelectRelevantMemories__build_request_async(current_user_request: str, current_conversation: typing.Optional[context.ConversationHistory], session_memories: typing.List[context.SessionMemoryContext], selected_task: task_routing.SelectedTaskContext, candidate_memories: typing.List[RetrievedMemoryCandidate], relevance_memories: typing.List[RelevanceMemoryContext], machine_state: context.MachineStateContext, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def SelectRelevantMemories__build_request_stream(current_user_request: str, current_conversation: typing.Optional[context.ConversationHistory], session_memories: typing.List[context.SessionMemoryContext], selected_task: task_routing.SelectedTaskContext, candidate_memories: typing.List[RetrievedMemoryCandidate], relevance_memories: typing.List[RelevanceMemoryContext], machine_state: context.MachineStateContext, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def SelectRelevantMemories__build_request_stream_async(current_user_request: str, current_conversation: typing.Optional[context.ConversationHistory], session_memories: typing.List[context.SessionMemoryContext], selected_task: task_routing.SelectedTaskContext, candidate_memories: typing.List[RetrievedMemoryCandidate], relevance_memories: typing.List[RelevanceMemoryContext], machine_state: context.MachineStateContext, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.http.Request:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def SelectRelevantMemories__parse(json: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> RelevantMemoryDecision:
    """Raises:
        LlmClient"""
async def SelectRelevantMemories__parse_async(json: str, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> RelevantMemoryDecision:
    """Raises:
        LlmClient"""
def SelectRelevantMemories__parse_stream(sse: baml.http.SseStream, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.memory_selection.RelevantMemoryDecision], RelevantMemoryDecision]:
    """Raises:
        InvalidArgument, LlmClient"""
async def SelectRelevantMemories__parse_stream_async(sse: baml.http.SseStream, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.memory_selection.RelevantMemoryDecision], RelevantMemoryDecision]:
    """Raises:
        InvalidArgument, LlmClient"""
def SelectRelevantMemories__render_prompt(current_user_request: str, current_conversation: typing.Optional[context.ConversationHistory], session_memories: typing.List[context.SessionMemoryContext], selected_task: task_routing.SelectedTaskContext, candidate_memories: typing.List[RetrievedMemoryCandidate], relevance_memories: typing.List[RelevanceMemoryContext], machine_state: context.MachineStateContext, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.PromptAst:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
async def SelectRelevantMemories__render_prompt_async(current_user_request: str, current_conversation: typing.Optional[context.ConversationHistory], session_memories: typing.List[context.SessionMemoryContext], selected_task: task_routing.SelectedTaskContext, candidate_memories: typing.List[RetrievedMemoryCandidate], relevance_memories: typing.List[RelevanceMemoryContext], machine_state: context.MachineStateContext, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.PromptAst:
    """Raises:
        InvalidArgument, LlmClient, RenderPrompt"""
def SelectRelevantMemories_stream(current_user_request: str, current_conversation: typing.Optional[context.ConversationHistory], session_memories: typing.List[context.SessionMemoryContext], selected_task: task_routing.SelectedTaskContext, candidate_memories: typing.List[RetrievedMemoryCandidate], relevance_memories: typing.List[RelevanceMemoryContext], machine_state: context.MachineStateContext, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.memory_selection.RelevantMemoryDecision], RelevantMemoryDecision]:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
async def SelectRelevantMemories_stream_async(current_user_request: str, current_conversation: typing.Optional[context.ConversationHistory], session_memories: typing.List[context.SessionMemoryContext], selected_task: task_routing.SelectedTaskContext, candidate_memories: typing.List[RetrievedMemoryCandidate], relevance_memories: typing.List[RelevanceMemoryContext], machine_state: context.MachineStateContext, *, client: typing.Union[baml.llm.Client, UNSET] = UNSET) -> baml.llm.Stream[typing.Optional[stream_types.memory_selection.RelevantMemoryDecision], RelevantMemoryDecision]:
    """Raises:
        DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


def SelectedGraph(memories: retrieved_memory.RetrievedMemoryGraph, decision: RelevantMemoryDecision) -> retrieved_memory.RetrievedMemoryGraph: ...
async def SelectedGraph_async(memories: retrieved_memory.RetrievedMemoryGraph, decision: RelevantMemoryDecision) -> retrieved_memory.RetrievedMemoryGraph: ...


def RelevantSessionGraph(session: retrieved_memory.RetrievedSessionGraph, kept_ids: typing.List[str]) -> typing.Optional[retrieved_memory.RetrievedSessionGraph]: ...
async def RelevantSessionGraph_async(session: retrieved_memory.RetrievedSessionGraph, kept_ids: typing.List[str]) -> typing.Optional[retrieved_memory.RetrievedSessionGraph]: ...


def RelevantConversationGraph(conversation: retrieved_memory.RetrievedConversationGraph, kept_ids: typing.List[str]) -> typing.Optional[retrieved_memory.RetrievedConversationGraph]: ...
async def RelevantConversationGraph_async(conversation: retrieved_memory.RetrievedConversationGraph, kept_ids: typing.List[str]) -> typing.Optional[retrieved_memory.RetrievedConversationGraph]: ...


class RelevanceMemoryContext(pydantic.BaseModel):
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class RetrievedMemoryCandidate(pydantic.BaseModel):
    id: str
    kind: str
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str
    retrieval_matched: bool
    parent_session_id: typing.Optional[str]
    parent_conversation_id: typing.Optional[str]


class RelevantMemoryDecision(pydantic.BaseModel):
    kept_memory_ids: typing.List[str]
    candidate_memory: typing.Optional[memory_search.CandidateMemory]


__all__ = [
    "Candidates",
    "Candidates_async",
    "TaskCandidate",
    "TaskCandidate_async",
    "CurrentSessionMemoryCandidate",
    "CurrentSessionMemoryCandidate_async",
    "UserPreferenceCandidate",
    "UserPreferenceCandidate_async",
    "TaskCandidateDescription",
    "TaskCandidateDescription_async",
    "SessionCandidate",
    "SessionCandidate_async",
    "SessionMemoryCandidate",
    "SessionMemoryCandidate_async",
    "ConversationCandidate",
    "ConversationCandidate_async",
    "ConversationMessageCandidate",
    "ConversationMessageCandidate_async",
    "MessageMatchedMemorySearch",
    "MessageMatchedMemorySearch_async",
    "IsCurrentSession",
    "IsCurrentSession_async",
    "SelectRelevantMemories",
    "SelectRelevantMemories_async",
    "SelectRelevantMemories__build_request",
    "SelectRelevantMemories__build_request_async",
    "SelectRelevantMemories__build_request_stream",
    "SelectRelevantMemories__build_request_stream_async",
    "SelectRelevantMemories__parse",
    "SelectRelevantMemories__parse_async",
    "SelectRelevantMemories__parse_stream",
    "SelectRelevantMemories__parse_stream_async",
    "SelectRelevantMemories__render_prompt",
    "SelectRelevantMemories__render_prompt_async",
    "SelectRelevantMemories_stream",
    "SelectRelevantMemories_stream_async",
    "SelectedGraph",
    "SelectedGraph_async",
    "RelevantSessionGraph",
    "RelevantSessionGraph_async",
    "RelevantConversationGraph",
    "RelevantConversationGraph_async",
    "RelevanceMemoryContext",
    "RetrievedMemoryCandidate",
    "RelevantMemoryDecision",
]
