# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import typing
import pydantic


class Duration(pydantic.BaseModel):
    """
    Represents a non-localized timespan.
    
    May be negative: while `Instant` represents absolute points in time, a `Duration` represents the difference between two `Instant`s.
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    _nanoseconds: typing.Optional[int]


class Instant(pydantic.BaseModel):
    """
    Represents an absolute point in time.

    Attributes:
        _nanoseconds: Internal representation: the number of nanoseconds since the UNIX epoch.
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    _nanoseconds: typing.Optional[int]


class PlainDate(pydantic.BaseModel):
    """
    A civil date without a time or timezone, on the proleptic Gregorian
    calendar: `1979-05-27`.
    
    Equivalent to `Temporal.PlainDate` (TC39).

    Attributes:
        _days: Internal representation: days since 1970-01-01 on the proleptic
            Gregorian calendar.
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    _days: typing.Optional[int]


class PlainDateTime(pydantic.BaseModel):
    """
    A civil ("wall-clock") date and time without a timezone, on the proleptic
    Gregorian calendar: `1979-05-27T07:32:00`. It cannot be located on the
    global timeline without supplying a timezone via `to_zoned`.
    
    Equivalent to `Temporal.PlainDateTime` (TC39). The `Plain` prefix marks
    anything without a timezone, following TC39 Temporal.

    Attributes:
        _nanoseconds: Internal representation: the wall-clock reading encoded as nanoseconds
            since 1970-01-01T00:00:00, interpreting the reading as if it were UTC.
            This is a civil quantity, not an absolute time.
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    _nanoseconds: typing.Optional[int]


class PlainTime(pydantic.BaseModel):
    """
    A civil wall-clock time without a date or timezone: `07:32:00.5`.
    
    Equivalent to `Temporal.PlainTime` (TC39).

    Attributes:
        _nanoseconds: Internal representation: nanoseconds since midnight, in `[0, 24h)`.
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    _nanoseconds: typing.Optional[int]


class AmbiguousTimeError(pydantic.BaseModel):
    """
    Thrown when a civil time cannot be unambiguously located in a timezone
    (DST gap or overlap) and `disambiguation` is `"reject"`.
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    message: typing.Optional[str]


class TimeZoneOffset(pydantic.BaseModel):
    """
    A fixed offset from UTC, with a permitted range of ±24 hours (real
    timezones currently range from -12 to +14 hours).
    
    Note that unlike IANA identifiers, a `TimeZoneOffset` does not change
    based on daylight savings. Sometimes this is desirable, but other times
    it is not, so `ZonedDateTime` permits either.

    Attributes:
        _nanoseconds: Internal representation: the offset in nanoseconds. Invariant: within
            ±24 hours.
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    _nanoseconds: typing.Optional[int]


class UnknownTimezoneError(pydantic.BaseModel):
    """
    Thrown when an IANA timezone identifier cannot be resolved against the
    host's timezone database.
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    timezone: typing.Optional[str]


Disambiguation: typing.TypeAlias = typing.Union[typing.Literal["compatible"], typing.Literal["earlier"], typing.Literal["later"], typing.Literal["reject"]]


class ZonedDateTime(pydantic.BaseModel):
    """
    A timezone-aware point in time: an absolute instant plus a timezone —
    either a fixed offset (`-07:00`) or an IANA identifier
    (`America/Los_Angeles`).
    
    The timezone does not affect the absolute time; it affects the
    interpretation of date/time components and string formatting. The
    internal representation is an absolute time (like `Instant`) rather than
    calendar components, so values are unambiguous across DST transitions.
    
    Equivalent to `Temporal.ZonedDateTime` (TC39).

    Attributes:
        _nanoseconds: Internal representation: nanoseconds since the Unix epoch (an inlined
            `Instant`).
        _offset_ns: Internal: the fixed offset in nanoseconds, if the timezone is a fixed
            offset. Invariant: exactly one of `_offset_ns` / `_iana` is non-null.
        _iana: Internal: the IANA identifier, if the timezone is one.
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    _nanoseconds: typing.Optional[int]
    _offset_ns: typing.Optional[int]
    _iana: typing.Optional[str]


__all__ = [
    "Duration",
    "Instant",
    "PlainDate",
    "PlainDateTime",
    "PlainTime",
    "AmbiguousTimeError",
    "TimeZoneOffset",
    "UnknownTimezoneError",
    "Disambiguation",
    "ZonedDateTime",
]
