# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import typing
import pydantic


class Duration(pydantic.BaseModel):
    _nanoseconds: typing.Optional[int]


class Instant(pydantic.BaseModel):
    _nanoseconds: typing.Optional[int]


class PlainDate(pydantic.BaseModel):
    _days: typing.Optional[int]


class PlainDateTime(pydantic.BaseModel):
    _nanoseconds: typing.Optional[int]


class PlainTime(pydantic.BaseModel):
    _nanoseconds: typing.Optional[int]


class AmbiguousTimeError(pydantic.BaseModel):
    message: typing.Optional[str]


class TimeZoneOffset(pydantic.BaseModel):
    _nanoseconds: typing.Optional[int]


class UnknownTimezoneError(pydantic.BaseModel):
    timezone: typing.Optional[str]


Disambiguation: typing.TypeAlias = typing.Union[typing.Literal["compatible"], typing.Literal["earlier"], typing.Literal["later"], typing.Literal["reject"]]


class ZonedDateTime(pydantic.BaseModel):
    _nanoseconds: typing.Optional[int]
    _offset_ns: typing.Optional[int]
    _iana: typing.Optional[str]


__all__ = [
    "Duration",
    "Instant",
    "PlainDate",
    "PlainDateTime",
    "PlainTime",
    "AmbiguousTimeError",
    "TimeZoneOffset",
    "UnknownTimezoneError",
    "Disambiguation",
    "ZonedDateTime",
]
