# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import typing
import pydantic

if typing.TYPE_CHECKING:
    from .. import baml
    from .. import stream_types
    from .. import task_catalog
    from .. import turn_context

from baml_bridge import define_function as _define_function


class RetrievedTaskNode(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: str
    name: str
    description: str
    input: str
    output: str
    prompt: str
    provider_id: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class RetrievedSessionNode(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: str
    name: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class RetrievedSessionMemoryNode(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: str
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class RetrievedConversationNode(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: str
    name: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class RetrievedConversationMessageNode(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: str
    role: str
    content: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class RetrievedConversationGraph(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    conversation: RetrievedConversationNode
    matched: bool
    messages: typing.List[RetrievedConversationMessageNode]
    matched_message_ids: typing.List[str]


class RetrievedSessionGraph(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    session: RetrievedSessionNode
    matched: bool
    conversations: typing.List[RetrievedConversationGraph]
    session_memories: typing.List[RetrievedSessionMemoryNode]


class RetrievedMemoryGraph(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    task_catalog: typing.List[RetrievedTaskNode]
    past_sessions: typing.List[RetrievedSessionGraph]
    current_session_memories: typing.List[RetrievedSessionMemoryNode]


ChooseMemorySearchDepths       = _define_function("user.memory.ChooseMemorySearchDepths", "sync",  ["current_timestamp", "current_user_request", "current_conversation", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories", "machine_state"], ["client"])
ChooseMemorySearchDepths.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
ChooseMemorySearchDepths_async = _define_function("user.memory.ChooseMemorySearchDepths", "async", ["current_timestamp", "current_user_request", "current_conversation", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories", "machine_state"], ["client"])
ChooseMemorySearchDepths_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
ChooseMemorySearchDepths__build_request       = _define_function("user.memory.ChooseMemorySearchDepths$build_request", "sync",  ["current_timestamp", "current_user_request", "current_conversation", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories", "machine_state"], ["client"])
ChooseMemorySearchDepths__build_request.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearchDepths__build_request_async = _define_function("user.memory.ChooseMemorySearchDepths$build_request", "async", ["current_timestamp", "current_user_request", "current_conversation", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories", "machine_state"], ["client"])
ChooseMemorySearchDepths__build_request_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearchDepths__build_request_stream       = _define_function("user.memory.ChooseMemorySearchDepths$build_request_stream", "sync",  ["current_timestamp", "current_user_request", "current_conversation", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories", "machine_state"], ["client"])
ChooseMemorySearchDepths__build_request_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearchDepths__build_request_stream_async = _define_function("user.memory.ChooseMemorySearchDepths$build_request_stream", "async", ["current_timestamp", "current_user_request", "current_conversation", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories", "machine_state"], ["client"])
ChooseMemorySearchDepths__build_request_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearchDepths__parse       = _define_function("user.memory.ChooseMemorySearchDepths$parse", "sync",  ["json"], ["client"])
ChooseMemorySearchDepths__parse.__doc__ = """Raises:
    ParseError"""
ChooseMemorySearchDepths__parse_async = _define_function("user.memory.ChooseMemorySearchDepths$parse", "async", ["json"], ["client"])
ChooseMemorySearchDepths__parse_async.__doc__ = """Raises:
    ParseError"""
ChooseMemorySearchDepths__parse_stream       = _define_function("user.memory.ChooseMemorySearchDepths$parse_stream", "sync",  ["sse"], ["client"])
ChooseMemorySearchDepths__parse_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
ChooseMemorySearchDepths__parse_stream_async = _define_function("user.memory.ChooseMemorySearchDepths$parse_stream", "async", ["sse"], ["client"])
ChooseMemorySearchDepths__parse_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
ChooseMemorySearchDepths__render_prompt       = _define_function("user.memory.ChooseMemorySearchDepths$render_prompt", "sync",  ["current_timestamp", "current_user_request", "current_conversation", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories", "machine_state"], ["client"])
ChooseMemorySearchDepths__render_prompt.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearchDepths__render_prompt_async = _define_function("user.memory.ChooseMemorySearchDepths$render_prompt", "async", ["current_timestamp", "current_user_request", "current_conversation", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories", "machine_state"], ["client"])
ChooseMemorySearchDepths__render_prompt_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearchDepths_stream       = _define_function("user.memory.ChooseMemorySearchDepths$stream", "sync",  ["current_timestamp", "current_user_request", "current_conversation", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories", "machine_state"], ["client"])
ChooseMemorySearchDepths_stream.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
ChooseMemorySearchDepths_stream_async = _define_function("user.memory.ChooseMemorySearchDepths$stream", "async", ["current_timestamp", "current_user_request", "current_conversation", "session_memories", "selected_task", "memory_search_hints", "search_domains", "search_depth_memories", "machine_state"], ["client"])
ChooseMemorySearchDepths_stream_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


SearchDomains       = _define_function("user.memory.SearchDomains", "sync",  [])
SearchDomains_async = _define_function("user.memory.SearchDomains", "async", [])


ChooseMemorySearch       = _define_function("user.memory.ChooseMemorySearch", "sync",  ["current_user_request", "current_conversation", "session_memories", "selected_task", "conversation_evaluation_memories", "machine_state"], ["client"])
ChooseMemorySearch.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
ChooseMemorySearch_async = _define_function("user.memory.ChooseMemorySearch", "async", ["current_user_request", "current_conversation", "session_memories", "selected_task", "conversation_evaluation_memories", "machine_state"], ["client"])
ChooseMemorySearch_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
ChooseMemorySearch__build_request       = _define_function("user.memory.ChooseMemorySearch$build_request", "sync",  ["current_user_request", "current_conversation", "session_memories", "selected_task", "conversation_evaluation_memories", "machine_state"], ["client"])
ChooseMemorySearch__build_request.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearch__build_request_async = _define_function("user.memory.ChooseMemorySearch$build_request", "async", ["current_user_request", "current_conversation", "session_memories", "selected_task", "conversation_evaluation_memories", "machine_state"], ["client"])
ChooseMemorySearch__build_request_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearch__build_request_stream       = _define_function("user.memory.ChooseMemorySearch$build_request_stream", "sync",  ["current_user_request", "current_conversation", "session_memories", "selected_task", "conversation_evaluation_memories", "machine_state"], ["client"])
ChooseMemorySearch__build_request_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearch__build_request_stream_async = _define_function("user.memory.ChooseMemorySearch$build_request_stream", "async", ["current_user_request", "current_conversation", "session_memories", "selected_task", "conversation_evaluation_memories", "machine_state"], ["client"])
ChooseMemorySearch__build_request_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearch__parse       = _define_function("user.memory.ChooseMemorySearch$parse", "sync",  ["json"], ["client"])
ChooseMemorySearch__parse.__doc__ = """Raises:
    ParseError"""
ChooseMemorySearch__parse_async = _define_function("user.memory.ChooseMemorySearch$parse", "async", ["json"], ["client"])
ChooseMemorySearch__parse_async.__doc__ = """Raises:
    ParseError"""
ChooseMemorySearch__parse_stream       = _define_function("user.memory.ChooseMemorySearch$parse_stream", "sync",  ["sse"], ["client"])
ChooseMemorySearch__parse_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
ChooseMemorySearch__parse_stream_async = _define_function("user.memory.ChooseMemorySearch$parse_stream", "async", ["sse"], ["client"])
ChooseMemorySearch__parse_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
ChooseMemorySearch__render_prompt       = _define_function("user.memory.ChooseMemorySearch$render_prompt", "sync",  ["current_user_request", "current_conversation", "session_memories", "selected_task", "conversation_evaluation_memories", "machine_state"], ["client"])
ChooseMemorySearch__render_prompt.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearch__render_prompt_async = _define_function("user.memory.ChooseMemorySearch$render_prompt", "async", ["current_user_request", "current_conversation", "session_memories", "selected_task", "conversation_evaluation_memories", "machine_state"], ["client"])
ChooseMemorySearch__render_prompt_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
ChooseMemorySearch_stream       = _define_function("user.memory.ChooseMemorySearch$stream", "sync",  ["current_user_request", "current_conversation", "session_memories", "selected_task", "conversation_evaluation_memories", "machine_state"], ["client"])
ChooseMemorySearch_stream.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
ChooseMemorySearch_stream_async = _define_function("user.memory.ChooseMemorySearch$stream", "async", ["current_user_request", "current_conversation", "session_memories", "selected_task", "conversation_evaluation_memories", "machine_state"], ["client"])
ChooseMemorySearch_stream_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


class ConversationEvaluationMemoryContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class SearchDepthMemoryContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class MemoryTagSearch(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    any_of: typing.List[str]
    all_of: typing.List[str]
    none_of: typing.List[str]


class MemoryStringSearch(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    contains: typing.List[str]
    equals: typing.List[str]


class CandidateMemory(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    title: str
    description: str


class SearchDepthDomain(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: str
    description: str
    searches: str
    hydrates: str


class SearchDepthTimestamps(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    created_after: str
    read_after: str
    updated_after: str


class ConversationMemorySearchHints(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    tags: MemoryTagSearch
    strings: MemoryStringSearch
    candidate_memory: typing.Optional[CandidateMemory]


class SearchDepthDecision(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    depths: typing.Dict[str, SearchDepthTimestamps]
    candidate_memory: typing.Optional[CandidateMemory]


Candidates       = _define_function("user.memory.Candidates", "sync",  ["memories", "current_session_id", "user_preferences"])
Candidates_async = _define_function("user.memory.Candidates", "async", ["memories", "current_session_id", "user_preferences"])


TaskCandidate       = _define_function("user.memory.TaskCandidate", "sync",  ["task"])
TaskCandidate_async = _define_function("user.memory.TaskCandidate", "async", ["task"])


CurrentSessionMemoryCandidate       = _define_function("user.memory.CurrentSessionMemoryCandidate", "sync",  ["memory", "current_session_id"])
CurrentSessionMemoryCandidate_async = _define_function("user.memory.CurrentSessionMemoryCandidate", "async", ["memory", "current_session_id"])


UserPreferenceCandidate       = _define_function("user.memory.UserPreferenceCandidate", "sync",  ["preference"])
UserPreferenceCandidate_async = _define_function("user.memory.UserPreferenceCandidate", "async", ["preference"])


TaskCandidateDescription       = _define_function("user.memory.TaskCandidateDescription", "sync",  ["task"])
TaskCandidateDescription_async = _define_function("user.memory.TaskCandidateDescription", "async", ["task"])


SessionCandidate       = _define_function("user.memory.SessionCandidate", "sync",  ["session", "is_current_session"])
SessionCandidate_async = _define_function("user.memory.SessionCandidate", "async", ["session", "is_current_session"])


SessionMemoryCandidate       = _define_function("user.memory.SessionMemoryCandidate", "sync",  ["session", "memory", "is_current_session"])
SessionMemoryCandidate_async = _define_function("user.memory.SessionMemoryCandidate", "async", ["session", "memory", "is_current_session"])


ConversationCandidate       = _define_function("user.memory.ConversationCandidate", "sync",  ["session", "conversation", "is_current_session"])
ConversationCandidate_async = _define_function("user.memory.ConversationCandidate", "async", ["session", "conversation", "is_current_session"])


ConversationMessageCandidate       = _define_function("user.memory.ConversationMessageCandidate", "sync",  ["session", "conversation", "message", "is_current_session"])
ConversationMessageCandidate_async = _define_function("user.memory.ConversationMessageCandidate", "async", ["session", "conversation", "message", "is_current_session"])


MessageMatchedMemorySearch       = _define_function("user.memory.MessageMatchedMemorySearch", "sync",  ["conversation", "message"])
MessageMatchedMemorySearch_async = _define_function("user.memory.MessageMatchedMemorySearch", "async", ["conversation", "message"])


IsCurrentSession       = _define_function("user.memory.IsCurrentSession", "sync",  ["session", "current_session_id"])
IsCurrentSession_async = _define_function("user.memory.IsCurrentSession", "async", ["session", "current_session_id"])


SelectRelevantMemories       = _define_function("user.memory.SelectRelevantMemories", "sync",  ["current_user_request", "current_conversation", "session_memories", "selected_task", "candidate_memories", "relevance_memories", "machine_state"], ["client"])
SelectRelevantMemories.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
SelectRelevantMemories_async = _define_function("user.memory.SelectRelevantMemories", "async", ["current_user_request", "current_conversation", "session_memories", "selected_task", "candidate_memories", "relevance_memories", "machine_state"], ["client"])
SelectRelevantMemories_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
SelectRelevantMemories__build_request       = _define_function("user.memory.SelectRelevantMemories$build_request", "sync",  ["current_user_request", "current_conversation", "session_memories", "selected_task", "candidate_memories", "relevance_memories", "machine_state"], ["client"])
SelectRelevantMemories__build_request.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
SelectRelevantMemories__build_request_async = _define_function("user.memory.SelectRelevantMemories$build_request", "async", ["current_user_request", "current_conversation", "session_memories", "selected_task", "candidate_memories", "relevance_memories", "machine_state"], ["client"])
SelectRelevantMemories__build_request_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
SelectRelevantMemories__build_request_stream       = _define_function("user.memory.SelectRelevantMemories$build_request_stream", "sync",  ["current_user_request", "current_conversation", "session_memories", "selected_task", "candidate_memories", "relevance_memories", "machine_state"], ["client"])
SelectRelevantMemories__build_request_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
SelectRelevantMemories__build_request_stream_async = _define_function("user.memory.SelectRelevantMemories$build_request_stream", "async", ["current_user_request", "current_conversation", "session_memories", "selected_task", "candidate_memories", "relevance_memories", "machine_state"], ["client"])
SelectRelevantMemories__build_request_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
SelectRelevantMemories__parse       = _define_function("user.memory.SelectRelevantMemories$parse", "sync",  ["json"], ["client"])
SelectRelevantMemories__parse.__doc__ = """Raises:
    ParseError"""
SelectRelevantMemories__parse_async = _define_function("user.memory.SelectRelevantMemories$parse", "async", ["json"], ["client"])
SelectRelevantMemories__parse_async.__doc__ = """Raises:
    ParseError"""
SelectRelevantMemories__parse_stream       = _define_function("user.memory.SelectRelevantMemories$parse_stream", "sync",  ["sse"], ["client"])
SelectRelevantMemories__parse_stream.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
SelectRelevantMemories__parse_stream_async = _define_function("user.memory.SelectRelevantMemories$parse_stream", "async", ["sse"], ["client"])
SelectRelevantMemories__parse_stream_async.__doc__ = """Raises:
    InvalidArgument, LlmClient"""
SelectRelevantMemories__render_prompt       = _define_function("user.memory.SelectRelevantMemories$render_prompt", "sync",  ["current_user_request", "current_conversation", "session_memories", "selected_task", "candidate_memories", "relevance_memories", "machine_state"], ["client"])
SelectRelevantMemories__render_prompt.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
SelectRelevantMemories__render_prompt_async = _define_function("user.memory.SelectRelevantMemories$render_prompt", "async", ["current_user_request", "current_conversation", "session_memories", "selected_task", "candidate_memories", "relevance_memories", "machine_state"], ["client"])
SelectRelevantMemories__render_prompt_async.__doc__ = """Raises:
    InvalidArgument, LlmClient, RenderPrompt"""
SelectRelevantMemories_stream       = _define_function("user.memory.SelectRelevantMemories$stream", "sync",  ["current_user_request", "current_conversation", "session_memories", "selected_task", "candidate_memories", "relevance_memories", "machine_state"], ["client"])
SelectRelevantMemories_stream.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""
SelectRelevantMemories_stream_async = _define_function("user.memory.SelectRelevantMemories$stream", "async", ["current_user_request", "current_conversation", "session_memories", "selected_task", "candidate_memories", "relevance_memories", "machine_state"], ["client"])
SelectRelevantMemories_stream_async.__doc__ = """Raises:
    DevOther, InvalidArgument, Io, LlmClient, RenderPrompt, Timeout"""


SelectedGraph       = _define_function("user.memory.SelectedGraph", "sync",  ["memories", "decision"])
SelectedGraph_async = _define_function("user.memory.SelectedGraph", "async", ["memories", "decision"])


RelevantSessionGraph       = _define_function("user.memory.RelevantSessionGraph", "sync",  ["session", "kept_ids"])
RelevantSessionGraph_async = _define_function("user.memory.RelevantSessionGraph", "async", ["session", "kept_ids"])


RelevantConversationGraph       = _define_function("user.memory.RelevantConversationGraph", "sync",  ["conversation", "kept_ids"])
RelevantConversationGraph_async = _define_function("user.memory.RelevantConversationGraph", "async", ["conversation", "kept_ids"])


class RelevanceMemoryContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str


class RetrievedMemoryCandidate(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: str
    kind: str
    title: str
    description: str
    tags: typing.List[str]
    created_at: str
    updated_at: str
    read_at: str
    retrieval_matched: bool
    parent_session_id: typing.Optional[str]
    parent_conversation_id: typing.Optional[str]


class RelevantMemoryDecision(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    kept_memory_ids: typing.List[str]
    candidate_memory: typing.Optional[CandidateMemory]


__all__ = [
    "RetrievedTaskNode",
    "RetrievedSessionNode",
    "RetrievedSessionMemoryNode",
    "RetrievedConversationNode",
    "RetrievedConversationMessageNode",
    "RetrievedConversationGraph",
    "RetrievedSessionGraph",
    "RetrievedMemoryGraph",
    "ChooseMemorySearchDepths",
    "ChooseMemorySearchDepths_async",
    "ChooseMemorySearchDepths__build_request",
    "ChooseMemorySearchDepths__build_request_async",
    "ChooseMemorySearchDepths__build_request_stream",
    "ChooseMemorySearchDepths__build_request_stream_async",
    "ChooseMemorySearchDepths__parse",
    "ChooseMemorySearchDepths__parse_async",
    "ChooseMemorySearchDepths__parse_stream",
    "ChooseMemorySearchDepths__parse_stream_async",
    "ChooseMemorySearchDepths__render_prompt",
    "ChooseMemorySearchDepths__render_prompt_async",
    "ChooseMemorySearchDepths_stream",
    "ChooseMemorySearchDepths_stream_async",
    "SearchDomains",
    "SearchDomains_async",
    "ChooseMemorySearch",
    "ChooseMemorySearch_async",
    "ChooseMemorySearch__build_request",
    "ChooseMemorySearch__build_request_async",
    "ChooseMemorySearch__build_request_stream",
    "ChooseMemorySearch__build_request_stream_async",
    "ChooseMemorySearch__parse",
    "ChooseMemorySearch__parse_async",
    "ChooseMemorySearch__parse_stream",
    "ChooseMemorySearch__parse_stream_async",
    "ChooseMemorySearch__render_prompt",
    "ChooseMemorySearch__render_prompt_async",
    "ChooseMemorySearch_stream",
    "ChooseMemorySearch_stream_async",
    "ConversationEvaluationMemoryContext",
    "SearchDepthMemoryContext",
    "MemoryTagSearch",
    "MemoryStringSearch",
    "CandidateMemory",
    "SearchDepthDomain",
    "SearchDepthTimestamps",
    "ConversationMemorySearchHints",
    "SearchDepthDecision",
    "Candidates",
    "Candidates_async",
    "TaskCandidate",
    "TaskCandidate_async",
    "CurrentSessionMemoryCandidate",
    "CurrentSessionMemoryCandidate_async",
    "UserPreferenceCandidate",
    "UserPreferenceCandidate_async",
    "TaskCandidateDescription",
    "TaskCandidateDescription_async",
    "SessionCandidate",
    "SessionCandidate_async",
    "SessionMemoryCandidate",
    "SessionMemoryCandidate_async",
    "ConversationCandidate",
    "ConversationCandidate_async",
    "ConversationMessageCandidate",
    "ConversationMessageCandidate_async",
    "MessageMatchedMemorySearch",
    "MessageMatchedMemorySearch_async",
    "IsCurrentSession",
    "IsCurrentSession_async",
    "SelectRelevantMemories",
    "SelectRelevantMemories_async",
    "SelectRelevantMemories__build_request",
    "SelectRelevantMemories__build_request_async",
    "SelectRelevantMemories__build_request_stream",
    "SelectRelevantMemories__build_request_stream_async",
    "SelectRelevantMemories__parse",
    "SelectRelevantMemories__parse_async",
    "SelectRelevantMemories__parse_stream",
    "SelectRelevantMemories__parse_stream_async",
    "SelectRelevantMemories__render_prompt",
    "SelectRelevantMemories__render_prompt_async",
    "SelectRelevantMemories_stream",
    "SelectRelevantMemories_stream_async",
    "SelectedGraph",
    "SelectedGraph_async",
    "RelevantSessionGraph",
    "RelevantSessionGraph_async",
    "RelevantConversationGraph",
    "RelevantConversationGraph_async",
    "RelevanceMemoryContext",
    "RetrievedMemoryCandidate",
    "RelevantMemoryDecision",
]
