# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import typing
import pydantic

from baml_core import define_function as _define_function


CoreTasks       = _define_function("user.agent_host_catalog.CoreTasks", "sync",  [])
CoreTasks_async = _define_function("user.agent_host_catalog.CoreTasks", "async", [])


class CoreTaskDefinition(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    name: str
    description: str
    input: str
    output: str
    prompt: str
    tags: typing.List[str]
    model_id: str
    reasoning_effort: typing.Optional[str]


__all__ = [
    "CoreTasks",
    "CoreTasks_async",
    "CoreTaskDefinition",
]
