# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import typing
import pydantic

from ... import stream_types


class TaskPromptComposition(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    task_input: typing.Optional[str]
    candidate_memory: typing.Optional[stream_types.memory_search.CandidateMemory]


class TaskPromptDecision(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    full_task_prompt: typing.Optional[str]
    candidate_memory: typing.Optional[stream_types.memory_search.CandidateMemory]


class TaskPromptMemoryContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    title: typing.Optional[str]
    description: typing.Optional[str]
    tags: typing.List[str]
    created_at: typing.Optional[str]
    updated_at: typing.Optional[str]
    read_at: typing.Optional[str]


class TaskPromptSelectedMemoryContext(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    title: typing.Optional[str]
    description: typing.Optional[str]
    tags: typing.List[str]
    created_at: typing.Optional[str]
    updated_at: typing.Optional[str]
    read_at: typing.Optional[str]


__all__ = [
    "TaskPromptComposition",
    "TaskPromptDecision",
    "TaskPromptMemoryContext",
    "TaskPromptSelectedMemoryContext",
]
