# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import typing
import pydantic

from baml_bridge import (
    BamlPyHandle as _BamlPyHandle,
    define_function as _define_function,
)


class ScanOptions(pydantic.BaseModel):
    """
    Options for `Glob.scan`.

    Attributes:
        cwd: Working directory to resolve relative patterns from.
        dot: Include dotfiles (hidden files starting with `.`).
        absolute: Return absolute paths instead of relative paths.
        follow_symlinks: Follow symbolic links when scanning.
        throw_error_on_broken_symlink: Throw an error if a broken symbolic link is encountered.
        only_files: Only return files, not directories.
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    cwd: typing.Optional[str]
    dot: typing.Optional[bool]
    absolute: typing.Optional[bool]
    follow_symlinks: typing.Optional[bool]
    throw_error_on_broken_symlink: typing.Optional[bool]
    only_files: typing.Optional[bool]


class Glob(pydantic.BaseModel):
    """A compiled glob pattern. Create one with `baml.glob.new(pattern)`."""
    model_config = pydantic.ConfigDict(extra="forbid")
    _handle: _BamlPyHandle
    scan       = _define_function("baml.glob.Glob.scan", "sync",  ["self", "root"])
    scan_async = _define_function("baml.glob.Glob.scan", "async", ["self", "root"])
    matches       = _define_function("baml.glob.Glob.matches", "sync",  ["self", "path"])
    matches_async = _define_function("baml.glob.Glob.matches", "async", ["self", "path"])


new       = _define_function("baml.glob.new", "sync",  ["pattern"])
new.__doc__ = """Compiles a glob `pattern` and returns a `Glob` object for scanning or matching.

Raises:
    Io"""
new_async = _define_function("baml.glob.new", "async", ["pattern"])
new_async.__doc__ = """Compiles a glob `pattern` and returns a `Glob` object for scanning or matching.

Raises:
    Io"""


__all__ = [
    "ScanOptions",
    "Glob",
    "new",
    "new_async",
]
