# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import typing
import pydantic

if typing.TYPE_CHECKING:
    from .... import baml
    from .... import stream_types

from baml_core import BamlPyHandle as _BamlPyHandle


TFinal = typing.TypeVar("TFinal")
TStream = typing.TypeVar("TStream")


class ExecutionContext(pydantic.BaseModel):
    jinja_string: typing.Optional[str]
    args: typing.Dict[str, typing.Any]
    function_name: typing.Optional[str]
    prompt_closure: typing.Optional[typing.Any]


class OrchestrationStep(pydantic.BaseModel):
    primitive_client: typing.Optional[PrimitiveClient]
    delay_ms: typing.Optional[int]


class PlannerState(pydantic.BaseModel):
    rr_client_names: typing.List[str]


class AnthropicOptions(pydantic.BaseModel):
    max_tokens: typing.Optional[int]


class AzureOpenAiOptions(pydantic.BaseModel):
    resource_name: typing.Optional[str]
    deployment_id: typing.Optional[str]
    api_version: typing.Optional[str]
    max_tokens: typing.Optional[int]


class BedrockOptions(pydantic.BaseModel):
    region: typing.Optional[str]
    endpoint_url: typing.Optional[str]
    access_key_id: typing.Optional[str]
    secret_access_key: typing.Optional[str]
    session_token: typing.Optional[str]
    profile: typing.Optional[str]
    stop_sequences: typing.Optional[typing.List[str]]
    max_tokens: typing.Optional[int]
    temperature: typing.Optional[float]
    top_p: typing.Optional[float]


class Client(pydantic.BaseModel):
    name: typing.Optional[str]
    client_type: typing.Optional[baml.llm.ClientType]
    sub_clients: typing.List[Client]
    retry: typing.Optional[RetryPolicy]
    counter: typing.Optional[int]


class Context(pydantic.BaseModel):
    client: typing.Optional[ContextClient]
    tags: typing.Dict[str, typing.Any]
    output_format: typing.Optional[str]
    _output_format: typing.Optional[OutputFormat]


class ContextClient(pydantic.BaseModel):
    name: typing.Optional[str]
    provider: typing.Optional[str]
    default_role: typing.Optional[str]
    allowed_roles: typing.List[str]


class MediaUrlHandler(pydantic.BaseModel):
    image: typing.Optional[str]
    audio: typing.Optional[str]
    video: typing.Optional[str]
    pdf: typing.Optional[str]


class OutputFormat(pydantic.BaseModel):
    _data: _BamlPyHandle


class PrimitiveClient(pydantic.BaseModel):
    name: typing.Optional[str]
    provider: typing.Optional[str]
    options: typing.Optional[PrimitiveClientOptions]


class PrimitiveClientOptions(pydantic.BaseModel):
    model: typing.Optional[str]
    base_url: typing.Optional[str]
    allowed_role_metadata: typing.Optional[typing.Any]
    finish_reason_allow_list: typing.Optional[typing.List[str]]
    finish_reason_deny_list: typing.Optional[typing.List[str]]
    supports_streaming: typing.Optional[bool]
    default_role: typing.Optional[str]
    allowed_roles: typing.Optional[typing.List[str]]
    remap_roles: typing.Optional[typing.Dict[str, str]]
    api_key: typing.Optional[str]
    provider_options: typing.Union[AnthropicOptions, AzureOpenAiOptions, BedrockOptions, VertexAiOptions, None]
    media_url_handler: typing.Optional[MediaUrlHandler]
    headers: typing.Dict[str, str]
    query_params: typing.Dict[str, str]
    request_body: typing.Dict[str, typing.Any]


class PromptAst(pydantic.BaseModel):
    _data: _BamlPyHandle


class RetryPolicy(pydantic.BaseModel):
    max_retries: typing.Optional[int]
    initial_delay_ms: typing.Optional[int]
    multiplier: typing.Optional[float]
    max_delay_ms: typing.Optional[int]


class Role(pydantic.BaseModel):
    name: typing.Optional[str]
    metadata: typing.Dict[str, typing.Any]


class Stream(pydantic.BaseModel, typing.Generic[TStream, TFinal]):
    _client: typing.Optional[PrimitiveClient]
    _acc: typing.Optional[StreamAccumulator]
    _sse: typing.Optional[stream_types.baml.http.SseStream]
    _cache: typing.Optional[StreamCache[TStream, TFinal]]


class StreamAccumulator(pydantic.BaseModel):
    _handle: _BamlPyHandle


class StreamCache(pydantic.BaseModel, typing.Generic[TStream, TFinal]):
    _data: _BamlPyHandle


class VertexAiOptions(pydantic.BaseModel):
    credentials: typing.Optional[str]
    credentials_content: typing.Optional[str]
    location: typing.Optional[str]
    project_id: typing.Optional[str]


__all__ = [
    "ExecutionContext",
    "OrchestrationStep",
    "PlannerState",
    "AnthropicOptions",
    "AzureOpenAiOptions",
    "BedrockOptions",
    "Client",
    "Context",
    "ContextClient",
    "MediaUrlHandler",
    "OutputFormat",
    "PrimitiveClient",
    "PrimitiveClientOptions",
    "PromptAst",
    "RetryPolicy",
    "Role",
    "Stream",
    "StreamAccumulator",
    "StreamCache",
    "VertexAiOptions",
]
