# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import typing
import pydantic

from .... import baml
from .... import stream_types

from baml_bridge import BamlPyHandle as _BamlPyHandle


T = typing.TypeVar("T")


class CsvError(pydantic.BaseModel):
    """
    A structured CSV error with positional diagnostics.
    
    `kind` is for portable handling; `line` / `record` / `field` / `column`
    make "row 41,283 has 7 fields, expected 8" diagnostics cheap.

    Attributes:
        kind
        message
        line: 1-based line in the source where the offending record starts.
        record: 0-based data-record index (header excluded).
        field: 0-based field index within the record.
        column: Header name, when known.
        expected: `FieldCount`: expected width.
        found: `FieldCount`: actual width.
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    kind: typing.Optional[baml.csv.CsvErrorKind]
    message: typing.Optional[str]
    line: typing.Optional[int]
    record: typing.Optional[int]
    field: typing.Optional[int]
    column: typing.Optional[str]
    expected: typing.Optional[int]
    found: typing.Optional[int]


class CsvHeaders(pydantic.BaseModel):
    """
    (internal) Marker: resolved header names (`null` when there are none).
    Do not use directly.
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    names: typing.Optional[typing.List[str]]


class CsvNeedData(pydantic.BaseModel):
    """
    (internal) Marker: the reader needs more input bytes before it can make
    progress. Do not use directly.
    """
    model_config = pydantic.ConfigDict(extra="forbid")


class CsvPosition(pydantic.BaseModel):
    """
    A position in a CSV source.

    Attributes:
        byte: 0-based byte offset into the source.
        line: 1-based line number.
        record: 0-based data-record index (header excluded).
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    byte: typing.Optional[int]
    line: typing.Optional[int]
    record: typing.Optional[int]


class CsvReader(pydantic.BaseModel):
    """
    A streaming CSV reader. Create one with `baml.csv.open` or
    `baml.csv.reader`.
    
    `CsvReader` is a lazy iterator over `CsvRecord` values: a multi-gigabyte
    file parses in constant memory, and every `baml.iter` adapter and default
    method (`map`, `filter`, `collect`, ...) works on it. There is one
    cursor; raw iteration, `rows<T>()`, and `headers()` all draw from the
    same stream.
    
    A thrown record error has already consumed the offending record: the
    parser resynchronizes at the next record boundary and the next call to
    `next()` continues. One corrupt cell costs exactly one record.
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    _handle: _BamlPyHandle
    _file: typing.Optional[stream_types.baml.fs.File]
    _on_skip: typing.Optional[typing.Any]
    _owns_file: typing.Optional[bool]


class CsvRecord(pydantic.BaseModel):
    """
    One raw CSV record. Yielded by iterating a `CsvReader`.
    
    Records have snapshot semantics: they remain valid after the reader
    advances. Cell access is lazy — `get<int>("amount")` converts one cell
    without touching the others.
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    _handle: _BamlPyHandle


class CsvRows(pydantic.BaseModel, typing.Generic[T]):
    """
    A typed iterator over a `CsvReader`, decoding each record into `T`.
    Create one with `CsvReader.rows<T>()`.
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    reader: typing.Optional[CsvReader]


class CsvSkip(pydantic.BaseModel):
    """
    (internal) Marker: a record was skipped under `on_error = "skip"`.
    Do not use directly.
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    error: typing.Optional[CsvError]


class CsvWriter(pydantic.BaseModel):
    """
    A streaming CSV writer. Create one with `baml.csv.create`,
    `baml.csv.writer`, or `baml.csv.buffer`.
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    _handle: _BamlPyHandle
    _file: typing.Optional[stream_types.baml.fs.File]
    _owns_file: typing.Optional[bool]


class ReaderOptions(pydantic.BaseModel):
    """
    Options for CSV readers. All fields are optional; `null` means default.
    
    `delimiter`, `quote`, `escape`, and `comment` must be single ASCII bytes
    and mutually distinct; violations throw `CsvError { kind: Options }` at
    construction.

    Attributes:
        delimiter: Field separator. Exactly one ASCII byte. Default `","` (`"\\t"` for TSV).
        quote: Quote character. Exactly one ASCII byte. Default `"\\""`.
        quoting: `false` treats quote bytes as ordinary data. Default `true`.
        escape: Escape byte for quotes. `null` (default) means RFC 4180 `""` doubling;
            setting it switches to escape-character dialects (`"\\\\"` for MySQL-style
            dumps).
        has_header: First record is the header. Default `true`.
        headers: Supply (`has_header = false`) or replace (`has_header = true`; the
            file's header row is consumed) column names.
        comment: Records whose first byte (outside quotes) matches are skipped. Off by
            default — `#` is valid data.
        trim: Strip leading/trailing ASCII space and tab from header and/or unquoted
            field values. Default `"none"`.
        skip_lines: Raw lines dropped before parsing begins (preamble junk, Excel `sep=;`
            lines, a Markdown code fence). Default `0`.
        skip_blank_records: Drop blank records. Default `true`.
        ragged: Ragged-record policy. `"strict"` (default): width mismatch throws
            `FieldCount`. `"pad"`: short records padded with empty cells (long ones
            still throw). `"truncate"`: long records cut to the expected width
            (short ones still throw).
        null_values: Unquoted cell texts (after trim) treated as null cells. Default `[]`.
        encoding: `"utf8"` (default) throws `Encoding` on invalid bytes; `"utf8-lossy"`
            substitutes U+FFFD.
        bom: A leading UTF-8 BOM is stripped by default so it never corrupts the
            first header name.
        on_error: Per-record error policy. `"throw"` (default): `next()` throws a
            `CsvError` for a malformed record and the reader resumes at the next
            record. `"skip"`: record-scoped errors are counted and skipped.
        on_skip: Observer invoked with each skipped record's `CsvError` when
            `on_error = "skip"`. Constant-memory alternative to `skipped()`.
        max_skipped: How many skipped `CsvError` values `skipped()` retains. Default 1000.
            `0` disables retention. `skipped_count()` stays exact regardless.
        limit: Stop after this many data records. Default unlimited.
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    delimiter: typing.Optional[str]
    quote: typing.Optional[str]
    quoting: typing.Optional[bool]
    escape: typing.Optional[str]
    has_header: typing.Optional[bool]
    headers: typing.Optional[typing.List[str]]
    comment: typing.Optional[str]
    trim: typing.Union[typing.Literal["none"], typing.Literal["headers"], typing.Literal["fields"], typing.Literal["all"], None]
    skip_lines: typing.Optional[int]
    skip_blank_records: typing.Optional[bool]
    ragged: typing.Union[typing.Literal["strict"], typing.Literal["pad"], typing.Literal["truncate"], None]
    null_values: typing.Optional[typing.List[str]]
    encoding: typing.Union[typing.Literal["utf8"], typing.Literal["utf8-lossy"], None]
    bom: typing.Union[typing.Literal["strip"], typing.Literal["keep"], None]
    on_error: typing.Union[typing.Literal["throw"], typing.Literal["skip"], None]
    on_skip: typing.Optional[typing.Any]
    max_skipped: typing.Optional[int]
    limit: typing.Optional[int]


class WriterOptions(pydantic.BaseModel):
    """
    Options for CSV writers. All fields are optional; `null` means default.

    Attributes:
        delimiter: Field separator. Exactly one ASCII byte. Default `","`.
        quote: Quote character. Exactly one ASCII byte. Default `"\\""`.
        quote_style: `"minimal"` (default): quote only fields containing the delimiter,
            quote, CR, or LF. `"all"`: quote every field. `"never"`: quote nothing;
            a field that would require quoting throws `Encode`.
        escape: `null` (default) means `""` doubling inside quoted fields.
        terminator: Record terminator. Default `"lf"`; `"crlf"` for strict RFC 4180 / Excel.
        write_header: Automatically emit a header before the first `write_row<T>`.
            Default `true`.
        headers: Override header names for typed writes (positional).
        null_value: How `null` serializes. Default `""`.
        bom: Emit a UTF-8 BOM (Excel's UTF-8 detection). Default `false`.
        sanitize_formulas: CSV-injection guard: prefix `'` to cells starting with `=`, `+`, `-`,
            `@`, tab, CR, or LF (including full-width variants). Mutates the data,
            which is why it is opt-in. Default `false`.
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    delimiter: typing.Optional[str]
    quote: typing.Optional[str]
    quote_style: typing.Union[typing.Literal["minimal"], typing.Literal["all"], typing.Literal["never"], None]
    escape: typing.Optional[str]
    terminator: typing.Union[typing.Literal["lf"], typing.Literal["crlf"], None]
    write_header: typing.Optional[bool]
    headers: typing.Optional[typing.List[str]]
    null_value: typing.Optional[str]
    bom: typing.Optional[bool]
    sanitize_formulas: typing.Optional[bool]


CsvValue: typing.TypeAlias = typing.Union[bool, int, int, float, str, None]


__all__ = [
    "CsvError",
    "CsvHeaders",
    "CsvNeedData",
    "CsvPosition",
    "CsvReader",
    "CsvRecord",
    "CsvRows",
    "CsvSkip",
    "CsvWriter",
    "ReaderOptions",
    "WriterOptions",
    "CsvValue",
]
