# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import typing
import pydantic

if typing.TYPE_CHECKING:
    from ... import stream_types
    from ... import task


class CompletedVoiceTaskCycle(pydantic.BaseModel):
    cycle_id: typing.Optional[str]
    understanding: typing.Optional[VoicePromptUnderstanding]
    retrieved_memories: typing.Optional[stream_types.memory.RetrievedMemoryGraph]
    continuation: typing.Optional[VoicePromptContinuation]
    attempt_id: typing.Optional[str]
    task_completion: typing.Optional[task.CompletionResult]


class PendingVoiceRequestResult(pydantic.BaseModel):
    ...


class SuccessfulVoiceTaskResult(pydantic.BaseModel):
    task_name: typing.Optional[str]
    completion_requirement: typing.Optional[str]
    output_summary: typing.Optional[str]


class VoiceTaskCompletionReview(pydantic.BaseModel):
    attempt_id: typing.Optional[str]
    completion_string: typing.Optional[str]
    output_summary: typing.Optional[str]
    completion: typing.Optional[task.CompletionResult]
    elapsed_ms: typing.Optional[int]


class VoiceTaskConversationScope(pydantic.BaseModel):
    current_human_reply_created_at: typing.Optional[str]
    active_human_reply_created_at: typing.List[str]


class VoiceTaskExecutionBoundaryResult(pydantic.BaseModel):
    attempt_id: typing.Optional[str]
    task_execution: typing.Optional[stream_types.task.TaskExecutionResult]


class VoiceTaskFailureReview(pydantic.BaseModel):
    attempt_id: typing.Optional[str]
    task_prompt: typing.Optional[str]
    completion_string: typing.Optional[str]
    output_summary: typing.Optional[str]
    earlier_refusal_reply_text: typing.Optional[str]
    decision: typing.Optional[stream_types.task.TaskFailureDecision]
    elapsed_ms: typing.Optional[int]


class VoiceTaskFlowContext(pydantic.BaseModel):
    cycle_id: typing.Optional[str]
    current_timestamp: typing.Optional[str]
    current_conversation: typing.Optional[stream_types.turn_context.ConversationHistory]
    session_memories: typing.List[stream_types.turn_context.SessionMemoryContext]
    user_preferences: typing.List[stream_types.turn_context.UserPreferenceMemoryContext]
    available_tasks: typing.List[stream_types.task_catalog.AvailableTask]
    task_choice_memories: typing.List[stream_types.task.TaskChoiceMemoryContext]
    conversation_evaluation_memories: typing.List[stream_types.memory.ConversationEvaluationMemoryContext]
    search_depth_memories: typing.List[stream_types.memory.SearchDepthMemoryContext]
    current_session_id: typing.Optional[str]
    relevance_memories: typing.List[stream_types.memory.RelevanceMemoryContext]
    task_prompt_memories: typing.List[stream_types.task.TaskPromptMemoryContext]
    machine_state: typing.Optional[stream_types.turn_context.MachineStateContext]


class VoiceTaskFlowResult(pydantic.BaseModel):
    cycle_id: typing.Optional[str]
    understanding: typing.Optional[VoicePromptUnderstanding]
    retrieved_memories: typing.Optional[stream_types.memory.RetrievedMemoryGraph]
    continuation: typing.Optional[VoicePromptContinuation]
    attempt_id: typing.Optional[str]
    task_completion: typing.Optional[task.CompletionResult]
    task_completion_ms: typing.Optional[int]
    completion_reviews: typing.List[VoiceTaskCompletionReview]
    failure_reviews: typing.List[VoiceTaskFailureReview]


class VoiceTaskNoActionResult(pydantic.BaseModel):
    cycle_id: typing.Optional[str]
    task_choice: typing.Optional[stream_types.task.TaskChoiceDecision]
    selected_task: typing.Optional[stream_types.task_catalog.SelectedTaskContext]
    task_choice_ms: typing.Optional[int]


VoiceRequestResultState: typing.TypeAlias = typing.Union[PendingVoiceRequestResult, VoiceTaskFlowResult, VoiceTaskNoActionResult]


VoiceTaskRunResult: typing.TypeAlias = typing.Union[VoiceTaskFlowResult, VoiceTaskNoActionResult]


class VoicePromptContinuation(pydantic.BaseModel):
    relevance_decision: typing.Optional[stream_types.memory.RelevantMemoryDecision]
    selected_memories: typing.Optional[stream_types.memory.RetrievedMemoryGraph]
    selected_memory_contexts: typing.List[stream_types.task.TaskPromptSelectedMemoryContext]
    task_prompt: typing.Optional[stream_types.task.TaskPromptDecision]
    timings: typing.Optional[VoicePromptContinuationTimings]


class VoicePromptContinuationTimings(pydantic.BaseModel):
    memory_relevance_ms: typing.Optional[int]
    task_prompt_ms: typing.Optional[int]


class VoicePromptUnderstanding(pydantic.BaseModel):
    task_choice: typing.Optional[stream_types.task.TaskChoiceDecision]
    selected_task: typing.Optional[stream_types.task_catalog.SelectedTaskContext]
    memory_search_hints: typing.Optional[stream_types.memory.ConversationMemorySearchHints]
    search_depths: typing.Optional[stream_types.memory.SearchDepthDecision]
    timings: typing.Optional[VoicePromptUnderstandingTimings]


class VoicePromptUnderstandingTimings(pydantic.BaseModel):
    task_choice_ms: typing.Optional[int]
    memory_search_ms: typing.Optional[int]
    search_depth_ms: typing.Optional[int]


__all__ = [
    "CompletedVoiceTaskCycle",
    "PendingVoiceRequestResult",
    "SuccessfulVoiceTaskResult",
    "VoiceTaskCompletionReview",
    "VoiceTaskConversationScope",
    "VoiceTaskExecutionBoundaryResult",
    "VoiceTaskFailureReview",
    "VoiceTaskFlowContext",
    "VoiceTaskFlowResult",
    "VoiceTaskNoActionResult",
    "VoiceRequestResultState",
    "VoiceTaskRunResult",
    "VoicePromptContinuation",
    "VoicePromptContinuationTimings",
    "VoicePromptUnderstanding",
    "VoicePromptUnderstandingTimings",
]
