# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import typing
import pydantic

from ... import workspace


class CheckpointSelection(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    paths: typing.List[str]
    reasons: typing.Dict[str, str]


class FilesystemMemoryReference(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    id: typing.Optional[str]
    title: typing.Optional[str]
    description: typing.Optional[str]
    tags: typing.List[str]


class WorkspaceChange(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    path: typing.Optional[str]
    change_kind: typing.Union[typing.Literal["create"], typing.Literal["write"], typing.Literal["rename"], typing.Literal["delete"], typing.Literal["metadata"]]
    size_bytes: typing.Optional[int]


class WorkspacePlan(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    memory_ids: typing.List[str]
    prefetch_paths: typing.List[str]
    rules: typing.List[WorkspacePolicyRule]


class WorkspacePolicyRule(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    path_glob: typing.Optional[str]
    materialization: typing.Optional[workspace.Materialization]
    retention: typing.Optional[workspace.Retention]
    provenance: typing.Optional[str]


__all__ = [
    "CheckpointSelection",
    "FilesystemMemoryReference",
    "WorkspaceChange",
    "WorkspacePlan",
    "WorkspacePolicyRule",
]
