# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import typing
import typing_extensions
import pydantic

from .... import stream_types


Item = typing_extensions.TypeAliasType("Item", typing.Union["Table", typing.List["Item"], bool, int, float, str, "stream_types.baml.time.ZonedDateTime", "stream_types.baml.time.PlainDateTime", "stream_types.baml.time.PlainDate", "stream_types.baml.time.PlainTime"])


class Table(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    items: typing.Dict[str, Item]


class TomlParseError(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    message: typing.Optional[str]


__all__ = [
    "Item",
    "Table",
    "TomlParseError",
]
