# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import typing


def input(prompt: typing.Optional[str]) -> str:
    """Reads a line of text from stdin. If `prompt` is provided, it is printed first (without a newline)."""
async def input_async(prompt: typing.Optional[str]) -> str:
    """Reads a line of text from stdin. If `prompt` is provided, it is printed first (without a newline)."""


def print(s: str) -> None:
    """Write `s` to stdout with no trailing newline. Flushes immediately so the
    bytes are visible before the next sysop or await suspends the thread."""
async def print_async(s: str) -> None:
    """Write `s` to stdout with no trailing newline. Flushes immediately so the
    bytes are visible before the next sysop or await suspends the thread."""


def println(s: str) -> None:
    """Write `s` to stdout followed by a newline."""
async def println_async(s: str) -> None:
    """Write `s` to stdout followed by a newline."""


def eprint(s: str) -> None:
    """Like `print` but writes to stderr."""
async def eprint_async(s: str) -> None:
    """Like `print` but writes to stderr."""


def eprintln(s: str) -> None:
    """Like `println` but writes to stderr."""
async def eprintln_async(s: str) -> None:
    """Like `println` but writes to stderr."""


__all__ = [
    "input",
    "input_async",
    "print",
    "print_async",
    "println",
    "println_async",
    "eprint",
    "eprint_async",
    "eprintln",
    "eprintln_async",
]
