# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import enum
import typing
import pydantic


E = typing.TypeVar("E")
Err = typing.TypeVar("Err")
T = typing.TypeVar("T")


class FutureState(str, enum.Enum):
    Pending = "Pending"
    Ready = "Ready"
    Error = "Error"
    Cancelled = "Cancelled"


class Future(pydantic.BaseModel, typing.Generic[T, E]):
    def cancel(self) -> bool:
        """Request cancellation of the future. If the future is already
        settled, this is a no-op and returns `false`. Otherwise the
        future's cancel token fires; the spawned thread will throw
        `baml.panics.Cancelled` at its next `await` point.

        Returns `true` if a transition to the Cancelled state was
        performed, `false` if the future was already settled."""
    async def cancel_async(self) -> bool:
        """Request cancellation of the future. If the future is already
        settled, this is a no-op and returns `false`. Otherwise the
        future's cancel token fires; the spawned thread will throw
        `baml.panics.Cancelled` at its next `await` point.

        Returns `true` if a transition to the Cancelled state was
        performed, `false` if the future was already settled."""
    def is_settled(self) -> bool:
        """`true` if the future has reached a terminal state (Ready, Error,
        or Cancelled). Once `true`, this method's result never changes."""
    async def is_settled_async(self) -> bool:
        """`true` if the future has reached a terminal state (Ready, Error,
        or Cancelled). Once `true`, this method's result never changes."""
    def is_cancelled(self) -> bool:
        """`true` if the future was cancelled before producing a value.
        Implies `is_settled() == true`."""
    async def is_cancelled_async(self) -> bool:
        """`true` if the future was cancelled before producing a value.
        Implies `is_settled() == true`."""
    def is_result(self) -> bool:
        """`true` if the future settled with a successful value. Implies
        `is_settled() == true`."""
    async def is_result_async(self) -> bool:
        """`true` if the future settled with a successful value. Implies
        `is_settled() == true`."""
    def is_error(self) -> bool:
        """`true` if the future settled with an error. Implies
        `is_settled() == true`."""
    async def is_error_async(self) -> bool:
        """`true` if the future settled with an error. Implies
        `is_settled() == true`."""
    def state(self) -> FutureState: ...
    async def state_async(self) -> FutureState: ...


def all_complete(futures: typing.List[None], *, _types: dict[str, type]) -> None:
    """BEP-034 combinators over a homogeneous array of futures (all sharing value
    type `T` and error type `E`). The inputs are already running, so awaiting
    them — even in a loop — runs them concurrently; the combinator just decides
    how to combine the results. Each returns a new `Future`, so they compose.
    Await every future and return their values in input order. Like `all`, but
    the losers KEEP RUNNING on a failure (they are not cancelled). Throws the
    first error encountered in input order."""
async def all_complete_async(futures: typing.List[None], *, _types: dict[str, type]) -> None:
    """BEP-034 combinators over a homogeneous array of futures (all sharing value
    type `T` and error type `E`). The inputs are already running, so awaiting
    them — even in a loop — runs them concurrently; the combinator just decides
    how to combine the results. Each returns a new `Future`, so they compose.
    Await every future and return their values in input order. Like `all`, but
    the losers KEEP RUNNING on a failure (they are not cancelled). Throws the
    first error encountered in input order."""


def all(futures: typing.List[None], *, _types: dict[str, type]) -> None:
    """Await every future and return their values in input order, like
    `all_complete`, but on the FIRST failure the remaining futures are
    cancelled before the error is re-thrown (JS `Promise.all`). Use
    `all_complete` instead when losers have side effects that must finish.

    Note: failures are observed in input order (not strictly first-to-fail in
    wall-clock time); the value contract — every value, or one error — is the
    same either way."""
async def all_async(futures: typing.List[None], *, _types: dict[str, type]) -> None:
    """Await every future and return their values in input order, like
    `all_complete`, but on the FIRST failure the remaining futures are
    cancelled before the error is re-thrown (JS `Promise.all`). Use
    `all_complete` instead when losers have side effects that must finish.

    Note: failures are observed in input order (not strictly first-to-fail in
    wall-clock time); the value contract — every value, or one error — is the
    same either way."""


class AllFailed(pydantic.BaseModel, typing.Generic[E]):
    errors: typing.List[E]


def __await_any(futures: typing.List[None], *, _types: dict[str, type]) -> int:
    """BEP-034 internal primitive: suspend until the FIRST of `futures` settles —
    whether it succeeds, fails, or is cancelled — and return its index in input
    order. Compiles to a dedicated `AwaitAny` suspend point (it is `await` over
    many futures), and is the building block for `race` and `any`. The inputs
    are already running, so this only decides *which* settled first; it never
    re-throws (callers `await futures[i]` to observe the value or error)."""
async def __await_any_async(futures: typing.List[None], *, _types: dict[str, type]) -> int:
    """BEP-034 internal primitive: suspend until the FIRST of `futures` settles —
    whether it succeeds, fails, or is cancelled — and return its index in input
    order. Compiles to a dedicated `AwaitAny` suspend point (it is `await` over
    many futures), and is the building block for `race` and `any`. The inputs
    are already running, so this only decides *which* settled first; it never
    re-throws (callers `await futures[i]` to observe the value or error)."""


def race(futures: typing.List[None], *, _types: dict[str, type]) -> None:
    """Settle with the FIRST future to settle, whether it succeeds or fails; the
    remaining futures are cancelled (JS `Promise.race`). A fast failure from
    one input therefore wins the race — use `any` when you want the first
    SUCCESS. Racing an empty array never settles (matching JS)."""
async def race_async(futures: typing.List[None], *, _types: dict[str, type]) -> None:
    """Settle with the FIRST future to settle, whether it succeeds or fails; the
    remaining futures are cancelled (JS `Promise.race`). A fast failure from
    one input therefore wins the race — use `any` when you want the first
    SUCCESS. Racing an empty array never settles (matching JS)."""


def any(futures: typing.List[None], *, _types: dict[str, type]) -> None:
    """Settle with the first future to SUCCEED; the remaining futures are then
    cancelled (JS `Promise.any`). If every future fails, throws `AllFailed<E>`
    carrying all the errors in input order. Cancelled inputs are skipped (they
    neither win nor contribute an error)."""
async def any_async(futures: typing.List[None], *, _types: dict[str, type]) -> None:
    """Settle with the first future to SUCCEED; the remaining futures are then
    cancelled (JS `Promise.any`). If every future fails, throws `AllFailed<E>`
    carrying all the errors in input order. Cancelled inputs are skipped (they
    neither win nor contribute an error)."""


__all__ = [
    "FutureState",
    "Future",
    "all_complete",
    "all_complete_async",
    "all",
    "all_async",
    "AllFailed",
    "race",
    "race_async",
    "any",
    "any_async",
]
