# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import enum
import typing
import pydantic

from baml_bridge import define_function as _define_function


E = typing.TypeVar("E")
Err = typing.TypeVar("Err")
T = typing.TypeVar("T")


class FutureState(str, enum.Enum):
    """
    BEP-034 — concurrency via `spawn` / `await`.

    `Future<T, E>` is the handle returned by `spawn { body }`. Awaiting
    a future blocks the current thread until the future settles; on
    settle, `await` either yields the value or re-throws the future's
    error.

    Sys-op calls (e.g. `http.fetch`, `fs.read`) are not futures — they
    return their value directly and yield cooperatively under the hood.
    To run one concurrently, wrap it in `spawn { ... }`.

    The class is opaque to user code — its fields are runtime-managed.
    All operations on a future go through the methods declared below.

    State transitions: `Pending` → (`Ready` | `Error` | `Cancelled`).
    Once settled, a future never changes state again.
    Surface enumeration mirroring the runtime's `bex_vm_types::FutureRead`
    states. Used by `Future.state(self)` to expose the settle status of
    a future to BAML code.
    """
    Pending = "Pending"
    Ready = "Ready"
    Error = "Error"
    Cancelled = "Cancelled"


class Future(pydantic.BaseModel, typing.Generic[T, E]):
    model_config = pydantic.ConfigDict(extra="forbid")
    cancel       = _define_function("baml.future.Future.cancel", "sync",  ["self"], class_type_params=["T", "E"])
    cancel_async = _define_function("baml.future.Future.cancel", "async", ["self"], class_type_params=["T", "E"])
    is_settled       = _define_function("baml.future.Future.is_settled", "sync",  ["self"], class_type_params=["T", "E"])
    is_settled_async = _define_function("baml.future.Future.is_settled", "async", ["self"], class_type_params=["T", "E"])
    is_cancelled       = _define_function("baml.future.Future.is_cancelled", "sync",  ["self"], class_type_params=["T", "E"])
    is_cancelled_async = _define_function("baml.future.Future.is_cancelled", "async", ["self"], class_type_params=["T", "E"])
    is_result       = _define_function("baml.future.Future.is_result", "sync",  ["self"], class_type_params=["T", "E"])
    is_result_async = _define_function("baml.future.Future.is_result", "async", ["self"], class_type_params=["T", "E"])
    is_error       = _define_function("baml.future.Future.is_error", "sync",  ["self"], class_type_params=["T", "E"])
    is_error_async = _define_function("baml.future.Future.is_error", "async", ["self"], class_type_params=["T", "E"])
    state       = _define_function("baml.future.Future.state", "sync",  ["self"], class_type_params=["T", "E"])
    state_async = _define_function("baml.future.Future.state", "async", ["self"], class_type_params=["T", "E"])


all_complete       = _define_function("baml.future.all_complete", "sync",  ["futures"], type_params=["T", "E"])
all_complete_async = _define_function("baml.future.all_complete", "async", ["futures"], type_params=["T", "E"])


all       = _define_function("baml.future.all", "sync",  ["futures"], type_params=["T", "E"])
all_async = _define_function("baml.future.all", "async", ["futures"], type_params=["T", "E"])


class AllFailed(pydantic.BaseModel, typing.Generic[E]):
    """
    The error `any` throws when EVERY input future failed. `errors` holds the
    per-future errors in input order. (BEP-034; JS calls this `AggregateError`.)
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    errors: typing.List[E]


__await_any       = _define_function("baml.future.__await_any", "sync",  ["futures"], type_params=["T", "E"])
__await_any_async = _define_function("baml.future.__await_any", "async", ["futures"], type_params=["T", "E"])


race       = _define_function("baml.future.race", "sync",  ["futures"], type_params=["T", "E"])
race_async = _define_function("baml.future.race", "async", ["futures"], type_params=["T", "E"])


any       = _define_function("baml.future.any", "sync",  ["futures"], type_params=["T", "Err"])
any_async = _define_function("baml.future.any", "async", ["futures"], type_params=["T", "Err"])


__all__ = [
    "FutureState",
    "Future",
    "all_complete",
    "all_complete_async",
    "all",
    "all_async",
    "AllFailed",
    "race",
    "race_async",
    "any",
    "any_async",
]
