# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import typing
import pydantic

if typing.TYPE_CHECKING:
    from ... import baml

from baml_bridge import (
    BamlPyHandle as _BamlPyHandle,
    define_function as _define_function,
)


_timeout_nanos       = _define_function("baml.net._timeout_nanos", "sync",  ["timeout"])
_timeout_nanos_async = _define_function("baml.net._timeout_nanos", "async", ["timeout"])


class TcpStream(pydantic.BaseModel):
    """
    A TCP connection. Created by `baml.net.TcpStream.connect` or returned by
    `baml.net.TcpListener.accept`. Modeled on Rust's `std::net::TcpStream`.
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    _handle: _BamlPyHandle
    connect       = staticmethod(_define_function("baml.net.TcpStream.connect", "sync",  ["addr"], ["timeout"]))
    connect_async = staticmethod(_define_function("baml.net.TcpStream.connect", "async", ["addr"], ["timeout"]))
    _connect       = staticmethod(_define_function("baml.net.TcpStream._connect", "sync",  ["addr", "timeout_nanos"]))
    _connect_async = staticmethod(_define_function("baml.net.TcpStream._connect", "async", ["addr", "timeout_nanos"]))
    read       = _define_function("baml.net.TcpStream.read", "sync",  ["self"], ["timeout"])
    read_async = _define_function("baml.net.TcpStream.read", "async", ["self"], ["timeout"])
    _read       = _define_function("baml.net.TcpStream._read", "sync",  ["self", "timeout_nanos"])
    _read_async = _define_function("baml.net.TcpStream._read", "async", ["self", "timeout_nanos"])
    write       = _define_function("baml.net.TcpStream.write", "sync",  ["self", "data"], ["timeout"])
    write_async = _define_function("baml.net.TcpStream.write", "async", ["self", "data"], ["timeout"])
    _write       = _define_function("baml.net.TcpStream._write", "sync",  ["self", "data", "timeout_nanos"])
    _write_async = _define_function("baml.net.TcpStream._write", "async", ["self", "data", "timeout_nanos"])
    close       = _define_function("baml.net.TcpStream.close", "sync",  ["self"])
    close_async = _define_function("baml.net.TcpStream.close", "async", ["self"])


class TcpListener(pydantic.BaseModel):
    """
    A bound TCP listener. Created by `baml.net.TcpListener.bind`. Calling `accept`
    suspends the current BAML thread until an incoming connection arrives (or the
    thread is cancelled). Modeled on Rust's `std::net::TcpListener`.
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    _handle: _BamlPyHandle
    bind       = staticmethod(_define_function("baml.net.TcpListener.bind", "sync",  ["addr"]))
    bind_async = staticmethod(_define_function("baml.net.TcpListener.bind", "async", ["addr"]))
    accept       = _define_function("baml.net.TcpListener.accept", "sync",  ["self"])
    accept_async = _define_function("baml.net.TcpListener.accept", "async", ["self"])
    close       = _define_function("baml.net.TcpListener.close", "sync",  ["self"])
    close_async = _define_function("baml.net.TcpListener.close", "async", ["self"])


class UdpSocket(pydantic.BaseModel):
    """
    A UDP socket. Created by `baml.net.UdpSocket.bind`. UDP is connectionless and
    message-oriented: every `send_to` / `recv_from` carries a single datagram.
    Modeled on Rust's `std::net::UdpSocket`.
    """
    model_config = pydantic.ConfigDict(extra="forbid")
    _handle: _BamlPyHandle
    bind       = staticmethod(_define_function("baml.net.UdpSocket.bind", "sync",  ["addr"]))
    bind_async = staticmethod(_define_function("baml.net.UdpSocket.bind", "async", ["addr"]))
    send_to       = _define_function("baml.net.UdpSocket.send_to", "sync",  ["self", "data", "addr"], ["timeout"])
    send_to_async = _define_function("baml.net.UdpSocket.send_to", "async", ["self", "data", "addr"], ["timeout"])
    _send_to       = _define_function("baml.net.UdpSocket._send_to", "sync",  ["self", "data", "addr", "timeout_nanos"])
    _send_to_async = _define_function("baml.net.UdpSocket._send_to", "async", ["self", "data", "addr", "timeout_nanos"])
    recv_from       = _define_function("baml.net.UdpSocket.recv_from", "sync",  ["self"], ["timeout"])
    recv_from_async = _define_function("baml.net.UdpSocket.recv_from", "async", ["self"], ["timeout"])
    _recv_from       = _define_function("baml.net.UdpSocket._recv_from", "sync",  ["self", "timeout_nanos"])
    _recv_from_async = _define_function("baml.net.UdpSocket._recv_from", "async", ["self", "timeout_nanos"])
    close       = _define_function("baml.net.UdpSocket.close", "sync",  ["self"])
    close_async = _define_function("baml.net.UdpSocket.close", "async", ["self"])


class Datagram(pydantic.BaseModel):
    """A received UDP datagram: the payload bytes and the address of the sender."""
    model_config = pydantic.ConfigDict(extra="forbid")
    data: bytes
    addr: str


__all__ = [
    "TcpStream",
    "TcpListener",
    "UdpSocket",
    "Datagram",
]
