class AvailableTask {
    id: string,
    name: string,
    description: string,
    input: string,
    output: string,
    prompt: string,
    provider_id: string,
    model_id: string,
    created_at: string,
    updated_at: string,
    read_at: string,
}

class SelectedTaskContext {
    id: string,
    name: string,
    description: string,
    input: string,
    output: string,
    prompt: string,
    provider_id: string,
    model_id: string,
    created_at: string,
    updated_at: string,
    read_at: string,
}
