# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import typing
import pydantic

from ... import memory

if typing.TYPE_CHECKING:
    from ... import turn_context

from baml_bridge import define_function as _define_function


EmptyCandidateMemoryWriteBatch       = _define_function("user.memory.internal.EmptyCandidateMemoryWriteBatch", "sync",  [])
EmptyCandidateMemoryWriteBatch_async = _define_function("user.memory.internal.EmptyCandidateMemoryWriteBatch", "async", [])


CandidateMemoryCount       = _define_function("user.memory.internal.CandidateMemoryCount", "sync",  ["groups"])
CandidateMemoryCount_async = _define_function("user.memory.internal.CandidateMemoryCount", "async", ["groups"])


AddCandidateMemoryToGroup       = _define_function("user.memory.internal.AddCandidateMemoryToGroup", "sync",  ["group", "layer", "candidate"])
AddCandidateMemoryToGroup_async = _define_function("user.memory.internal.AddCandidateMemoryToGroup", "async", ["group", "layer", "candidate"])


HasSelectedCandidates       = _define_function("user.memory.internal.HasSelectedCandidates", "sync",  ["batch"])
HasSelectedCandidates_async = _define_function("user.memory.internal.HasSelectedCandidates", "async", ["batch"])


CandidateMemoryReviewInputs       = _define_function("user.memory.internal.CandidateMemoryReviewInputs", "sync",  ["groups", "context"])
CandidateMemoryReviewInputs_async = _define_function("user.memory.internal.CandidateMemoryReviewInputs", "async", ["groups", "context"])


AddCandidateMemoryReviewInput       = _define_function("user.memory.internal.AddCandidateMemoryReviewInput", "sync",  ["inputs", "layer", "candidates", "stored_memories"])
AddCandidateMemoryReviewInput_async = _define_function("user.memory.internal.AddCandidateMemoryReviewInput", "async", ["inputs", "layer", "candidates", "stored_memories"])


KeptCandidateMemories       = _define_function("user.memory.internal.KeptCandidateMemories", "sync",  ["candidates", "decision"])
KeptCandidateMemories_async = _define_function("user.memory.internal.KeptCandidateMemories", "async", ["candidates", "decision"])


CandidateMemoryWriteBatchFromReviews       = _define_function("user.memory.internal.CandidateMemoryWriteBatchFromReviews", "sync",  ["reviews"])
CandidateMemoryWriteBatchFromReviews_async = _define_function("user.memory.internal.CandidateMemoryWriteBatchFromReviews", "async", ["reviews"])


CandidateMemoryPurpose       = _define_function("user.memory.internal.CandidateMemoryPurpose", "sync",  ["layer"])
CandidateMemoryPurpose_async = _define_function("user.memory.internal.CandidateMemoryPurpose", "async", ["layer"])


EmptyCandidateMemoryReviewContext       = _define_function("user.memory.internal.EmptyCandidateMemoryReviewContext", "sync",  [])
EmptyCandidateMemoryReviewContext_async = _define_function("user.memory.internal.EmptyCandidateMemoryReviewContext", "async", [])


class CandidateMemoryReviewInput(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    layer: memory.CandidateMemoryLayer
    purpose: str
    candidates: typing.List[memory.CandidateMemoryEntry]
    stored_memories: typing.List[memory.StoredCandidateMemory]


class CandidateMemoryReview(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    layer: memory.CandidateMemoryLayer
    candidates: typing.List[memory.CandidateMemoryEntry]
    kept_candidates: typing.List[memory.CandidateMemoryEntry]


TaskCandidate       = _define_function("user.memory.internal.TaskCandidate", "sync",  ["task"])
TaskCandidate_async = _define_function("user.memory.internal.TaskCandidate", "async", ["task"])


CurrentSessionMemoryCandidate       = _define_function("user.memory.internal.CurrentSessionMemoryCandidate", "sync",  ["memory", "current_session_id"])
CurrentSessionMemoryCandidate_async = _define_function("user.memory.internal.CurrentSessionMemoryCandidate", "async", ["memory", "current_session_id"])


UserPreferenceCandidate       = _define_function("user.memory.internal.UserPreferenceCandidate", "sync",  ["preference"])
UserPreferenceCandidate_async = _define_function("user.memory.internal.UserPreferenceCandidate", "async", ["preference"])


TaskCandidateDescription       = _define_function("user.memory.internal.TaskCandidateDescription", "sync",  ["task"])
TaskCandidateDescription_async = _define_function("user.memory.internal.TaskCandidateDescription", "async", ["task"])


SessionCandidate       = _define_function("user.memory.internal.SessionCandidate", "sync",  ["session", "is_current_session"])
SessionCandidate_async = _define_function("user.memory.internal.SessionCandidate", "async", ["session", "is_current_session"])


SessionMemoryCandidate       = _define_function("user.memory.internal.SessionMemoryCandidate", "sync",  ["session", "memory", "is_current_session"])
SessionMemoryCandidate_async = _define_function("user.memory.internal.SessionMemoryCandidate", "async", ["session", "memory", "is_current_session"])


ConversationCandidate       = _define_function("user.memory.internal.ConversationCandidate", "sync",  ["session", "conversation", "is_current_session"])
ConversationCandidate_async = _define_function("user.memory.internal.ConversationCandidate", "async", ["session", "conversation", "is_current_session"])


ConversationMessageCandidate       = _define_function("user.memory.internal.ConversationMessageCandidate", "sync",  ["session", "conversation", "message", "is_current_session"])
ConversationMessageCandidate_async = _define_function("user.memory.internal.ConversationMessageCandidate", "async", ["session", "conversation", "message", "is_current_session"])


MessageMatchedMemorySearch       = _define_function("user.memory.internal.MessageMatchedMemorySearch", "sync",  ["conversation", "message"])
MessageMatchedMemorySearch_async = _define_function("user.memory.internal.MessageMatchedMemorySearch", "async", ["conversation", "message"])


IsCurrentSession       = _define_function("user.memory.internal.IsCurrentSession", "sync",  ["session", "current_session_id"])
IsCurrentSession_async = _define_function("user.memory.internal.IsCurrentSession", "async", ["session", "current_session_id"])


RelevantSessionGraph       = _define_function("user.memory.internal.RelevantSessionGraph", "sync",  ["session", "kept_ids"])
RelevantSessionGraph_async = _define_function("user.memory.internal.RelevantSessionGraph", "async", ["session", "kept_ids"])


RelevantConversationGraph       = _define_function("user.memory.internal.RelevantConversationGraph", "sync",  ["conversation", "kept_ids"])
RelevantConversationGraph_async = _define_function("user.memory.internal.RelevantConversationGraph", "async", ["conversation", "kept_ids"])


__all__ = [
    "EmptyCandidateMemoryWriteBatch",
    "EmptyCandidateMemoryWriteBatch_async",
    "CandidateMemoryCount",
    "CandidateMemoryCount_async",
    "AddCandidateMemoryToGroup",
    "AddCandidateMemoryToGroup_async",
    "HasSelectedCandidates",
    "HasSelectedCandidates_async",
    "CandidateMemoryReviewInputs",
    "CandidateMemoryReviewInputs_async",
    "AddCandidateMemoryReviewInput",
    "AddCandidateMemoryReviewInput_async",
    "KeptCandidateMemories",
    "KeptCandidateMemories_async",
    "CandidateMemoryWriteBatchFromReviews",
    "CandidateMemoryWriteBatchFromReviews_async",
    "CandidateMemoryPurpose",
    "CandidateMemoryPurpose_async",
    "EmptyCandidateMemoryReviewContext",
    "EmptyCandidateMemoryReviewContext_async",
    "CandidateMemoryReviewInput",
    "CandidateMemoryReview",
    "TaskCandidate",
    "TaskCandidate_async",
    "CurrentSessionMemoryCandidate",
    "CurrentSessionMemoryCandidate_async",
    "UserPreferenceCandidate",
    "UserPreferenceCandidate_async",
    "TaskCandidateDescription",
    "TaskCandidateDescription_async",
    "SessionCandidate",
    "SessionCandidate_async",
    "SessionMemoryCandidate",
    "SessionMemoryCandidate_async",
    "ConversationCandidate",
    "ConversationCandidate_async",
    "ConversationMessageCandidate",
    "ConversationMessageCandidate_async",
    "MessageMatchedMemorySearch",
    "MessageMatchedMemorySearch_async",
    "IsCurrentSession",
    "IsCurrentSession_async",
    "RelevantSessionGraph",
    "RelevantSessionGraph_async",
    "RelevantConversationGraph",
    "RelevantConversationGraph_async",
]
