# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import typing
import pydantic

if typing.TYPE_CHECKING:
    from ... import stream_types


class TaskExecutionResult(pydantic.BaseModel):
    returns: typing.List[TaskReturnItem]


class TaskReturnItem(pydantic.BaseModel):
    name: typing.Optional[str]
    payload: typing.Optional[typing.Dict[str, str]]


class TaskAttemptReply(pydantic.BaseModel):
    role: typing.Optional[str]
    content: typing.Optional[str]


class TaskPromptComposition(pydantic.BaseModel):
    task_input: typing.Optional[str]
    candidate_memory: typing.Optional[stream_types.memory.CandidateMemory]


class TaskPromptDecision(pydantic.BaseModel):
    full_task_prompt: typing.Optional[str]
    candidate_memory: typing.Optional[stream_types.memory.CandidateMemory]


class TaskPromptMemoryContext(pydantic.BaseModel):
    title: typing.Optional[str]
    description: typing.Optional[str]
    tags: typing.List[str]
    created_at: typing.Optional[str]
    updated_at: typing.Optional[str]
    read_at: typing.Optional[str]


class TaskPromptSelectedMemoryContext(pydantic.BaseModel):
    title: typing.Optional[str]
    description: typing.Optional[str]
    tags: typing.List[str]
    created_at: typing.Optional[str]
    updated_at: typing.Optional[str]
    read_at: typing.Optional[str]


class TaskFailureDecision(pydantic.BaseModel):
    validation_reply: typing.Optional[str]
    can_refine: typing.Optional[bool]


class TaskFailureResolution(pydantic.BaseModel):
    validation_reply: typing.Optional[str]
    can_refine: typing.Optional[bool]
    retry_context: typing.Optional[TaskRetryContext]
    retry_prompt: typing.Optional[str]


class TaskRetryContext(pydantic.BaseModel):
    previous_replies: typing.List[TaskAttemptReply]
    refusal_replies: typing.List[str]


class TaskChoiceDecision(pydantic.BaseModel):
    selected_task_id: typing.Optional[str]
    confidence: typing.Optional[float]
    candidate_memory: typing.Optional[stream_types.memory.CandidateMemory]


class TaskChoiceMemoryContext(pydantic.BaseModel):
    title: typing.Optional[str]
    description: typing.Optional[str]
    tags: typing.List[str]
    created_at: typing.Optional[str]
    updated_at: typing.Optional[str]
    read_at: typing.Optional[str]


__all__ = [
    "TaskExecutionResult",
    "TaskReturnItem",
    "TaskAttemptReply",
    "TaskPromptComposition",
    "TaskPromptDecision",
    "TaskPromptMemoryContext",
    "TaskPromptSelectedMemoryContext",
    "TaskFailureDecision",
    "TaskFailureResolution",
    "TaskRetryContext",
    "TaskChoiceDecision",
    "TaskChoiceMemoryContext",
]
