# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (16)
# #########################################################################

class AvailableTask(BaseModel):
    id: typing.Optional[str] = None
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None
    input: typing.Optional[str] = None
    output: typing.Optional[str] = None
    prompt: typing.Optional[str] = None
    provider_id: typing.Optional[str] = None
    created_at: typing.Optional[str] = None
    updated_at: typing.Optional[str] = None
    read_at: typing.Optional[str] = None

class CandidateMemory(BaseModel):
    title: typing.Optional[str] = None
    description: typing.Optional[str] = None

class ConversationEvaluationMemoryContext(BaseModel):
    title: typing.Optional[str] = None
    description: typing.Optional[str] = None
    tags: typing.List[str]
    created_at: typing.Optional[str] = None
    updated_at: typing.Optional[str] = None
    read_at: typing.Optional[str] = None

class ConversationHistory(BaseModel):
    id: typing.Optional[str] = None
    name: typing.Optional[str] = None
    created_at: typing.Optional[str] = None
    updated_at: typing.Optional[str] = None
    read_at: typing.Optional[str] = None
    messages: typing.List["ConversationHistoryMessage"]

class ConversationHistoryMessage(BaseModel):
    created_at: typing.Optional[str] = None
    updated_at: typing.Optional[str] = None
    read_at: typing.Optional[str] = None
    role: typing.Optional[str] = None
    content: typing.Optional[str] = None

class ConversationMemorySearchHints(BaseModel):
    tags: typing.Optional["MemoryTagSearch"] = None
    strings: typing.Optional["MemoryStringSearch"] = None
    candidate_memory: typing.Optional["CandidateMemory"] = None

class MemoryStringSearch(BaseModel):
    contains: typing.List[str]
    equals: typing.List[str]

class MemoryTagSearch(BaseModel):
    any_of: typing.List[str]
    all_of: typing.List[str]
    none_of: typing.List[str]

class SearchDepthDecision(BaseModel):
    depths: typing.Dict[str, "SearchDepthTimestamps"]
    candidate_memory: typing.Optional["CandidateMemory"] = None

class SearchDepthDomain(BaseModel):
    id: typing.Optional[str] = None
    description: typing.Optional[str] = None
    searches: typing.Optional[str] = None
    hydrates: typing.Optional[str] = None

class SearchDepthMemoryContext(BaseModel):
    title: typing.Optional[str] = None
    description: typing.Optional[str] = None
    tags: typing.List[str]
    created_at: typing.Optional[str] = None
    updated_at: typing.Optional[str] = None
    read_at: typing.Optional[str] = None

class SearchDepthTimestamps(BaseModel):
    created_after: typing.Optional[str] = None
    read_after: typing.Optional[str] = None
    updated_after: typing.Optional[str] = None

class SelectedTaskContext(BaseModel):
    id: typing.Optional[str] = None
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None
    input: typing.Optional[str] = None
    output: typing.Optional[str] = None
    prompt: typing.Optional[str] = None
    provider_id: typing.Optional[str] = None
    created_at: typing.Optional[str] = None
    updated_at: typing.Optional[str] = None
    read_at: typing.Optional[str] = None

class SessionMemoryContext(BaseModel):
    title: typing.Optional[str] = None
    description: typing.Optional[str] = None
    tags: typing.List[str]
    created_at: typing.Optional[str] = None
    updated_at: typing.Optional[str] = None
    read_at: typing.Optional[str] = None

class TaskChoiceDecision(BaseModel):
    selected_task_id: typing.Optional[str] = None
    confidence: typing.Optional[float] = None
    reason: typing.Optional[str] = None
    agent_thought: typing.Optional[str] = None
    candidate_memory: typing.Optional["CandidateMemory"] = None

class TaskChoiceMemoryContext(BaseModel):
    title: typing.Optional[str] = None
    description: typing.Optional[str] = None
    tags: typing.List[str]
    created_at: typing.Optional[str] = None
    updated_at: typing.Optional[str] = None
    read_at: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
